<?php
/**
 * Gutenverse Contact Us Contact content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Us Contact', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1290"},"height":{},"elementId":"guten-2cw8B7","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}}},"zIndex":{"Desktop":"2"},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="2cw8B7"><section class="wp-block-gutenverse-section guten-element guten-section guten-2cw8B7 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Ol0DVU","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Ol0DVU"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Ol0DVU"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-7MwyZd","title":"New York","titleTag":"h3","description":"914 Shore Lane Brooklyn, NY 11207","icon":"gtn gtn-apartment1-light","iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none"}},"containerBoxShadow":{"horizontal":"0","vertical":"0","blur":"11","spread":"5","color":{"r":104,"g":104,"b":104,"a":0.08}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"right":"5"}}},"iconColor":{"type":"variable","id":"renovater-accent"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"renovater-accent"}}},"titlePadding":{"Desktop":{},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"renovater-primary"},"titleTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"renovater-body-text"},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} -->
<div class="guten-element guten-7MwyZd animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-apartment1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">New York</h3><p class="icon-box-description">914 Shore Lane Brooklyn, NY 11207</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-Jic2xI","title":"London","titleTag":"h3","description":"56 Mill Road London WC14 8CJ","icon":"gtn gtn-cityscape-light","iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default"},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":""}}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"5"}}},"iconColor":{"r":51,"g":51,"b":51,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none","width":"1","color":{"r":51,"g":51,"b":51,"a":1}}},"titlePadding":{"Desktop":{},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":[]},"titleColor":{"r":51,"g":51,"b":51,"a":1},"titleTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"r":68,"g":68,"b":68,"a":1},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"400"},"background":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-Jic2xI animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-cityscape-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">London</h3><p class="icon-box-description">56 Mill Road London WC14 8CJ</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-05m450","title":"California","titleTag":"h3","description":"6 Hickory Road Westminster, CA 92683","icon":"gtn gtn-apartment-light","iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none"}},"containerBoxShadow":{"horizontal":"0","vertical":"0","blur":"11","spread":"5","color":{"r":104,"g":104,"b":104,"a":0.08}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"5"}}},"iconColor":{"type":"variable","id":"renovater-accent"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"renovater-accent"}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"renovater-primary"},"titleTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"renovater-body-text"},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-05m450 animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-apartment-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">California</h3><p class="icon-box-description">6 Hickory Road Westminster, CA 92683</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-CWslS9","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"boxShadow":{"color":{"r":5,"g":5,"b":5,"a":0.08},"horizontal":"0","vertical":"5","blur":"30"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","bottom":"0","right":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","left":"","right":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"80","bottom":"80","left":"80"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"20","left":"10"}}},"zIndex":{"Desktop":"5"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CWslS9 animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="CWslS9"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-xVVXx4","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-xVVXx4">Get In Touch</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Sw6m2j","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"renovater-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-Sw6m2j"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-TZtAs1","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":"2"}} -->
<form style="display:none" class="guten-element guten-form-builder guten-TZtAs1"><!-- wp:gutenverse/form-input-text {"elementId":"guten-3bX8Ol","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperColor":{"Desktop":[]},"helperPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputMargin":{"Desktop":{},"Mobile":[]},"placeholderColor":{"Desktop":{"r":160,"g":160,"b":160,"a":1}},"inputTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"inputColorNormal":{"Desktop":{"r":51,"g":51,"b":51,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-3bX8Ol hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-email {"elementId":"guten-oXyIca","showLabel":false,"showHelper":false,"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"r":160,"g":160,"b":160,"a":1}},"inputTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"inputColorNormal":{"Desktop":{"r":51,"g":51,"b":51,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"all":{"type":"solid","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-oXyIca hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-pK01mc","showLabel":false,"inputPlaceholder":"Your Subject","showHelper":false,"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"r":160,"g":160,"b":160,"a":1}},"inputTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"inputColorNormal":{"Desktop":{"r":51,"g":51,"b":51,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"all":{"type":"solid","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-pK01mc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-aM3jG3","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":[]},"inputHeight":{"Desktop":"160"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"r":160,"g":160,"b":160,"a":1}},"inputTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"inputColorNormal":{"Desktop":{"r":51,"g":51,"b":51,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"all":{"type":"solid","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-aM3jG3 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-8fxoMT","content":"Send Message","buttonBackground":{"type":"default","color":{"type":"variable","id":"renovater-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"renovater-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":""},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"button-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"renovater-background"},"alignButton":{"Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-8fxoMT"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-HrmcEJ","background":{},"backgroundHover":{},"border":{"radius":{"Desktop":[]}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-10","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"-5","right":"-5","bottom":"-5","left":"-5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"2","bottom":"2","right":"2","left":"2"}},"Mobile":[]},"zIndex":{"Desktop":""},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="HrmcEJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-HrmcEJ layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-q3lgRr","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-200","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"-120"}},"Mobile":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":""},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-q3lgRr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="q3lgRr"><div class="guten-column-wrapper"><!-- wp:gutenverse/google-maps {"elementId":"guten-oGEFfX","location":"Sessions House, Newington Causeway, London SE1 6AZ, United Kingdom","zoom":"16","height":{"Desktop":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-10"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"}} -->
<div class="guten-element gutenverse-maps guten-oGEFfX"><iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=Sessions%20House%2C%20Newington%20Causeway%2C%20London%20SE1%206AZ%2C%20United%20Kingdom&amp;z=16&amp;t=m&amp;output=embed&amp;iwloc=near" title="Sessions House, Newington Causeway, London SE1 6AZ, United Kingdom"></iframe></div>
<!-- /wp:gutenverse/google-maps --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
