<?php
/**
 * Gutenverse Pricing Plans content.
 */
return array(
	'title'      => __( 'Gutenverse Pricing Plans', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1290"},"height":{},"elementId":"guten-BTxsnc","background":{"type":"default","image":{"Desktop":{}},"position":{"Desktop":"top center"},"size":{"Desktop":"contain"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":""},"opacity":"","topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"150"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"40","left":"10"}}},"animation":{},"hideTablet":false,"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="BTxsnc"><section class="wp-block-gutenverse-section guten-element guten-section guten-BTxsnc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-DwVHwR","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DwVHwR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DwVHwR"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-rWHQoz","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"slideInUp"},"duration":"normal","delay":"0"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-rWHQoz animated guten-element-hide desktop-slideInUp">Choose Your Plan</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-c9qARx","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"type":"variable","id":"renovater-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"27","bottom":"","left":"27"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"8","bottom":"0","left":"8"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"150"}} -->
<div class="guten-element gutenverse-text-editor guten-c9qARx animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1290"},"isChild":true,"height":{},"gap":"no","elementId":"guten-EHsCUb","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="EHsCUb"><section class="wp-block-gutenverse-section guten-element guten-section guten-EHsCUb animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-q0oyJg","background":{"type":"default","color":{"r":248,"g":248,"b":248,"a":1}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"70"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-q0oyJg"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="q0oyJg"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-QQY36p","title":"Personal","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant","icon":"gtn gtn-man-light","iconSize":{"Desktop":"60"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"30","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"30","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"30","left":"20"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"renovater-background-2"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconColor":{"type":"variable","id":"renovater-accent"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"10","right":"","left":""}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"renovater-primary"},"titleTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{},"Mobile":[]},"descColor":{"type":"variable","id":"renovater-body-text"},"descTypography":{"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"}},"margin":{"Tablet":[]},"padding":{"Tablet":[]}} -->
<div class="guten-element guten-QQY36p guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-man-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Personal</h2><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-JZrwTn","spaceBetween":{"Desktop":"25"},"alignList":{"Desktop":"center"},"iconColor":{"type":"variable","id":"renovater-accent"},"textColor":{"type":"variable","id":"renovater-body-text"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"30","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-icon-list guten-JZrwTn"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-iVzWF2","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-iVzWF2"><a id="guten-iVzWF2"><i class="fas fa-check"></i><span class="list-text ">Fast Service</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-FdKBVl"} -->
<div class="guten-element guten-icon-list-item guten-FdKBVl"><a id="guten-FdKBVl"><i class="fas fa-check"></i><span class="list-text ">Design and Build</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-6BCTPi"} -->
<div class="guten-element guten-icon-list-item guten-6BCTPi"><a id="guten-6BCTPi"><i class="fas fa-check"></i><span class="list-text ">1 Month Maintenance</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-3pCpjc"} -->
<div class="guten-element guten-icon-list-item guten-3pCpjc"><a id="guten-3pCpjc"><i class="fas fa-check"></i><span class="list-text ">24/7 Support</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-kxHUr7","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"renovater-body-text"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-kxHUr7">$39</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Hjn6S2","textColor":{"type":"variable","id":"renovater-body-text"},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-Hjn6S2"><div class="text-content-inner"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">PER MONTH</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-6WYUGk","content":"Buy Now","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"renovater-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"renovater-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"button-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"renovater-background"}} -->
<div class="guten-element guten-button-wrapper guten-6WYUGk"><a class="guten-button guten-button-sm" href="#"><span>Buy Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-HMqas9","background":{"type":"default","color":{"r":248,"g":248,"b":248,"a":1}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":{}}},"boxShadow":{"color":{"r":121,"g":121,"b":121,"a":0.1},"horizontal":"0","vertical":"0","blur":"13","spread":"5"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-30","bottom":"-40"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"70"}},"Mobile":{}},"zIndex":{"Desktop":"10"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HMqas9"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HMqas9"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-zYxXeL","title":"Business","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant","icon":"gtn gtn-business-light","iconSize":{"Desktop":"60"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"55","right":"50","bottom":"30","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"30","left":"20"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"renovater-accent"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconColor":{"type":"variable","id":"renovater-primary"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"10","right":"","left":""}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"renovater-primary"},"titleTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{},"Mobile":[]},"descColor":{"type":"variable","id":"renovater-body-text"},"descTypography":{"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"}},"border":{"radius":{"Desktop":{}}}} -->
<div class="guten-element guten-zYxXeL guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-business-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Business</h2><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-Km4jIL","spaceBetween":{"Desktop":"25"},"alignList":{"Desktop":"center"},"iconColor":{"type":"variable","id":"renovater-accent"},"textColor":{"type":"variable","id":"renovater-body-text"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"30","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-icon-list guten-Km4jIL"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-vXHm5o","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-vXHm5o"><a id="guten-vXHm5o"><i class="fas fa-check"></i><span class="list-text ">Fast Service</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-r1khcQ"} -->
<div class="guten-element guten-icon-list-item guten-r1khcQ"><a id="guten-r1khcQ"><i class="fas fa-check"></i><span class="list-text ">Design and Build</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-mIk5G4"} -->
<div class="guten-element guten-icon-list-item guten-mIk5G4"><a id="guten-mIk5G4"><i class="fas fa-check"></i><span class="list-text ">1 Month Maintenance</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-4fPQSi"} -->
<div class="guten-element guten-icon-list-item guten-4fPQSi"><a id="guten-4fPQSi"><i class="fas fa-check"></i><span class="list-text ">24/7 Support</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-OLuykU","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-OLuykU">$69</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-No3Hro","textColor":{"type":"variable","id":"renovater-body-text"},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-No3Hro"><div class="text-content-inner"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">PER MONTH</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-1q3NBT","content":"Buy Now","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"renovater-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"renovater-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"button-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"renovater-background"}} -->
<div class="guten-element guten-button-wrapper guten-1q3NBT"><a class="guten-button guten-button-sm" href="#"><span>Buy Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-o7riyA","background":{"type":"default","color":{"r":248,"g":248,"b":248,"a":1}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"70"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-o7riyA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="o7riyA"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-0vSEgZ","title":"Enterprise","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant","icon":"gtn gtn-team-1-light","iconSize":{"Desktop":"60"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"30","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"30","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"30","left":"20"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"renovater-background-2"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconColor":{"type":"variable","id":"renovater-accent"},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"10","right":"","left":""}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"renovater-primary"},"titleTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{},"Mobile":[]},"descColor":{"type":"variable","id":"renovater-body-text"},"descTypography":{"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"}},"margin":{"Tablet":[]},"padding":{"Tablet":[]}} -->
<div class="guten-element guten-0vSEgZ guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-team-1-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Enterprise</h2><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-LQs8pG","spaceBetween":{"Desktop":"25"},"alignList":{"Desktop":"center"},"iconColor":{"type":"variable","id":"renovater-accent"},"textColor":{"type":"variable","id":"renovater-body-text"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"30","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-icon-list guten-LQs8pG"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-9JjDRH","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-9JjDRH"><a id="guten-9JjDRH"><i class="fas fa-check"></i><span class="list-text ">Fast Service</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-NkW5iA"} -->
<div class="guten-element guten-icon-list-item guten-NkW5iA"><a id="guten-NkW5iA"><i class="fas fa-check"></i><span class="list-text ">Design and Build</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-rJjNKS"} -->
<div class="guten-element guten-icon-list-item guten-rJjNKS"><a id="guten-rJjNKS"><i class="fas fa-check"></i><span class="list-text ">1 Month Maintenance</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-XtybnY"} -->
<div class="guten-element guten-icon-list-item guten-XtybnY"><a id="guten-XtybnY"><i class="fas fa-check"></i><span class="list-text ">24/7 Support</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-K18YL4","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-K18YL4">$99</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-A0o0DE","textColor":{"type":"variable","id":"renovater-body-text"},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-A0o0DE"><div class="text-content-inner"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">PER MONTH</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-dTnuIV","content":"Buy Now","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"renovater-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"renovater-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"button-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"renovater-background"}} -->
<div class="guten-element guten-button-wrapper guten-dTnuIV"><a class="guten-button guten-button-sm" href="#"><span>Buy Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
