<?php
/**
 * Gutenverse Home FAQ content.
 */
return array(
	'title'      => __( 'Gutenverse Home FAQ', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1290"},"height":{},"gap":"no","elementId":"guten-Crpm3R","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"30","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="Crpm3R"><section class="wp-block-gutenverse-section guten-element guten-section guten-Crpm3R layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-wLgsux","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","right":""}},"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"20","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wLgsux"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wLgsux"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ekMpPY","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"renovater-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-ekMpPY animated guten-element-hide desktop-fadeInLeft">FAQ</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Y6vPaB","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"renovater-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"150"}} -->
<div class="guten-element gutenverse-text-editor guten-Y6vPaB animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/accordions {"elementId":"guten-HYRz3U","iconOpen":"gtn gtn-up-arrow1-light","iconClosed":"gtn gtn-down-arrow1-light","iconPosition":"right","iconColor":{"type":"variable","id":"renovater-accent"},"iconActiveColor":{"type":"variable","id":"renovater-primary"},"titleTextColor":{"type":"variable","id":"renovater-primary"},"titleActiveColor":{"type":"variable","id":"renovater-primary"},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Mobile":{"unit":"em","point":"1.7"}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"28","right":"20","bottom":"28","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"contentTextColor":{"type":"variable","id":"renovater-body-text"},"contentTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"100","bottom":"45","left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"40","bottom":"25","left":"40"}}},"accordionBorder":{"radius":{"Desktop":{},"Mobile":[],"Tablet":[]},"all":{"type":"none","color":""}},"titleBorder":{"radius":{"Desktop":{},"Mobile":[]},"all":{"type":"none"}},"contentBorder":{"radius":{"Desktop":{},"Mobile":[]},"all":{"type":"none"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"accordionBorderActive":{"radius":{"Desktop":[]}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"25","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"contentBorderActive":{"radius":{"Desktop":[]}},"titleBackgroundActiveColor":{"type":"variable","id":"renovater-accent"},"titleBorderActive":{"radius":{"Desktop":{}}},"accordionBoxShadow":{"color":{"r":46,"g":46,"b":46,"a":0.1},"horizontal":"0","vertical":"0","blur":"10","spread":"1"}} -->
<div class="guten-element guten-accordions guten-HYRz3U animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/accordion {"elementId":"guten-WTgUPZ","iconOpen":"gtn gtn-up-arrow1-light","iconClosed":"gtn gtn-down-arrow1-light","iconPosition":"right"} -->
<div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">Does Your Company Have in House Architects and Engineers?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-up-arrow1-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-down-arrow1-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis natus ut perspiciatis unde omnis iste natus error</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-8PCeLk","iconOpen":"gtn gtn-up-arrow1-light","iconClosed":"gtn gtn-down-arrow1-light","iconPosition":"right"} -->
<div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">Does Your Company Have in House Architects and Engineers?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-up-arrow1-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-down-arrow1-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis natus ut perspiciatis unde omnis iste natus error</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-GbQRZJ","first":true,"iconOpen":"gtn gtn-up-arrow1-light","iconClosed":"gtn gtn-down-arrow1-light","iconPosition":"right"} -->
<div class="accordion-item active"><div class="accordion-heading"><span class="accordion-text">Does Your Company Have in House Architects and Engineers?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-up-arrow1-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-down-arrow1-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis natus ut perspiciatis unde omnis iste natus error</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3PZU9O","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"flex-end"},"border":{"radius":{"Desktop":[]},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3PZU9O hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3PZU9O"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Nw51dC","imgSrc":{"media":{"imageId":584,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-phone-communication-513218-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":260,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-phone-communication-513218-pxhere.com-260x300.webp","orientation":"portrait"},"large":{"height":1024,"width":888,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-phone-communication-513218-pxhere.com-888x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-phone-communication-513218-pxhere.com.webp","height":1488,"width":1290,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"400","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[]}},"align":{"Desktop":"right","Tablet":"center"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"-50","bottom":"-10","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","left":"0","bottom":"0","right":"0"}},"Tablet":{"unit":"%","dimension":{"top":"","right":"10","bottom":"","left":""}},"Mobile":[]},"positioningType":{"Tablet":"default"},"positioningAlign":{"Tablet":"flex-end"}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-Nw51dC animated guten-element-hide desktop-fadeInRight"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-phone-communication-513218-pxhere.com.webp" height="1488" width="1290"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
