<?php
/**
 * Gutenverse Fun Fact content.
 */
return array(
	'title'      => __( 'Gutenverse Fun Fact', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1290"},"height":{},"gap":"no","elementId":"guten-RbNAVf","background":{"type":"default","image":{"Desktop":{"id":549,"image":"' . esc_url( RENOVATER_URI ) . 'assets/img/abstract-architecture-structure-texture-window-glass-1158866-pxhere.com.webp"}},"position":{"Desktop":"bottom left"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","gradientColor":[{"color":"rgba(239, 170, 6, 1)","opacity":1,"active":true,"id":1,"offset":"0.220"},{"color":"rgba(0, 0, 0, 0.71)","active":false,"opacity":0.71,"id":2,"offset":"0.220"}],"gradientType":"linear","gradientAngle":"300","color":{"r":0,"g":0,"b":0,"a":0.7}},"opacity":"","topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"40","bottom":"60"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="RbNAVf"><section class="wp-block-gutenverse-section guten-element guten-section guten-RbNAVf layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-cfJMek","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cfJMek animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cfJMek"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1290"},"isChild":true,"height":{},"gap":"no","elementId":"guten-ZWpwTs","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="ZWpwTs"><section class="wp-block-gutenverse-section guten-element guten-section guten-ZWpwTs layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-2DFQrt","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-2DFQrt"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="2DFQrt"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-0GjeK6","icon":"gtn gtn-deal-light","iconColor":{"Desktop":{"type":"variable","id":"renovater-accent"}},"iconBorder":{"radius":{"Desktop":{}}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"200","suffix":"+","title":"Completed Projects","numberColor":{"Desktop":{"type":"variable","id":"renovater-background"}},"titleColor":{"Desktop":{"type":"variable","id":"renovater-background"}},"numberTypography":{"size":{"Mobile":{"point":"24","unit":"px"}}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":"30","left":"30","top":"","bottom":""}}},"animation":{"delay":"0","type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="guten-element guten-0GjeK6 animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-deal-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="200" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Completed Projects</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-QOn9VZ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QOn9VZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QOn9VZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-RBBBCR","icon":"gtn gtn-User-light","iconColor":{"Desktop":{"type":"variable","id":"renovater-accent"}},"iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"300","suffix":"+","title":"Happy Client","numberColor":{"Desktop":{"type":"variable","id":"renovater-background"}},"titleColor":{"Desktop":{"type":"variable","id":"renovater-background"}},"numberTypography":{"size":{"Mobile":{"point":"24","unit":"px"}}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":{},"Mobile":[]},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"35","bottom":"","left":"35"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-RBBBCR animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-User-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="300" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Happy Client</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-nuCbWo","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nuCbWo"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nuCbWo"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-UP9CQ0","icon":"gtn gtn-team-2-line","iconColor":{"Desktop":{"type":"variable","id":"renovater-accent"}},"iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"128","suffix":"","title":"Professional Team","numberColor":{"Desktop":{"type":"variable","id":"renovater-background"}},"titleColor":{"Desktop":{"type":"variable","id":"renovater-background"}},"numberTypography":{"size":{"Mobile":{"point":"24","unit":"px"}}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":{},"Mobile":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"30","left":"30"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-UP9CQ0 animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-2-line"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="128" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Professional Team</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-RCCMf7","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RCCMf7"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RCCMf7"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-f7Ee9j","icon":"gtn gtn-trophy-light","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"110","suffix":"","title":"Awards Winning","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"size":{"Mobile":{"point":"24","unit":"px"}}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":[],"Mobile":[]},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":"30","left":"30"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-f7Ee9j animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-trophy-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="110" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Awards Winning</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
