<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse About Detail', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-1cqS8n","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"","bottom":"100","left":""}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"70","bottom":"70"}}}} -->
<div class="section-wrapper" data-id="1cqS8n"><section class="wp-block-gutenverse-section guten-element guten-section guten-1cqS8n layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-XeCSiV","margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30"}},"Tablet":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"fast"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-XeCSiV animated guten-element-hide fast desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XeCSiV"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-x6oKYw","imgSrc":{"media":{"imageId":1256,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/StockSnap_WPFJXLWIZ7-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":200,"url":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/StockSnap_WPFJXLWIZ7-200x300.webp","orientation":"portrait"},"large":{"height":1024,"width":683,"url":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/StockSnap_WPFJXLWIZ7-683x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/StockSnap_WPFJXLWIZ7.webp","height":1920,"width":1280,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","height":{"Desktop":{"point":"500","unit":"px"},"Mobile":{"point":"300","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{},"Tablet":{}}},"opacity":"","imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"none"},"duration":"slow","delay":""},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{}},"padding":{"Tablet":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-x6oKYw slow"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/StockSnap_WPFJXLWIZ7.webp" height="1920" width="1280"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-xRVN06","margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"30"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"10","right":"","bottom":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"fast","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xRVN06 animated guten-element-hide fast desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="xRVN06"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-AzqEfW","type":3,"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"subtitle-font"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-AzqEfW">About Company</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-yv72Ro","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font"},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-yv72Ro">We Are Skilled In Providing Superior Service</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-IxJmZR","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-font"}} -->
<div class="guten-element gutenverse-text-editor guten-IxJmZR"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-TEI9Ps","margin":{"Desktop":{"unit":"px","dimension":{"top":"45","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"slow","delay":""}} -->
<div class="section-wrapper" data-id="TEI9Ps"><section class="wp-block-gutenverse-section guten-element guten-section guten-TEI9Ps slow layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-B6Fwbl","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"15","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-B6Fwbl"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="B6Fwbl"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-GM95E5","title":"Certified Team","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus ullamcorper.","icon":"gtn gtn-badge","iconSize":{"Desktop":"45","Tablet":"43"},"iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"containerBorder":{"radius":{"Desktop":{},"Mobile":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h5-font"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"text-font"}} -->
<div class="guten-element guten-GM95E5 guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-badge"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Certified Team</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus ullamcorper.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-o7YdRR","margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-o7YdRR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="o7YdRR"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-QGeZ1I","title":"Trusted Company","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus ullamcorper.","icon":"gtn gtn-team-1-light","iconSize":{"Desktop":"45","Tablet":"43"},"iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h5-font"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"text-font"},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","left":"15"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{}}} -->
<div class="guten-element guten-QGeZ1I guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-team-1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Trusted Company</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus ullamcorper.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
