<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Info', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-To7DvH","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"70","bottom":"70"}}}} -->
<div class="section-wrapper" data-id="To7DvH"><section class="wp-block-gutenverse-section guten-element guten-section guten-To7DvH layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50},"elementId":"guten-3QGmbh","border":{"radius":{"Desktop":{}},"all":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3QGmbh animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3QGmbh"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-oyA5WX","title":"Email Address","titleTag":"h3","description":"contac@domain.com\u003cbr\u003esupport@domain.com","icon":"gtn gtn-envelope2-light","iconSize":{"Desktop":"50","Tablet":"45","Mobile":"40"},"iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{},"Tablet":{}},"containerBackground":{"type":"default","color":{"type":"variable","id":"seventh"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{},"Tablet":{}},"all":{"type":"none","width":"","color":""}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h5-font"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"text-font"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}}} -->
<div class="guten-element guten-oyA5WX guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-envelope2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Email Address</h3><p class="icon-box-description">contac@domain.com<br>support@domain.com</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":null},"elementId":"guten-0zeeRi","border":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"10","right":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0zeeRi animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0zeeRi"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-xebTcp","title":"Call Us","titleTag":"h3","description":"+62 478-2240-190 (local)\u003cbr\u003e+62 478-2242-192 (from abroad)","icon":"gtn gtn-phone-light","iconSize":{"Desktop":"50","Tablet":"45","Mobile":"40"},"iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{}},"containerBackground":{"type":"default","color":{"type":"variable","id":"fourth"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"containerBoxShadow":{"vertical":"5","blur":"25","color":{"r":9,"g":31,"b":57,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h5-font"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"text-font"}} -->
<div class="guten-element guten-xebTcp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Call Us</h3><p class="icon-box-description">+62 478-2240-190 (local)<br>+62 478-2242-192 (from abroad)</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100,"Mobile":null},"elementId":"guten-tV8yH5","margin":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"20"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tV8yH5 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="tV8yH5"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-k9Vcue","title":"Visit Us","titleTag":"h3","description":"Hayam Wuruk Street, Denpasar City, Bali 80235, Indonesia","icon":"gtn gtn-map-marker1-light","iconSize":{"Desktop":"50","Tablet":"45","Mobile":"40"},"iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"60","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"seventh"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h5-font"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"text-font"}} -->
<div class="guten-element guten-k9Vcue guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-map-marker1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Visit Us</h3><p class="icon-box-description">Hayam Wuruk Street, Denpasar City, Bali 80235, Indonesia</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
