<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse Home Logo Slider', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-ZnsnoD","border":{"radius":{"Desktop":{}},"top":{"type":"solid","width":"0","color":{"r":231,"g":234,"b":241,"a":1}},"bottom":{"type":"none","width":"","color":{"r":231,"g":234,"b":241,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"60"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"300"}} -->
<div class="section-wrapper" data-id="ZnsnoD"><section class="wp-block-gutenverse-section guten-element guten-section guten-ZnsnoD animated guten-element-hide desktop-fadeIn layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-O7aEJb","border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"r":231,"g":234,"b":241,"a":1}}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-O7aEJb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="O7aEJb"><div class="guten-column-wrapper"><!-- wp:gutenverse/logo-slider {"elementId":"guten-E0xab7","logos":[{"title":"One","_key":"Fqa3E3","src":{"id":119,"image":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-1.webp"}},{"title":"Two","_key":"vVvV6o","src":{"id":120,"image":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-2.webp"}},{"title":"Three","_key":"AvU6pP","src":{"id":122,"image":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-4.webp"}},{"title":"Four","_key":"sUqaCL","src":{"id":121,"image":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-3.webp"}},{"title":"Five","src":{"id":123,"image":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-5.webp"},"_key":"6BqvCo"}],"imageFixHeight":true,"imageHeight":{"Desktop":"28"},"imageFit":{"Desktop":"contain"},"imagePadding":{"Desktop":{}},"imageMargin":{"Desktop":{}},"imageHoverPadding":{"Desktop":{}},"imageHoverMargin":{"Desktop":{}},"imageBorder":{"radius":{"Desktop":{}}},"imageBorderHover":{"radius":{"Desktop":{}}},"spacing":{"Desktop":"80","Tablet":"50","Mobile":"40"},"itemShowed":{"Desktop":"5","Tablet":"5","Mobile":"2"},"loop":true,"arrowPadding":{"Desktop":{}},"arrowMargin":{"Desktop":{}},"arrowBorder":{"radius":{"Desktop":{}}},"opacity":"0.8","hoverOpacity":"1"} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-E0xab7 arrow-bottom-edge"><div class="client-list"><div id="guten-E0xab7" class="swiper-container" data-loop="true" data-autoplay="false" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:40,&quot;slidesPerView&quot;:2},&quot;768&quot;:{&quot;spaceBetween&quot;:50,&quot;slidesPerView&quot;:5},&quot;1024&quot;:{&quot;spaceBetween&quot;:80,&quot;slidesPerView&quot;:5}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-1.webp" alt="One"/><img class="hover-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-1.webp" alt="One"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-2.webp" alt="Two"/><img class="hover-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-2.webp" alt="Two"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-4.webp" alt="Three"/><img class="hover-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-4.webp" alt="Three"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-3.webp" alt="Four"/><img class="hover-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-3.webp" alt="Four"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-5.webp" alt="Five"/><img class="hover-image" src="' . esc_url( ECHELON_FSE_URI ) . 'assets/img/client-logo-5.webp" alt="Five"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
