<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Article', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-5HKiHh","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"120"}},"Mobile":{"unit":"px","dimension":{"top":"70","bottom":"120"}}}} -->
<div class="section-wrapper" data-id="5HKiHh"><section class="wp-block-gutenverse-section guten-element guten-section guten-5HKiHh layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-wAhgrK"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wAhgrK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wAhgrK"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-8Ukkm5","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"subtitle-font"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-8Ukkm5">Latest News</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-g736Qj","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-g736Qj">Our News &amp; Article</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-kVx1EO","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="section-wrapper" data-id="kVx1EO"><section class="wp-block-gutenverse-section guten-element guten-section guten-kVx1EO animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":100,"Mobile":null},"elementId":"guten-cBMY8m","animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cBMY8m slow"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cBMY8m"><div class="guten-column-wrapper"><!-- wp:gutenverse/post-block {"elementId":"guten-hJ2gMC","numberPost":"2","column":{"Desktop":"2","Mobile":"1"},"categoryPosition":"left","excerptLength":"13","readmoreEnabled":false,"metaAuthorEnabled":false,"postblockType":"type-3","postItemGap":{"Desktop":"30","Tablet":"20"},"postItemMargin":{"Mobile":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":{},"Desktop":{}},"postItemPadding":{"Mobile":{},"Desktop":{},"Tablet":{}},"postItemBorder":{"radius":{"Mobile":{},"Desktop":{},"Tablet":{}}},"thumbnailWidth":{"Desktop":""},"thumbnailMargin":{"Desktop":{}},"thumbnailPadding":{"Desktop":{}},"thumbnailBorder":{"radius":{"Desktop":{}}},"thumbnailHeight":{"Desktop":"270"},"thumbnailRadius":{"Desktop":{}},"contentMargin":{"Desktop":{}},"contentPadding":{"Desktop":{}},"contentBorder":{"radius":{"Desktop":{}}},"categoryColor":{"type":"variable","id":"fourth"},"categoryTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"weight":"400","size":{"Desktop":{"point":"14","unit":"px"}}},"categoryBackground":{"type":"variable","id":"third"},"categoryMargin":{"Desktop":{}},"categoryPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"16","bottom":"12","left":"16"}}},"categoryBorder":{"radius":{"Desktop":{}}},"titleMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h5-font"},"excerptMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"excerptColor":{"type":"variable","id":"fifth"},"excerptTypography":{"type":"variable","id":"text-font"},"readmoreMargin":{"Desktop":{}},"readmorePadding":{"Desktop":{}},"readmoreBorder":{"radius":{"Desktop":{}}},"metaTypography":{"type":"variable","id":"text-13-font"},"metaColor":{"type":"variable","id":"ninth"},"metaMargin":{"Desktop":{},"Mobile":{}},"metaDateIconSpacing":{"Desktop":"8"},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<div class="guten-element guten-post-block guten-hJ2gMC"></div>
<!-- /wp:gutenverse/post-block --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":100,"Mobile":null},"elementId":"guten-l3FoNN","margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40","top":"-12","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":""}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-l3FoNN slow"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="l3FoNN"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-sL8mdq","type":3,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-font"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-sL8mdq">Recent News</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/divider {"elementId":"guten-ci7e8S","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"sixth"},"size":{"Desktop":"1.2"},"gap":{"Desktop":"1"}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-ci7e8S"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/post-list {"elementId":"guten-qCgBEX","numberPost":"3","postOffset":"0","metaEnabled":true,"metaDateEnabled":true,"metaPosition":"bottom","contentMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"contentWidth":{"Desktop":{"point":"","unit":"px"}},"contentBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{},"Tablet":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"title-18-font"},"metaTypography":{"type":"variable","id":"text-14-font"},"metaIconSize":{"Desktop":"14"},"metaIconSpacing":{"Desktop":"6"},"metaMargin":{"Desktop":{"unit":"px","dimension":{"top":"6","bottom":""}},"Tablet":{}},"metaPadding":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{}},"metaColor":{"type":"variable","id":"ninth"},"metaBorder":{"radius":{"Desktop":{}}},"paginationTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"}},"weight":"400"},"paginationMargin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"paginationPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","bottom":"16","right":"30","left":"30"}}},"paginationWidth":{"Desktop":"100"},"paginationColor":{"r":255,"g":255,"b":255,"a":1},"paginationBackground":{"type":"default","color":{"r":17,"g":86,"b":155,"a":1}},"paginationBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"paginationShadow":{"color":{"r":0,"g":0,"b":0,"a":0}},"paginationHoverShadow":{"color":{"r":0,"g":0,"b":0,"a":0},"horizontal":"0","vertical":"0","blur":"0","spread":"0"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}}}} -->
<div class="guten-element guten-post-list guten-qCgBEX"></div>
<!-- /wp:gutenverse/post-list -->

<!-- wp:gutenverse/button {"elementId":"guten-BvNcRR","content":"View All","buttonWidth":{"Desktop":"100"},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"30","bottom":"18","left":"30"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"eighth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none","width":"","color":{"r":17,"g":86,"b":155,"a":1}}},"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"border":{"radius":{"Desktop":{}}},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"color":{"type":"variable","id":"fourth"},"iconColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"fourth"},"hoverTextColor":{"type":"variable","id":"fourth"}} -->
<div class="guten-element guten-button-wrapper guten-BvNcRR"><a class="guten-button slow guten-button-sm" href="#"><span>View All</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
