<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse Home Service', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-rPqs2y","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"120","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"40","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"70","left":""}}}} -->
<div class="section-wrapper" data-id="rPqs2y"><section class="wp-block-gutenverse-section guten-element guten-section guten-rPqs2y layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-OrmICS"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OrmICS"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OrmICS"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-E1BW41","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"subtitle-font"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-E1BW41">Our Services</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-pBivh2","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-pBivh2">Our Best Services</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-S1CAGO","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-font"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"35","left":"35"}},"Tablet":{"unit":"%","dimension":{"right":"22","left":"22","top":"","bottom":""}},"Mobile":{"unit":"%","dimension":{"right":"5","left":"5"}}}} -->
<div class="guten-element gutenverse-text-editor guten-S1CAGO"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa ligula eget.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-8mTZDG","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
<div class="section-wrapper" data-id="8mTZDG"><section class="wp-block-gutenverse-section guten-element guten-section guten-8mTZDG layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-DjlxFL","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","top":"10","bottom":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DjlxFL animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DjlxFL"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-WGDRSL","title":"Business Planning","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.","watermarkShow":true,"watermarkIcon":"gtn gtn-presentation-light","icon":"gtn gtn-presentation-light","iconSize":{"Desktop":"48","Tablet":"40"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"50","bottom":"20","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"40","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","left":"40","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"containerBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","color":{"type":"variable","id":"sixth"},"width":"1"}},"containerBorderHover":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"fourth"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"fourth"},"titleTypography":{"type":"variable","id":"h6-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font"},"watermarkColor":{"type":"variable","id":"tenth"},"watermarkSize":{"Desktop":"110","Tablet":"85"},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"300"}} -->
<div class="guten-element guten-WGDRSL guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-presentation-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Business Planning</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.</p><!-- wp:gutenverse/button {"elementId":"guten-DbnHOc","content":"Learn More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"white"},"hoverTextColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-button-wrapper guten-DbnHOc"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span><i class="fa-lg gtn gtn-right-arrow1-light"></i></a></div>
<!-- /wp:gutenverse/button --></div><div class="hover-watermark"><i class="gtn gtn-presentation-light"></i></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-A6ELzg","margin":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"5","left":"5"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"10","bottom":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-A6ELzg animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="A6ELzg"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-rJGBmS","title":"Marketing Strategy","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.","watermarkShow":true,"watermarkIcon":"gtn gtn-team-1-light","icon":"gtn gtn-team-1-light","iconSize":{"Desktop":"48","Tablet":"40"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"50","bottom":"20","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"40","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"containerBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","color":{"type":"variable","id":"sixth"},"width":"1"}},"containerBorderHover":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"fourth"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"fourth"},"titleTypography":{"type":"variable","id":"h6-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font"},"watermarkColor":{"type":"variable","id":"tenth"},"watermarkSize":{"Desktop":"110","Tablet":"85"},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"500"}} -->
<div class="guten-element guten-rJGBmS guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-team-1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Marketing Strategy</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.</p><!-- wp:gutenverse/button {"elementId":"guten-lA4PZO","content":"Learn More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"fourth"},"hoverTextColor":{"type":"variable","id":"fourth"}} -->
<div class="guten-element guten-button-wrapper guten-lA4PZO"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span><i class="fa-lg gtn gtn-right-arrow1-light"></i></a></div>
<!-- /wp:gutenverse/button --></div><div class="hover-watermark"><i class="gtn gtn-team-1-light"></i></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-BrgUex","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"left":"10","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"10","bottom":"10","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-BrgUex animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BrgUex"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-OvTDnS","title":"Data Analysis","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.","watermarkShow":true,"watermarkIcon":"gtn gtn-chart2-light","icon":"gtn gtn-chart2-light","iconSize":{"Desktop":"48","Tablet":"40"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"50","bottom":"20","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"34","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"40","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"44","left":"40"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"containerBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","color":{"type":"variable","id":"sixth"},"width":"1"}},"containerBorderHover":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{},"Mobile":{}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"fourth"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"fourth"},"titleTypography":{"type":"variable","id":"h6-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font"},"watermarkColor":{"type":"variable","id":"tenth"},"watermarkSize":{"Desktop":"110","Tablet":"85"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}},"border":{"radius":{"Desktop":{}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"700"}} -->
<div class="guten-element guten-OvTDnS guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-chart2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Data Analysis</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.</p><!-- wp:gutenverse/button {"elementId":"guten-itQaqu","content":"Learn More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"fourth"},"hoverTextColor":{"type":"variable","id":"fourth"}} -->
<div class="guten-element guten-button-wrapper guten-itQaqu"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span><i class="fa-lg gtn gtn-right-arrow1-light"></i></a></div>
<!-- /wp:gutenverse/button --></div><div class="hover-watermark"><i class="gtn gtn-chart2-light"></i></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-Dy9TXv","margin":{"Desktop":{"unit":"px","dimension":{"top":"-45"}},"Tablet":{"unit":"px","dimension":{"top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"0","bottom":"0"}}}} -->
<div class="section-wrapper" data-id="Dy9TXv"><section class="wp-block-gutenverse-section guten-element guten-section guten-Dy9TXv layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-ljedpr","order":{"Mobile":1},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ljedpr animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ljedpr"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-21szTL","title":"Social Branding","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.","watermarkShow":true,"watermarkIcon":"gtn gtn-communication-light","icon":"gtn gtn-communication-light","iconSize":{"Desktop":"48","Tablet":"40"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"50","bottom":"20","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"40","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"containerBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","color":{"type":"variable","id":"sixth"},"width":"1"}},"containerBorderHover":{"radius":{"Desktop":{},"Tablet":{}},"all":{"width":"1","type":"solid","color":{"type":"variable","id":"third"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"r":255,"g":255,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"fourth"},"titleTypography":{"type":"variable","id":"h6-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font"},"watermarkColor":{"type":"variable","id":"tenth"},"watermarkSize":{"Desktop":"110","Tablet":"85"}} -->
<div class="guten-element guten-21szTL guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-communication-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Social Branding</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.</p><!-- wp:gutenverse/button {"elementId":"guten-vbA8mu","content":"Learn More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"fourth"},"hoverTextColor":{"type":"variable","id":"fourth"}} -->
<div class="guten-element guten-button-wrapper guten-vbA8mu"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span><i class="fa-lg gtn gtn-right-arrow1-light"></i></a></div>
<!-- /wp:gutenverse/button --></div><div class="hover-watermark"><i class="gtn gtn-communication-light"></i></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-k3oAKp","order":{"Mobile":3},"background":{"type":"default","image":{"Desktop":{"id":1229,"image":"' . esc_url( ECHELON_FSE_URI ) . 'assets/img/StockSnap_RRJH1KMRMW.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1}},"opacity":"0.7","verticalAlign":{"Desktop":"default","Tablet":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"5","left":"5","bottom":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"10","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"70","left":"70","top":"70","bottom":"70"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"40","bottom":"80","left":"40"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-k3oAKp animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="k3oAKp"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-ORjwe0","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-hero-font"},"margin":{"Tablet":{}},"padding":{"Tablet":{}}} -->
<div class="guten-element gutenverse-text-editor guten-ORjwe0"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Get To Know Our Another Best Services to Help Your Problems.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-PWpOVQ","content":"View More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"30","bottom":"18","left":"30"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"fourth"}}},"buttonBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}},"Tablet":{}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"fourth"},"iconColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"fourth"},"hoverTextColor":{"type":"variable","id":"fourth"}} -->
<div class="guten-element guten-button-wrapper guten-PWpOVQ"><a class="guten-button guten-button-sm" href="#"><span>View More</span><i class="fa-lg gtn gtn-right-arrow1-light"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-RLuFOn","order":{"Mobile":2},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"10","bottom":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RLuFOn animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RLuFOn"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Igg0jo","title":"Risk Management","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.","watermarkShow":true,"watermarkIcon":"gtn gtn-safebox1-light","icon":"gtn gtn-safebox1-light","iconSize":{"Desktop":"48","Tablet":"40"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"50","bottom":"20","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"30","left":"40"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"40","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"containerBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","color":{"type":"variable","id":"sixth"},"width":"1"}},"containerBorderHover":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"fourth"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"fourth"},"titleTypography":{"type":"variable","id":"h6-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fifth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font"},"watermarkColor":{"type":"variable","id":"tenth"},"watermarkSize":{"Desktop":"110","Tablet":"85"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}},"margin":{"Tablet":{}},"padding":{"Tablet":{}}} -->
<div class="guten-element guten-Igg0jo guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-safebox1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Risk Management</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit.</p><!-- wp:gutenverse/button {"elementId":"guten-pXLClR","content":"Learn More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"fourth"},"hoverTextColor":{"type":"variable","id":"fourth"}} -->
<div class="guten-element guten-button-wrapper guten-pXLClR"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span><i class="fa-lg gtn gtn-right-arrow1-light"></i></a></div>
<!-- /wp:gutenverse/button --></div><div class="hover-watermark"><i class="gtn gtn-safebox1-light"></i></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
