<?php
/**
 * Gutenverse Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Section 2', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":""},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"10","right":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="5e9nnt"><section class="wp-block-gutenverse-section guten-element guten-section guten-5e9nnt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-LLkRjW","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LLkRjW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LLkRjW"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-zzXU48","imgSrc":{"media":{"imageId":410,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( FINANCIO_URI ) . 'assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com-150x150.jpeg","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( FINANCIO_URI ) . 'assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com-300x200.jpeg","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( FINANCIO_URI ) . 'assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com-1024x683.jpeg","orientation":"landscape"},"full":{"url":"' . esc_url( FINANCIO_URI ) . 'assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com.jpg","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"},"Tablet":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":"100"}},"height":{"Desktop":{"point":"465","unit":"px"},"Mobile":{"point":"250","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-zzXU48 animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( FINANCIO_URI ) . 'assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com.jpg" height="1280" width="1920"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-hm22ZI","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"","top":"20","right":"","bottom":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hm22ZI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hm22ZI"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-7otlnJ","type":5,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-7otlnJ animated guten-element-hide desktop-fadeInRight">About Us</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-2W1hqH","color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-2W1hqH animated guten-element-hide desktop-fadeInRight">The Easiest Way to Manage Your Personal Finances</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-wb6sWe","textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-wb6sWe animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-izGD1I","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="izGD1I"><section class="wp-block-gutenverse-section guten-element guten-section guten-izGD1I layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-cae7WS","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cae7WS"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cae7WS"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Yozt5j","title":"Our Vision","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor","icon":"gtn gtn-eye2-light","iconPosition":"top","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":{}},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconColor":{"type":"variable","id":"primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":{},"Mobile":[]},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"third"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-Yozt5j animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-eye2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Our Vision</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-vxeXGf","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vxeXGf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vxeXGf"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-oP42hc","title":"Our Mission","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor","icon":"gtn gtn-target-light","iconPosition":"top","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconColor":{"type":"variable","id":"primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":{},"Mobile":[]},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"third"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
<div class="guten-element guten-oP42hc animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-target-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Our Mission</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
