<?php
/**
 * Gutenverse Service Content content.
 */
return array(
	'title'      => __( 'Gutenverse Service Content', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-ss336B","background":{"type":"default","color":"","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":""},"opacity":"0.8","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"","left":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="ss336B"><section class="wp-block-gutenverse-section guten-element guten-section guten-ss336B layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-cUroGs","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cUroGs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cUroGs"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-yrZhvt","type":5,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-yrZhvt animated guten-element-hide desktop-fadeInUp">Our Service</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-4cFXy5","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-4cFXy5 animated guten-element-hide desktop-fadeInUp">What Service We Offer</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-EMr7h3","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"26","left":"26"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"12","bottom":"0","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-EMr7h3 animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-181rlr","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="181rlr"><section class="wp-block-gutenverse-section guten-element guten-section guten-181rlr slow layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-rqDiaH","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rqDiaH"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rqDiaH"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-fFIFjz","title":"Investment Planning","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-invest-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":{}},"containerBackground":{"type":"default","color":{"type":"variable","id":"fifth"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"fifth"},"iconBgColor":{"type":"variable","id":"primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"third"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="guten-element guten-fFIFjz animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-invest-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Investment Planning</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-Mb9cVB","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"primary"},"iconColor":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} -->
<div class="guten-element guten-button-wrapper guten-Mb9cVB"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-W6ufL4","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-W6ufL4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="W6ufL4"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-cf0fQf","title":"Audit & Assurance","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-consut2-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"fifth"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"fifth"},"iconBgColor":{"type":"variable","id":"primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"third"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-cf0fQf animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-consut2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Audit &amp; Assurance</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-H4qmm7","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"primary"},"iconColor":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} -->
<div class="guten-element guten-button-wrapper guten-H4qmm7"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-szOJxc","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-szOJxc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="szOJxc"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-FngvNN","title":"Business Taxation","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-business-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":{}},"containerBackground":{"type":"default","color":{"type":"variable","id":"fifth"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"fifth"},"iconBgColor":{"type":"variable","id":"primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"third"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-FngvNN animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-business-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Business Taxation</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-7jcUrA","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"primary"},"iconColor":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} -->
<div class="guten-element guten-button-wrapper guten-7jcUrA"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-fzpr2K","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="fzpr2K"><section class="wp-block-gutenverse-section guten-element guten-section guten-fzpr2K slow layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-K1JYII","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-K1JYII"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="K1JYII"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-aE305Z","title":"Accounts Outsourcing","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-coins-1-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"fifth"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"fifth"},"iconBgColor":{"type":"variable","id":"primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"third"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-aE305Z animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-coins-1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Accounts Outsourcing</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-X57jFX","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"16","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"primary"},"iconColor":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} -->
<div class="guten-element guten-button-wrapper guten-X57jFX"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-PRO4Qn","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PRO4Qn"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PRO4Qn"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-pVAlLw","title":"Payroll & Salary","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-commerce-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":{}},"containerBackground":{"type":"default","color":{"type":"variable","id":"primary"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"primary"},"iconBgColor":{"type":"variable","id":"fifth"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"fifth"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<div class="guten-element guten-pVAlLw animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-commerce-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Payroll &amp; Salary</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-83grBP","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"fifth"},"iconColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} -->
<div class="guten-element guten-button-wrapper guten-83grBP"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-taz7eY","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-taz7eY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="taz7eY"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-5llfao","title":"Loan Management","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-loan-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"fifth"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"fifth"},"iconBgColor":{"type":"variable","id":"primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"third"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
<div class="guten-element guten-5llfao animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-loan-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Loan Management</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-TK519F","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"primary"},"iconColor":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} -->
<div class="guten-element guten-button-wrapper guten-TK519F"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
