<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":335,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wood-food-basket-baking-towel-flowers-1060664-pxhere.com.webp"}},"position":{"Desktop":"top left","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"waterlava-tenth"},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.8","border":{"radius":{"Tablet":[],"Desktop":[]}},"topDivider":{},"bottomDivider":{"type":"waves","width":{"Desktop":"144","Tablet":"174"},"flip":false,"height":{"Desktop":"90","Tablet":"100"},"colorMode":"default","color":{"r":255,"g":252,"b":249,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0","left":"0","right":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"200"}},"Tablet":{"unit":"px","dimension":{"top":"150","bottom":"200","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"150","bottom":"200"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="4qr4Df"><section class="wp-block-gutenverse-section guten-element guten-section guten-4qr4Df layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3vgI6y","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3vgI6y"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3vgI6y"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"h1-alt-font","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"200"},"Tablet":{"unit":"px","point":"190"},"Mobile":{"unit":"px","point":"120"}},"lineHeight":{"Desktop":{"unit":"px","point":"200"},"Tablet":{"unit":"px","point":"190"},"Mobile":{"unit":"px","point":"120"}},"style":"italic","weight":"400"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"slow","delay":"1"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-q3mXI6 animated guten-element-hide slow desktop-fadeInUp tablet-fadeInDown mobile-fadeInDown">404</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-acrOQB","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"h1-font","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"style":"italic","weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-40"}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"slow","delay":"1"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-acrOQB animated guten-element-hide slow desktop-fadeInUp tablet-fadeInDown mobile-fadeInDown">Something Went Wrong</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-kxbE7L","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"text-editor-2-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"px","point":"28.8"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":""}},"Mobile":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"0","bottom":"0","left":"120"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInUp","Mobile":"slideInUp"},"duration":"slow","delay":"2"}} -->
<div class="guten-element gutenverse-text-editor guten-kxbE7L animated guten-element-hide slow desktop-fadeInDown tablet-fadeInUp mobile-slideInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Quisque consectetur convallis exquis tincidunt ligula placeratet. Nam quis leo sed tortor blandit commodo. Quisque ultrices justo non convallis accumsan ante magna ornare sapien quis venenatis diam libero necorci.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"elementId":"guten-DPwJel","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="DPwJel"><section class="wp-block-gutenverse-section guten-element guten-section guten-DPwJel layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-HIN6fa","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HIN6fa"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HIN6fa"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-i0nEgV","content":"Back To Home","alignButton":{"Desktop":"center","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"waterlava-fifth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"white"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","color":{"r":191,"g":164,"b":152,"a":1},"width":"1"}},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow","delay":"3"},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"button-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"hoverTextColor":{"type":"variable","id":"waterlava-third"}} -->
<div class="guten-element guten-button-wrapper guten-i0nEgV"><a class="guten-button animated guten-element-hide slow desktop-fadeInLeft guten-button-sm" href="#"><span>Back To Home</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
