<?php
/**
 * Gutenverse About Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 1', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-TlTjon","background":{"type":"default","color":{"type":"variable","id":"waterlava-third"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="TlTjon"><section class="wp-block-gutenverse-section guten-element guten-section guten-TlTjon layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-vV4rJH","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{},"Mobile":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vV4rJH"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vV4rJH"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-aM1B5R","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"5","left":"5","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"0","right":"10","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="aM1B5R"><section class="wp-block-gutenverse-section guten-element guten-section guten-aM1B5R layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-DYjRwA","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DYjRwA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DYjRwA"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-zQgZ3t","verticalAlign":"center","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="zQgZ3t"><section class="wp-block-gutenverse-section guten-element guten-section guten-zQgZ3t layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-9aGyS1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9aGyS1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9aGyS1"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Pp6VLb","imgSrc":{"media":{"imageId":53,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-1024x1024.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp","height":1920,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"102","unit":"px"},"Tablet":{"point":"146","unit":"px"},"Mobile":{"point":"58","unit":"px"}},"height":{"Desktop":{"point":"102","unit":"px"},"Tablet":{"point":"145","unit":"px"},"Mobile":{"point":"57","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-Pp6VLb animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp" height="1920" width="1920"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/heading {"elementId":"guten-nuAQtp","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-nuAQtp animated guten-element-hide desktop-fadeInLeft">An Incredible Spa Experience</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-rbVW8W","dropcapMargin":{},"dropcapPadding":{},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"right":"5","left":"5"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-rbVW8W animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisl. </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/image {"elementId":"guten-uX2DHt","imgSrc":{"media":{"imageId":88,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-150x150.webp","orientation":"landscape"},"medium":{"height":71,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-300x71.webp","orientation":"landscape"},"large":{"height":244,"width":1024,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-1024x244.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan.webp","height":457,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"205","unit":"px"},"Tablet":{"point":"218","unit":"px"},"Mobile":{"point":"145","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"43","unit":"px"},"Mobile":{"point":"29","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"zIndex":{"Desktop":"10"}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-uX2DHt animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan.webp" height="457" width="1920"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/heading {"elementId":"guten-REHQzp","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-REHQzp animated guten-element-hide desktop-fadeInLeft">WaterLava Owner</h5>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-chAEvr","order":{"Tablet":2},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-chAEvr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="chAEvr"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Tm5j7e","imgSrc":{"media":{"imageId":262,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":184,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com-184x300.webp","orientation":"portrait"},"large":{"height":1024,"width":627,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com-627x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com.webp","height":2450,"width":1500,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"410","unit":"px"},"Mobile":{"point":"251","unit":"px"}},"height":{"Mobile":{"point":"361","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"200"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"-10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-Tm5j7e animated guten-element-hide desktop-fadeIn"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com.webp" height="2450" width="1500"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-OhTrmI","order":{"Tablet":1},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"5","left":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"20"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OhTrmI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OhTrmI"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-JzHGMF","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"margin":{"Mobile":{}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-JzHGMF animated guten-element-hide desktop-fadeInRight">1998</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Qhqu3X","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"}} -->
<div class="guten-element gutenverse-text-editor guten-Qhqu3X animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna.&nbsp;</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/heading {"elementId":"guten-GbdA2Z","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}},"padding":{"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-GbdA2Z animated guten-element-hide desktop-fadeInRight">Awards</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"elementId":"guten-cBA1Ok","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="cBA1Ok"><section class="wp-block-gutenverse-section guten-element guten-section guten-cBA1Ok layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-i2siCg","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-i2siCg animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="i2siCg"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-4988X8","iconColor":{"type":"variable","id":"waterlava-primary"},"iconColorHover":{"type":"variable","id":"waterlava-primary"},"textColor":{"type":"variable","id":"waterlava-primary"},"textColorHover":{"type":"variable","id":"waterlava-primary"},"textIndent":{"Desktop":"5"},"textTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"}} -->
<div class="guten-element guten-icon-list guten-4988X8"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-8cgn72"} -->
<div class="guten-element guten-icon-list-item guten-8cgn72"><a id="guten-8cgn72"><i class="fas fa-medal"></i><span class="list-text ">The Edge Bali</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-IHArFy"} -->
<div class="guten-element guten-icon-list-item guten-IHArFy"><a id="guten-IHArFy"><i class="fas fa-medal"></i><span class="list-text ">The Ritz Calton</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vtVNmZ"} -->
<div class="guten-element guten-icon-list-item guten-vtVNmZ"><a id="guten-vtVNmZ"><i class="fas fa-medal"></i><span class="list-text ">Laggona Cliff</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-KhxKQN","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KhxKQN animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KhxKQN"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-BydsM9","iconColor":{"type":"variable","id":"waterlava-primary"},"iconColorHover":{"type":"variable","id":"waterlava-primary"},"textColor":{"type":"variable","id":"waterlava-primary"},"textColorHover":{"type":"variable","id":"waterlava-primary"},"textIndent":{"Desktop":"5"},"textTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"}} -->
<div class="guten-element guten-icon-list guten-BydsM9"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-gAgIm0"} -->
<div class="guten-element guten-icon-list-item guten-gAgIm0"><a id="guten-gAgIm0"><i class="fas fa-medal"></i><span class="list-text ">Global Spa Awards</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ZZX0hy"} -->
<div class="guten-element guten-icon-list-item guten-ZZX0hy"><a id="guten-ZZX0hy"><i class="fas fa-medal"></i><span class="list-text ">Best Resort Spa</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-y3zHQs"} -->
<div class="guten-element guten-icon-list-item guten-y3zHQs"><a id="guten-y3zHQs"><i class="fas fa-medal"></i><span class="list-text ">Dive\'s Awards</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-rokpoV","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-rokpoV animated guten-element-hide desktop-fadeInRight">Our Specialist</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-UREabw","title":"Face Tratements","percentage":"90","barColor":{"type":"variable","id":"waterlava-seventh"},"trackColor":{"type":"variable","id":"waterlava-fifth"},"trackHeight":{"Desktop":"3"},"barRadius":{"Desktop":{},"Tablet":{}},"trackRadius":{"Desktop":{},"Tablet":{}},"barPadding":{"Desktop":{},"Tablet":{}},"barMargin":{"Desktop":{},"Tablet":{}},"titleColor":{"type":"variable","id":"waterlava-primary"},"titleTypography":{"type":"variable","id":"progres-bar-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"px","point":"27"},"Tablet":{"unit":"px","point":"25.5"}},"weight":"600"},"percentColor":{"type":"variable","id":"waterlava-primary"},"percentTypography":{"type":"variable","id":"progres-bar-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"px","point":"27"},"Tablet":{"unit":"px","point":"25.5"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-progress-bar guten-UREabw animated guten-element-hide desktop-fadeInRight"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Face Tratements</span></div><div class="skill-bar"><div class="skill-track" data-width="90" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
<!-- /wp:gutenverse/progress-bar -->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-yGblgz","title":"Scalp Massage","percentage":"97","barColor":{"type":"variable","id":"waterlava-seventh"},"trackColor":{"type":"variable","id":"waterlava-fifth"},"trackHeight":{"Desktop":"3"},"barRadius":{"Desktop":{}},"trackRadius":{"Desktop":{}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"type":"variable","id":"waterlava-primary"},"titleTypography":{"type":"variable","id":"progres-bar-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"px","point":"27"},"Tablet":{"unit":"px","point":"25.5"}},"weight":"600"},"percentColor":{"type":"variable","id":"waterlava-primary"},"percentTypography":{"type":"variable","id":"progres-bar-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"px","point":"27"},"Tablet":{"unit":"px","point":"25.5"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"}} -->
<div class="guten-element guten-progress-bar guten-yGblgz animated guten-element-hide desktop-fadeInRight"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Scalp Massage</span></div><div class="skill-bar"><div class="skill-track" data-width="97" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
<!-- /wp:gutenverse/progress-bar -->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-Y7DS2X","title":"Natural Mask","percentage":"93","barColor":{"type":"variable","id":"waterlava-seventh"},"trackColor":{"type":"variable","id":"waterlava-fifth"},"trackHeight":{"Desktop":"3"},"barRadius":{"Desktop":{}},"trackRadius":{"Desktop":{}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"type":"variable","id":"waterlava-primary"},"titleTypography":{"type":"variable","id":"progres-bar-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"px","point":"27"},"Tablet":{"unit":"px","point":"25.5"}},"weight":"600"},"percentColor":{"type":"variable","id":"waterlava-primary"},"percentTypography":{"type":"variable","id":"progres-bar-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"px","point":"27"},"Tablet":{"unit":"px","point":"25.5"}},"weight":"600"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"0","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
<div class="guten-element guten-progress-bar guten-Y7DS2X animated guten-element-hide desktop-fadeInRight"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Natural Mask</span></div><div class="skill-bar"><div class="skill-track" data-width="93" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
<!-- /wp:gutenverse/progress-bar --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
