<?php
/**
 * Gutenverse About Section 5 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 5', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"800"},"height":{},"gap":"no","elementId":"guten-Z4hdiW","background":{"type":"default","image":{"Desktop":{"id":241,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/flower-food-relax-produce-rest-baking-914313-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"waterlava-tenth"}},"opacity":"0.6","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"10","bottom":"50","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="Z4hdiW"><section class="wp-block-gutenverse-section guten-element guten-section guten-Z4hdiW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-pbHrFd","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pbHrFd"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pbHrFd"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-lLDvOq","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-lLDvOq animated guten-element-hide desktop-fadeInUp">Make An Appointment</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-YqKXfV","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
<div class="guten-element gutenverse-text-editor guten-YqKXfV animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-P3krAo","formId":{"label":"Form Appointment","value":620},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<form style="display:none" class="guten-element guten-form-builder guten-P3krAo animated guten-element-hide desktop-fadeInUp" data-form-id="620"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-xZp187","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="xZp187"><section class="wp-block-gutenverse-section guten-element guten-section guten-xZp187 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ecq9A4","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ecq9A4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ecq9A4"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-Hjq79h","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":{},"Tablet":{}},"labelMargin":{"Desktop":{},"Tablet":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-third"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"10","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderNormal":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderFocus":{"radius":{"Desktop":{}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-Hjq79h hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-rS6Dmp","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rS6Dmp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rS6Dmp"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-email {"elementId":"guten-eZzz7G","showLabel":false,"showHelper":false,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":{}},"all":{"type":"solid","color":{"type":"variable","id":"waterlava-third"},"width":"1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","left":"10","bottom":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPlaceholder":"email@domain.com","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderNormal":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderFocus":{"radius":{"Desktop":{}}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-eZzz7G hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="email@domain.com" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-cwxo68","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="cwxo68"><section class="wp-block-gutenverse-section guten-element guten-section guten-cwxo68 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-LHiHW7","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LHiHW7"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LHiHW7"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-telp {"elementId":"guten-nC62pg","showLabel":false,"showHelper":false,"labelPadding":{"Mobile":{},"Desktop":{}},"labelMargin":{"Mobile":{},"Desktop":{}},"helperPadding":{"Mobile":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-third"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","left":"0","bottom":"20"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPlaceholder":"Your Phone","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderNormal":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderFocus":{"radius":{"Desktop":{}}}} -->
<div class="guten-element guten-form-input-telp guten-form-input guten-input-position-top guten-nC62pg hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;telp&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Phone" name="input-telp" class="gutenverse-input gutenverse-input-tel" type="tel" pattern="[0-9]{3}-[0-9]{2}-[0-9]{3}"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-telp --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-lLkV3r","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lLkV3r"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lLkV3r"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-date {"elementId":"guten-7jasqi","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":{}},"all":{"type":"solid","color":{"type":"variable","id":"waterlava-third"},"width":"1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","left":"10","bottom":"20"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPlaceholder":"dd/mm/yyyy","dateFormat":"d/m/Y","dateStart":"1969-12-31T16:00:00.000Z","dateEnd":"2022-05-30T16:00:00.000Z","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderNormal":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderFocus":{"radius":{"Desktop":{}}}} -->
<div class="guten-element guten-form-input-date guten-form-input guten-input-position-top guten-7jasqi hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;date&quot;}" data-date="{&quot;dateFormat&quot;:&quot;d/m/Y&quot;,&quot;minDate&quot;:&quot;1969-12-31T16:00:00.000Z&quot;,&quot;maxDate&quot;:&quot;2022-05-30T16:00:00.000Z&quot;}" placeholder="dd/mm/yyyy" name="input-date" class="gutenverse-input gutenverse-input-date" type="text"/><div class="validation-error"></div></div></div>
<!-- /wp:gutenverse/form-input-date --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-nFPDhd","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="nFPDhd"><section class="wp-block-gutenverse-section guten-element guten-section guten-nFPDhd layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-dgUvr1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-dgUvr1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dgUvr1"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-select {"elementId":"guten-UOlY3D","showLabel":false,"inputPlaceholder":"Select Therapist","showHelper":false,"labelColor":{"Desktop":{}},"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":{}},"all":{"type":"solid","color":{"type":"variable","id":"waterlava-third"},"width":"1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","left":"","bottom":"20"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"selectOptions":[{"value":"option-1","label":"Dianne Russel","_key":"roMGRY","selected":true},{"value":"option-2","label":"Eleanor Pena","_key":"nHNlWO","selected":true},{"value":"option-3","label":"Jenny Wilson","_key":"TPyMBi","selected":true},{"label":"Kathryn Murphy","selected":true,"_key":"TqfqLC"},{"label":"Darrel Esther","selected":true,"_key":"YvgwJg"}],"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderNormal":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderHover":{"radius":{"Desktop":{}}},"choicesBgColorHover":{"Desktop":{"type":"variable","id":"waterlava-fifth"}}} -->
<div class="guten-element guten-form-input-select guten-form-input guten-input-position-top guten-UOlY3D hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><select name="input-select" data-validation="{&quot;type&quot;:&quot;select&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" class="gutenverse-input gutenverse-input-select"><option value="">Select Therapist</option><option value="option-1" selected>Dianne Russel</option><option value="option-2" selected>Eleanor Pena</option><option value="option-3" selected>Jenny Wilson</option><option selected>Kathryn Murphy</option><option selected>Darrel Esther</option></select><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-select --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-MxvopV","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MxvopV"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MxvopV"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-select {"elementId":"guten-u4iq3a","showLabel":false,"inputPlaceholder":"Select Services","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":{}},"all":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":1},"width":"1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","left":"10","bottom":"20"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputName":"Input-services","selectOptions":[{"value":"option-1","label":"Rescuse Treatment","_key":"NnJutu","selected":false},{"value":"option-2","label":"Scalp Massage","_key":"GT15cN","selected":false},{"value":"option-3","label":"Pranama Stone","_key":"p3HOfS","selected":false},{"_key":"tDlmzd","label":"Natural Mask","selected":false},{"_key":"D1lLOX","label":"Body Scrub","selected":false}],"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"white"}},"inputBorderNormal":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderHover":{"radius":{"Desktop":{}}},"choicesBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"choicesBgColorHover":{"Desktop":{"type":"variable","id":"waterlava-fifth"}}} -->
<div class="guten-element guten-form-input-select guten-form-input guten-input-position-top guten-u4iq3a hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><select name="Input-services" data-validation="{&quot;type&quot;:&quot;select&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" class="gutenverse-input gutenverse-input-select"><option value="">Select Services</option><option value="option-1">Rescuse Treatment</option><option value="option-2">Scalp Massage</option><option value="option-3">Pranama Stone</option><option>Natural Mask</option><option>Body Scrub</option></select><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-select --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-A7xSJM","showLabel":false,"showHelper":false,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":{}},"all":{"type":"solid","color":{"type":"variable","id":"waterlava-third"},"width":"1"}},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","left":"0","bottom":"20"}},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputHeight":{"Desktop":"150"},"inputPlaceholder":"Note For Us","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"white"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderNormal":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-third"}},"inputBorderFocus":{"radius":{"Desktop":{}}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-A7xSJM hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Note For Us" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-qFQKKB","content":"Book Now","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"waterlava-fifth"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"waterlava-twelfth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":{}}},"border":{"radius":{"Desktop":{}}},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"button-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"30"}},"Mobile":{}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-qFQKKB"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Book Now</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
