<?php
/**
 * Gutenverse Pricing Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Pricing Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-6jNzgz","background":{"type":"default","image":{"Desktop":{"id":140,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wood-food-basket-baking-towel-flowers-1060664-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"waterlava-tenth"}},"opacity":"0.7","topDivider":{},"bottomDivider":{"type":"waves","width":{"Desktop":"144"},"height":{"Desktop":"72"},"colorMode":"default","color":{"r":255,"g":252,"b":249,"a":1}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"150"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"100"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="6jNzgz"><section class="wp-block-gutenverse-section guten-element guten-section guten-6jNzgz layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-m9ofKj","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-m9ofKj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="m9ofKj"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-syP3FM","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"h1-font","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"style":"italic","weight":"400"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-syP3FM animated guten-element-hide desktop-fadeInDown">Pricing</h1>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
