<?php
/**
 * Gutenverse Blog Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Blog Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":372,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_5A5JLDXM4R.webp"}},"position":{"Desktop":"bottom center","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"waterlava-tenth"},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.7","topDivider":{},"bottomDivider":{"type":"waves","width":{"Desktop":"144"},"flip":false,"height":{"Desktop":"69"},"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"150"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"100"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="4qr4Df"><section class="wp-block-gutenverse-section guten-element guten-section guten-4qr4Df layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3vgI6y","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3vgI6y"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3vgI6y"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"h1-font","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"style":"italic","weight":"400"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-q3mXI6 animated guten-element-hide desktop-fadeInDown">Blog</h1>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
