<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse Page Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-asiuhB","background":{"type":"default","image":{"Desktop":{"id":335,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wood-food-basket-baking-towel-flowers-1060664-pxhere.com.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"waterlava-tenth"}},"opacity":"0.6","topDivider":{},"bottomDivider":{"type":"waves","width":{"Desktop":"144"},"height":{"Desktop":"88","Mobile":"60"},"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"180","bottom":"180"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"100"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="asiuhB"><section class="wp-block-gutenverse-section guten-element guten-section guten-asiuhB layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-z0Zwp6","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-z0Zwp6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="z0Zwp6"><div class="guten-column-wrapper"><!-- wp:post-title {"style":{"typography":{"fontSize":"48px"}},"textColor":"waterlava-third","fontFamily":"primary"} /--></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
