<?php
/**
 * Gutenverse About Section 6 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 6', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-AIDIXQ","verticalAlign":"center","background":{"type":"default","color":{"type":"variable","id":"waterlava-third"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"60","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"","bottom":"50","left":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="AIDIXQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-AIDIXQ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-LL7BZM","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LL7BZM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LL7BZM"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-9ocsth","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="9ocsth"><section class="wp-block-gutenverse-section guten-element guten-section guten-9ocsth layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-S5toc0","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-S5toc0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="S5toc0"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-OmJzPn","color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":[]},"padding":{"Mobile":[],"Desktop":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-OmJzPn animated guten-element-hide desktop-fadeInLeft">Client Inquiries</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-jGlkzZ","color":{"type":"variable","id":"waterlava-sixth"},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"70","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"70","unit":"px"}},"spacing":{"Desktop":"0.3"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"16"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Desktop":"0"},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"0","unit":"px"}},"positioningRight":{"Tablet":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"point":"-59","unit":"px"},"Tablet":{"unit":"%","point":"-46"},"Mobile":{"point":"-33","unit":"px"}},"positioningBottom":{"Tablet":{"point":"0","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-jGlkzZ">Faq</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-wCgelR","textColor":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"8","top":"","bottom":"","left":""}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<div class="guten-element gutenverse-text-editor guten-wCgelR animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae lectus orci congue magna in egestas nulla libero nisla.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-2fMFxa","content":"View All","buttonWidth":{"Desktop":"","Tablet":"25","Mobile":"60"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"50","left":"50"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}}},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"waterlava-fifth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-fifth"}}},"border":{"radius":{"Tablet":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"50"}},"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"padding":{"Tablet":[],"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"color":{"type":"variable","id":"waterlava-fifth"},"typography":{"type":"variable","id":"button-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"hoverTextColor":{"type":"variable","id":"waterlava-third"},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-button-wrapper guten-2fMFxa"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>View All</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-5fK99z","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"50"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5fK99z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5fK99z"><div class="guten-column-wrapper"><!-- wp:gutenverse/accordions {"elementId":"guten-sXxqbo","iconOpen":"gtn gtn-x-line","iconClosed":"gtn gtn-plus-light","iconPosition":"right","iconColor":{"type":"variable","id":"waterlava-primary"},"iconActiveColor":{"type":"variable","id":"waterlava-third"},"titleBackgroundColor":{"type":"variable","id":"waterlava-third"},"titleTextColor":{"type":"variable","id":"waterlava-primary"},"titleActiveColor":{"type":"variable","id":"waterlava-third"},"titleTypography":{"type":"variable","id":"list-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"21.6"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}}},"contentBackgroundColor":{"type":"variable","id":"waterlava-third"},"contentTextColor":{"type":"variable","id":"waterlava-primary"},"contentTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"50","left":"30"}}},"accordionBorder":{"radius":{"Desktop":{},"Mobile":[]},"all":{"type":"none"}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"solid","color":{"type":"variable","id":"waterlava-primary"},"width":"1"}},"border":{"radius":{"Tablet":[]},"all":{"width":"1"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"},"accordionBorderActive":{"radius":{"Desktop":[]},"all":{"type":"none"}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"20"}},"Tablet":[],"Mobile":[]},"contentBackgroundColorActive":{"type":"variable","id":"waterlava-third"},"contentTextColorActive":{"type":"variable","id":"waterlava-primary"},"contentBorderActive":{"radius":{"Desktop":{}}},"titleBackgroundActiveColor":{"type":"variable","id":"waterlava-primary"},"titleBorderActive":{"radius":{"Desktop":{}},"all":{"type":"none"}},"accordionBoxShadow":{"color":{"r":0,"g":0,"b":0,"a":0}}} -->
<div class="guten-element guten-accordions guten-sXxqbo animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/accordion {"elementId":"guten-Y3rMTt","first":true,"iconOpen":"gtn gtn-x-line","iconClosed":"gtn gtn-plus-light","iconPosition":"right"} -->
<div class="accordion-item active"><div class="accordion-heading"><span class="accordion-text">Can I Use The Code If I Don\'t Know To Code ? </span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-x-line"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-plus-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Fringilla neque iaculis ut. Suspendisse quis justo nec nisi porta commodo mattis a dui. Praesent sed nunc elit consequat egestas.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-Nb5Q3W","iconOpen":"gtn gtn-x-line","iconClosed":"gtn gtn-plus-light","iconPosition":"right"} -->
<div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">Enhance business with new technologies? </span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-x-line"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-plus-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Fringilla neque iaculis ut. Suspendisse quis justo nec nisi porta commodo mattis a dui. Praesent sed nunc elit consequat egestas.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-FJx5fk","iconOpen":"gtn gtn-x-line","iconClosed":"gtn gtn-plus-light","iconPosition":"right"} -->
<div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">Enhance business with New Technologies ? </span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-x-line"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-plus-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Fringilla neque iaculis ut. Suspendisse quis justo nec nisi porta commodo mattis a dui. Praesent sed nunc elit consequat egestas.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
