<?php
/**
 * Gutenverse FAQ Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Section 2', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-xDMJBH","background":{"type":"default","color":{"type":"variable","id":"waterlava-third"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="xDMJBH"><section class="wp-block-gutenverse-section guten-element guten-section guten-xDMJBH layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-KtCsX4","order":{"Tablet":2},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"50"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"0","bottom":"40"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KtCsX4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KtCsX4"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-nNVB7l","type":6,"color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-nNVB7l animated guten-element-hide desktop-fadeInLeft">Extended Licenses questions</h6>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-bCb76G","textColor":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"%","dimension":{"right":"15"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<div class="guten-element gutenverse-text-editor guten-bCb76G animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Donec feugiat lectus mi, nec scelerisque massa viverraac. Vivam vestibulum ornare imperdiet. Nam et sagittis diam. Maecenasma ximus fringilla viverra. Quisque malesuada enim sed aliquam feugiat. Curabitur id sem eu velit eleifend tincidunt met  et dolor iaculis convallis.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-9nh8ZD","spaceBetween":{"Desktop":"5"},"iconColor":{"type":"variable","id":"waterlava-primary"},"iconColorHover":{"type":"variable","id":"waterlava-primary"},"iconSize":{"Mobile":"10"},"textColor":{"type":"variable","id":"waterlava-primary"},"textColorHover":{"type":"variable","id":"waterlava-primary"},"textIndent":{"Desktop":"5"},"textTypography":{"type":"variable","id":"h6-alt-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"weight":"800"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-icon-list guten-9nh8ZD animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-6GmJ4Y"} -->
<div class="guten-element guten-icon-list-item guten-6GmJ4Y"><a id="guten-6GmJ4Y"><i class="fas fa-check"></i><span class="list-text ">Do you have lockers to secure my belongings ?</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-X3oOy0"} -->
<div class="guten-element guten-icon-list-item guten-X3oOy0"><a id="guten-X3oOy0"><i class="fas fa-check"></i><span class="list-text ">Who can guide me in choosing treatments ?</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-bgbix0"} -->
<div class="guten-element guten-icon-list-item guten-bgbix0"><a id="guten-bgbix0"><i class="fas fa-check"></i><span class="list-text ">When should I make my spa reservations ?</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-qr9LxN"} -->
<div class="guten-element guten-icon-list-item guten-qr9LxN"><a id="guten-qr9LxN"><i class="fas fa-check"></i><span class="list-text ">What if I have special health conditions ?</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/divider {"elementId":"guten-SlV95S","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"waterlava-seventh"},"size":{"Desktop":"1"},"dividerAlign":{"Desktop":"left"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15"}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-SlV95S"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/heading {"elementId":"guten-rvJcKK","type":6,"color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-rvJcKK animated guten-element-hide desktop-fadeInLeft">Support</h6>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-PXxGHY","textColor":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"%","dimension":{"right":"15"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-PXxGHY animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Curabitur interdum ipsum convallis porttitor vulputate. Morbi sed massa at dui congue porttitor eget. Quisque congue porttitor malesuada enim sed aliquam feugiat. </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-Gid8Hk","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"hideTablet":false,"hideMobile":true,"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="Gid8Hk"><section class="wp-block-gutenverse-section guten-element guten-section guten-Gid8Hk animated guten-element-hide desktop-fadeInLeft hide-mobile layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ZikHrh","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ZikHrh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ZikHrh"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Vqyh7S","title":"Email","description":"purina@domain.com","icon":"gtn gtn-mail-line","iconSize":{"Desktop":"50","Tablet":"40"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconColor":{"type":"variable","id":"waterlava-primary"},"iconHoverColor":{"type":"variable","id":"waterlava-primary"},"iconBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"","right":""}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"titleColor":{"type":"variable","id":"waterlava-primary"},"titleHoverColor":{"type":"variable","id":"waterlava-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"descColor":{"type":"variable","id":"waterlava-primary"},"descHoverColor":{"type":"variable","id":"waterlava-primary"},"descTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"badgePadding":{"Tablet":[]},"badgeRadius":{"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-Vqyh7S guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-mail-line"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Email</h2><p class="icon-box-description">purina@domain.com</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-oDPU57","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"none"}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-oDPU57"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="oDPU57"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-XtawCp","title":"Phone","description":"+62-864-349-1","icon":"gtn gtn-phone-call-line","iconSize":{"Desktop":"45","Tablet":"35"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconColor":{"type":"variable","id":"waterlava-primary"},"iconHoverColor":{"type":"variable","id":"waterlava-primary"},"iconBorder":{"radius":{"Desktop":{},"Tablet":[]}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"5"}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"waterlava-primary"},"titleHoverColor":{"type":"variable","id":"waterlava-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"waterlava-primary"},"descHoverColor":{"type":"variable","id":"waterlava-primary"},"descTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"}} -->
<div class="guten-element guten-XtawCp guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone-call-line"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Phone</h2><p class="icon-box-description">+62-864-349-1</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-F68FIB","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"hideDesktop":true,"hideTablet":true,"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="F68FIB"><section class="wp-block-gutenverse-section guten-element guten-section guten-F68FIB hide-desktop hide-tablet layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-DPzGFB","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DPzGFB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DPzGFB"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-LNaFDg","title":"Email","description":"purina@domain.com","icon":"gtn gtn-mail-line","iconSize":{"Desktop":"50","Tablet":"40","Mobile":"40"},"iconPosition":"top","align":{"Desktop":"flex-start","Mobile":"center","Tablet":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"","right":""}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{}},"titleColor":{"r":80,"g":65,"b":74,"a":1},"titleHoverColor":{"r":80,"g":65,"b":74,"a":1},"titleTypography":{"type":"variable","id":"testimonial-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"22"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{}},"descColor":{"r":58,"g":44,"b":57,"a":1},"descHoverColor":{"r":58,"g":44,"b":57,"a":1},"descTypography":{"type":"variable","id":"funfact-title-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"18"}},"weight":"400"},"badgePadding":{"Tablet":[]},"badgeRadius":{"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-LNaFDg guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-mail-line"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Email</h2><p class="icon-box-description">purina@domain.com</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-E1y7cX","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-E1y7cX"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="E1y7cX"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-ywP3u3","title":"Phone","description":"+62-864-349-1","icon":"gtn gtn-phone-call-line","iconSize":{"Desktop":"45","Tablet":"35","Mobile":"40"},"iconPosition":"top","align":{"Desktop":"flex-start","Tablet":"center","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"iconBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"5"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{}},"titleColor":{"r":80,"g":65,"b":74,"a":1},"titleHoverColor":{"r":80,"g":65,"b":74,"a":1},"titleTypography":{"type":"variable","id":"testimonial-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"22"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{}},"descColor":{"r":58,"g":44,"b":57,"a":1},"descHoverColor":{"r":58,"g":44,"b":57,"a":1},"descTypography":{"type":"variable","id":"funfact-title-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"18"}},"weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-ywP3u3 guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone-call-line"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Phone</h2><p class="icon-box-description">+62-864-349-1</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-NJ5VZu","order":{"Tablet":1},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"80","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"50","right":"20","left":"20"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NJ5VZu"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="NJ5VZu"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-wPjYx0","color":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-wPjYx0 animated guten-element-hide desktop-fadeInRight">More Questions</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-iXYoBm","textColor":{"type":"variable","id":"waterlava-primary"},"typography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"%","dimension":{"right":"15"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"}} -->
<div class="guten-element gutenverse-text-editor guten-iXYoBm animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-hkCfM3","formId":{"label":"Form Questions","value":737},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"}} -->
<form style="display:none" class="guten-element guten-form-builder guten-hkCfM3 animated guten-element-hide desktop-fadeInRight" data-form-id="737"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-EOsDvn","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="EOsDvn"><section class="wp-block-gutenverse-section guten-element guten-section guten-EOsDvn layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-wLhb92","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wLhb92"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wLhb92"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-Ebofvp","showLabel":false,"inputPlaceholder":"First Name","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningLocation":"default","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"none","width":"1","color":{"type":"variable","id":"waterlava-eighth"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"20","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":""}}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-seventh"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-seventh"}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-Ebofvp hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="First Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-XSWnXa","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":[]},"padding":{"Tablet":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-XSWnXa"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XSWnXa"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-4pq5fm","showLabel":false,"inputPlaceholder":"Last Name","showHelper":false,"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningLocation":"default","border":{"radius":{"Desktop":[]},"all":{"type":"none","width":"1","color":{"r":58,"g":44,"b":57,"a":0.21}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":[]},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-seventh"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":[]},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-seventh"}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-4pq5fm hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Last Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-bT1amd","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="bT1amd"><section class="wp-block-gutenverse-section guten-element guten-section guten-bT1amd layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-jev0cv","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jev0cv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jev0cv"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-telp {"elementId":"guten-IByXg6","showLabel":false,"showHelper":false,"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningLocation":"default","border":{"radius":{"Desktop":[]},"all":{"type":"none","width":"1","color":{"r":58,"g":44,"b":57,"a":0.21}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Your Phone","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-seventh"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-seventh"}}}} -->
<div class="guten-element guten-form-input-telp guten-form-input guten-input-position-top guten-IByXg6 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;telp&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Phone" name="input-telp" class="gutenverse-input gutenverse-input-tel" type="tel" pattern="[0-9]{3}-[0-9]{2}-[0-9]{3}"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-telp --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-6JcAxB","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0"}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"0"}},"Desktop":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6JcAxB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6JcAxB"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-email {"elementId":"guten-abl9rj","showLabel":false,"showHelper":false,"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningLocation":"default","border":{"radius":{"Desktop":[]},"all":{"type":"none","width":"1","color":{"r":58,"g":44,"b":57,"a":0.21}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"email@domain.com","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-seventh"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-seventh"}}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-abl9rj hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="email@domain.com" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-Inh0Zo","showLabel":false,"showHelper":false,"labelPadding":{"Tablet":[],"Desktop":[]},"labelMargin":{"Tablet":[],"Desktop":[]},"positioningType":{"Desktop":"default"},"positioningLocation":"default","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"all":{"type":"none","color":""}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"20","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"inputHeight":{"Desktop":"150"},"inputPlaceholder":"Your Question","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"waterlava-seventh"}},"inputTypography":{"type":"variable","id":"text-editor-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Tablet":[]},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorHover":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":216,"g":215,"b":217,"a":1}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"waterlava-primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"waterlava-seventh"}}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-Inh0Zo hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Question" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-gXUOwC","content":"Send Question","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"waterlava-fifth"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"waterlava-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":{}}},"positioningType":{"Desktop":"default"},"positioningLocation":"default","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"color":{"type":"variable","id":"waterlava-third"},"typography":{"type":"variable","id":"button-font","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"hoverTextColor":{"type":"variable","id":"waterlava-third"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"30","bottom":"20","left":"30"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-gXUOwC"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Question</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
