<?php
/**
 * Gutenverse Footer content.
 */
return array(
	'title'      => __( 'Gutenverse Footer', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-nDAGrQ","background":{"type":"default","color":{"type":"variable","id":"sixth"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1397,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/shape-divider-footer-3.webp"},"Mobile":{"id":1485,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/shape-divider-footer-2.webp"},"Tablet":{"id":1485,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/shape-divider-footer-2.webp"}},"size":{"Desktop":"contain","Tablet":"contain","Mobile":"default"},"position":{"Desktop":"top center","Tablet":"top center","Mobile":"top center"},"repeat":{"Desktop":"no-repeat","Mobile":"default"},"yposition":{"Tablet":{"point":"61","unit":"px"}},"xposition":{"Tablet":{"point":"1","unit":"px"}},"width":{"Mobile":{"point":"500","unit":"px"}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"15","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"120","right":"","bottom":"","left":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="nDAGrQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-nDAGrQ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-F3KILv","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-F3KILv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="F3KILv"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-I4XJkP","imgSrc":{"media":{"imageId":20,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/logo-150x150.webp","orientation":"landscape"},"medium":{"height":67,"width":300,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/logo-300x67.webp","orientation":"landscape"},"large":{"height":227,"width":1024,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/logo-1024x227.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/logo-site.webp","height":361,"width":1627,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"260","unit":"px"},"Mobile":{"point":"190","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-I4XJkP"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RESTANCE_URI ) . 'assets/img/logo-site.webp" height="361" width="1627"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-cQF6VH","dropcapMargin":{},"dropcapPadding":{},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"28","bottom":"","left":"28"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"120","bottom":"0","left":"120"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"30"}}}} -->
<div class="guten-element gutenverse-text-editor guten-cQF6VH"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/divider {"elementId":"guten-Udxm0G","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"primary"},"size":{"Desktop":"1"},"gap":{"Desktop":"15"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"positioningType":{"Desktop":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"100"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-Udxm0G"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-al9k1k","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="al9k1k"><section class="wp-block-gutenverse-section guten-element guten-section guten-al9k1k layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":39.091,"Tablet":60,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-1N6BmF","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"120","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1N6BmF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1N6BmF"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-zqV1QF","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"25"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-zqV1QF">Keep Updated</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-byDq8g","dropcapMargin":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"dropcapPadding":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-byDq8g"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellent.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1140"},"isChild":true,"gap":"no","elementId":"guten-RkSNPO","margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}},"positioningType":{"Desktop":"default"}} -->
<div class="section-wrapper" data-id="RkSNPO"><section class="wp-block-gutenverse-section guten-element guten-section guten-RkSNPO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-yukCl1"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-yukCl1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="yukCl1"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-q6FZ9l","successPadding":{"Desktop":{}},"successBorder":{"radius":{"Desktop":{}}},"errorPadding":{"Desktop":{}},"errorBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-q6FZ9l"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-vyygzc"} -->
<div class="section-wrapper" data-id="vyygzc"><section class="wp-block-gutenverse-section guten-element guten-section guten-vyygzc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-eEKsqt"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eEKsqt"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="eEKsqt"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-email {"elementId":"guten-cdExhk","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"helperPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"custom","Tablet":"inline"},"positioningWidth":{"Desktop":{"unit":"%","point":"75"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"12","bottom":"16","left":"24"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"placeholderColor":{"Desktop":{"type":"variable","id":"forth"}},"inputTypography":{"type":"variable","id":"bottom-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.1"}},"inputColorNormal":{"Desktop":{}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"inputColorFocus":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-cdExhk hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-dEm4T7","buttonWidth":{"Desktop":""},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"showIcon":true,"icon":"fas fa-paper-plane","iconSpacing":{"Desktop":""},"iconSize":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"","unit":"px"}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"56","unit":"px"}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"iconColor":{"type":"variable","id":"white"},"hoverIconColor":{"type":"variable","id":"secondary"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"19","right":"20","bottom":"19","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"16","right":"18","bottom":"18","left":"18"}},"Mobile":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"17","left":"16"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-dEm4T7"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><i class="fa-lg fas fa-paper-plane"></i><span></span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":18.885,"Tablet":40,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-4IRtfz","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4IRtfz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="4IRtfz"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-wstLzr","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"19"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-wstLzr">Other Pages</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-i6IA0S","spaceBetween":{"Desktop":"8","Tablet":"6"},"textColor":{"type":"variable","id":"white"},"textColorHover":{"type":"variable","id":"secondary"},"textIndent":{"Desktop":""},"textTypography":{"type":"variable","id":"funfact-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-icon-list guten-i6IA0S"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-GoLOd5","hideIcon":true,"margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
<div class="guten-element guten-icon-list-item guten-GoLOd5"><a id="guten-GoLOd5" href="#"><span class="list-text no-icon">About Us</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-FdyBkN","hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-FdyBkN"><a id="guten-FdyBkN" href="#"><span class="list-text no-icon">Services</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Nvf4Am","hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-Nvf4Am"><a id="guten-Nvf4Am" href="#"><span class="list-text no-icon">Pricing</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-7e8WIC","hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-7e8WIC"><a id="guten-7e8WIC" href="#"><span class="list-text no-icon">Contact</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":18.94,"Tablet":60,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-MGSomc","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MGSomc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MGSomc"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-13zsl6","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"19"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-13zsl6">Quick Links</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-dGONxS","spaceBetween":{"Desktop":"8","Tablet":"6"},"textColor":{"type":"variable","id":"white"},"textColorHover":{"type":"variable","id":"secondary"},"textIndent":{"Desktop":""},"textTypography":{"type":"variable","id":"funfact-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-icon-list guten-dGONxS"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-IjXhlF","hideIcon":true,"margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
<div class="guten-element guten-icon-list-item guten-IjXhlF"><a id="guten-IjXhlF" href="#"><span class="list-text no-icon">Privacy Policy</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Rkuk9h","hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-Rkuk9h"><a id="guten-Rkuk9h" href="#"><span class="list-text no-icon">Terms of Service</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-TG7IHV","hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-TG7IHV"><a id="guten-TG7IHV" href="#"><span class="list-text no-icon">Credit</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-5bieih","hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-5bieih"><a id="guten-5bieih" href="#"><span class="list-text no-icon">FAQ</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":23.082,"Tablet":40,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-R2ZOF1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-R2ZOF1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="R2ZOF1"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-cQcZb1","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"19"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-cQcZb1">Office Location</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-pgojFq","spaceBetween":{"Desktop":"8","Tablet":"6"},"iconColor":{"type":"variable","id":"secondary"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"16"},"textTypography":{"type":"variable","id":"funfact-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-icon-list guten-pgojFq"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-P0f8l5","margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
<div class="guten-element guten-icon-list-item guten-P0f8l5"><a id="guten-P0f8l5"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Raya Mas Ubud, Gianyar</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-qsSwpt"} -->
<div class="guten-element guten-icon-list-item guten-qsSwpt"><a id="guten-qsSwpt"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 119-9234-231</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-C1xDGL","margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":""}},"Tablet":{"unit":"px","dimension":{"right":"10","top":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-icon-list-item guten-C1xDGL"><a id="guten-C1xDGL"><i class="fas fa-clock"></i><span class="list-text ">Mon - Sat : 09:00 AM - 21:00 PM Sunday : Closed</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/divider {"elementId":"guten-JQ15Qq","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"primary"},"size":{"Desktop":"1"},"gap":{"Desktop":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-JQ15Qq"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-dnc1OC","verticalAlign":"center","background":{},"backgroundHover":{},"border":{"radius":{"Desktop":{"unit":"px"}},"top":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":0.1}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","left":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="dnc1OC"><section class="wp-block-gutenverse-section guten-element guten-section guten-dnc1OC layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-xpw1eN","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"default","Mobile":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xpw1eN"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="xpw1eN"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-ZVsZIs","alignment":{"Desktop":"left","Tablet":"left","Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"icon-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300","spacing":{"Desktop":"0.05"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element gutenverse-text-editor guten-ZVsZIs"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Copyright © 2022 Real Estate &amp; Property Themes By Jegstudio</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-wePsnC","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"default","Mobile":"default"},"horizontalAlign":{"Desktop":"center","Mobile":"default"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"animation":{},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wePsnC hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wePsnC"><div class="guten-column-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-97rERu","iconSize":{"Desktop":{"point":"18","unit":"px"}},"gap":{"Desktop":"25"},"alignment":{"Desktop":"flex-end","Mobile":"center"},"color":"custom","iconColor":{"type":"variable","id":"secondary"},"bgColor":{"r":255,"g":96,"b":96,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"none","width":"0"}},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":"-10"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{}}} -->
<div class="guten-element guten-social-icons guten-97rERu rounded horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-9wjt6w"} -->
<div class="guten-element guten-social-icon guten-9wjt6w facebook"><a id="guten-9wjt6w"><i class="fab fa-facebook"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-vKb92U"} -->
<div class="guten-element guten-social-icon guten-vKb92U instagram"><a id="guten-vKb92U"><i class="fab fa-instagram"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-8F2IQ9"} -->
<div class="guten-element guten-social-icon guten-8F2IQ9 twitter"><a id="guten-8F2IQ9"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-UjM1YB"} -->
<div class="guten-element guten-social-icon guten-UjM1YB youtube"><a id="guten-UjM1YB"><i class="fab fa-youtube"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
