<?php
/**
 * Gutenverse Home CTA content.
 */
return array(
	'title'      => __( 'Gutenverse Home CTA', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-xtGsfJ","background":{"type":"default","image":{"Desktop":{"id":1336,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-villa-house-home-pool-italy-599833-pxhere.com.webp"}},"position":{"Desktop":"center center","Tablet":"default"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":"","width":{"Desktop":{"unit":"%","point":"150"}},"xposition":{"Desktop":{"point":"0","unit":"px"}},"yposition":{"Desktop":{"point":"-350","unit":"px"}}},"backgroundHover":{},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1511,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/shape-divider-5.webp"}},"position":{"Mobile":"custom","Desktop":"bottom left","Tablet":"custom"},"yposition":{"Mobile":{"point":"550","unit":"px"},"Tablet":{"point":"28","unit":"px"}},"xposition":{"Mobile":{"point":"1","unit":"px"},"Tablet":{"point":"-150","unit":"px"}},"repeat":{"Mobile":"no-repeat","Desktop":"no-repeat"},"size":{"Tablet":"default","Desktop":"custom"},"width":{"Desktop":{"point":"1500","unit":"px"}},"color":{"r":0,"g":0,"b":0,"a":0.6}},"opacity":"1","topDivider":{"width":{"Mobile":""}},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"150","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"70","right":"20","left":"10","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="xtGsfJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-xtGsfJ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":55,"Mobile":null,"Tablet":40},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Hw32Qq","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Hw32Qq hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Hw32Qq"><div class="guten-column-wrapper"></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":44.9,"Tablet":60,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-TFlSEG","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TFlSEG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TFlSEG"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-8qc5n5","textAlign":{"Desktop":"right","Mobile":"left"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"54"},"Tablet":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-8qc5n5 animated guten-element-hide desktop-fadeInRight">The Best Partner to Find New House.</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-9mTkQe","alignment":{"Desktop":"right","Mobile":"left"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"","left":"0"}},"Tablet":{"unit":"%","dimension":{"left":"25"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-9mTkQe animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-EKSCh4","content":"Contact Us","alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"type":"variable","id":"secondary"},"type":"solid","width":"1"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"bottom-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.1"}},"hoverTextColor":{"type":"variable","id":"secondary"}} -->
<div class="guten-element guten-button-wrapper guten-EKSCh4"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Contact Us</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
