<?php
/**
 * Gutenverse Single Post Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Hero', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":1353,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-structure-window-building-skyscraper-urban-1001301-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"r":3,"g":3,"b":3,"a":0.8}},"opacity":"1","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-152","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"-158"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"280","bottom":"230","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"230","bottom":"160","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"230","bottom":"160","right":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="9rsSZi"><section class="wp-block-gutenverse-section guten-element guten-section guten-9rsSZi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-a93VDD","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-a93VDD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="a93VDD"><div class="guten-column-wrapper"><!-- wp:gutenverse/post-title {"elementId":"guten-o210S6","htmlTag":"h4","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"h4-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"40"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"color":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{}}} -->
<div class="guten-element guten-post-title guten-o210S6"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-phUR4P","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="phUR4P"><section class="wp-block-gutenverse-section guten-element guten-section guten-phUR4P animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-qSiPOj","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qSiPOj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qSiPOj"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-g8pX5K","icon":"fas fa-calendar-alt","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"background":{"type":"default","color":""},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-g8pX5K guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="fas fa-calendar-alt"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-date {"elementId":"guten-6M0Zvs","typography":{"type":"variable","id":"funfact-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"400"},"color":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":""}}},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-date guten-6M0Zvs"></div>
<!-- /wp:gutenverse/post-date -->

<!-- wp:gutenverse/icon {"elementId":"guten-biINo7","icon":"fas fa-user-circle","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-biINo7 guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="fas fa-user-circle"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-author {"elementId":"guten-LzHUTf","typography":{"type":"variable","id":"funfact-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"400"},"color":{"type":"variable","id":"white"},"authorBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-author guten-LzHUTf"></div>
<!-- /wp:gutenverse/post-author --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
