<?php
/**
 * Gutenverse Property List Featured content.
 */
return array(
	'title'      => __( 'Gutenverse Property List Featured', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-TTcyWr","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"40","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="TTcyWr"><section class="wp-block-gutenverse-section guten-element guten-section guten-TTcyWr layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-I8pRoZ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-I8pRoZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="I8pRoZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-QBOSMr","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="QBOSMr"><section class="wp-block-gutenverse-section guten-element guten-section guten-QBOSMr layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-LE5mn7","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LE5mn7"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LE5mn7"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-FOsl6G","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-FOsl6G animated guten-element-hide desktop-fadeInUp">The Property</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-ZaPazg","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"54"},"Tablet":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-ZaPazg animated guten-element-hide desktop-fadeInUp">Featured Properties</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-fcqIdg","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"28","left":"28","top":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="guten-element gutenverse-text-editor guten-fcqIdg animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-BhDqlj","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0","right":"20","left":"20"}},"Mobile":[]},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="BhDqlj"><section class="wp-block-gutenverse-section guten-element guten-section guten-BhDqlj layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":65.698,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-6CHvpB","background":{"type":"default","image":{"Desktop":{"id":485,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/villa-house-chair-interior-view-home-1210556-pxhere.com.webp"}},"size":{"Desktop":"cover"},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":[]},"padding":{"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6CHvpB animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6CHvpB"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-zdIIOh","space":{"Desktop":{"point":"500","unit":"px"},"Mobile":{"point":"200","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-zdIIOh"></div>
<!-- /wp:gutenverse/spacer --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":34.3,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-W2Vl2K","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":""},"opacity":"0.2","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-W2Vl2K"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="W2Vl2K"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-cpmTwA","type":3,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-alt-font","font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-cpmTwA animated guten-element-hide desktop-fadeInRight">Pondok Asri Villa, Nusa Dua</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-IMcLMY","textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{},"Tablet":{"unit":"%","dimension":{"right":"26"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<div class="guten-element gutenverse-text-editor guten-IMcLMY animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-jPcyer","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"16"},"textColor":{"type":"variable","id":"third"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"}} -->
<div class="guten-element guten-icon-list guten-jPcyer animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-nmzVL8","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-nmzVL8"><a id="guten-nmzVL8"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Nusa Dua, Badung, Bali</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-WV5wVa"} -->
<div class="guten-element guten-icon-list-item guten-WV5wVa"><a id="guten-WV5wVa"><i class="fas fa-phone-alt"></i><span class="list-text ">+62 82 334 556 78</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-X320Wh","type":3,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"price-text-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-X320Wh animated guten-element-hide desktop-fadeInRight">Unit Detail</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-riSai0","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"900"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="riSai0"><section class="wp-block-gutenverse-section guten-element guten-section guten-riSai0 animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-GvZbUN","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GvZbUN"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GvZbUN"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-7s9Yhr","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"16"},"textColor":{"type":"variable","id":"third"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
<div class="guten-element guten-icon-list guten-7s9Yhr"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Y9l4oa"} -->
<div class="guten-element guten-icon-list-item guten-Y9l4oa"><a id="guten-Y9l4oa"><i class="fas fa-pencil-ruler"></i><span class="list-text ">250 M2</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-EzcFS2"} -->
<div class="guten-element guten-icon-list-item guten-EzcFS2"><a id="guten-EzcFS2"><i class="fas fa-bed"></i><span class="list-text ">4 Room</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-jcXvDM","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jcXvDM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jcXvDM"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-PV359s","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"16"},"textColor":{"type":"variable","id":"third"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"}} -->
<div class="guten-element guten-icon-list guten-PV359s"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-erSMdB"} -->
<div class="guten-element guten-icon-list-item guten-erSMdB"><a id="guten-erSMdB"><i class="fas fa-shower"></i><span class="list-text ">2 Bathroom</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-c9gooz"} -->
<div class="guten-element guten-icon-list-item guten-c9gooz"><a id="guten-c9gooz"><i class="fas fa-car"></i><span class="list-text ">1 Garage</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-Fqm85B","content":"Get it Now","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"type":"variable","id":"secondary"},"type":"solid","width":"1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1000"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"bottom-font","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.1"}},"hoverTextColor":{"type":"variable","id":"secondary"}} -->
<div class="guten-element guten-button-wrapper guten-Fqm85B"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Get it Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
