<?php
/**
 * Gutenverse Single Post Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Hero', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":304,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/camera-map-polaroid-electronics-picture-photograph-31187-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"sixth"}},"opacity":"0.6","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-90"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"180","bottom":"160"}},"Tablet":{"unit":"px","dimension":{"top":"160","bottom":"160","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="9rsSZi"><section class="wp-block-gutenverse-section guten-element guten-section guten-9rsSZi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-jdvueZ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jdvueZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jdvueZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/post-title {"elementId":"guten-20khXN","noContentText":"","linkTo":"post","alignment":{"Desktop":"center","Tablet":"center"},"typography":{"type":"variable","id":"h2-style-1"},"color":{"type":"variable","id":"ninth"},"colorHover":{"type":"variable","id":"ninth"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"100","left":"100"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="guten-element guten-post-title guten-20khXN animated guten-element-hide desktop-fadeInUp"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"540"},"isChild":true,"height":{},"gap":"no","elementId":"guten-RaQZDd","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Mobile":{},"Tablet":{}},"padding":{"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="RaQZDd"><section class="wp-block-gutenverse-section guten-element guten-section guten-RaQZDd animated guten-element-hide slow desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":22.13,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ri53Zs","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"flex-end","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ri53Zs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ri53Zs"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-6LxTeN","icon":"far fa-user-circle","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"iconColorHoverTwo":{"type":"variable","id":"secondary"},"iconShape":"custom","iconBorderRadius":{},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-6LxTeN guten-icon"><span class="guten-icon-wrapper custom stacked"><i class="far fa-user-circle"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-author {"elementId":"guten-3VPYAz","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"text-editor-font"},"color":{"type":"variable","id":"ninth"},"colorHover":{"type":"variable","id":"ninth"},"authorBorder":{"radius":{"Desktop":{}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"130","unit":"px"}}} -->
<div class="guten-element guten-post-author guten-3VPYAz"></div>
<!-- /wp:gutenverse/post-author --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-TTyUiP","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TTyUiP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TTyUiP"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-8OoPxa","icon":"far fa-calendar-alt","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"iconColorHoverTwo":{"type":"variable","id":"secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-8OoPxa guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="far fa-calendar-alt"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-date {"elementId":"guten-YGi9qB","typography":{"type":"variable","id":"text-editor-font"},"color":{"type":"variable","id":"ninth"},"colorHover":{"type":"variable","id":"ninth"},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"130","unit":"px"}}} -->
<div class="guten-element guten-post-date guten-YGi9qB"></div>
<!-- /wp:gutenverse/post-date --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Mobile":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-sX77EC","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sX77EC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sX77EC"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-xhFbG1","icon":"far fa-folder-open","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"iconColorHoverTwo":{"type":"variable","id":"secondary"},"iconShape":"custom","iconBorderRadius":{},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-xhFbG1 guten-icon"><span class="guten-icon-wrapper custom stacked"><i class="far fa-folder-open"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-terms {"elementId":"guten-YVtdZw","typography":{"type":"variable","id":"text-editor-font"},"color":{"type":"variable","id":"ninth"},"colorHover":{"type":"variable","id":"ninth"},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"130","unit":"px"}}} -->
<div class="guten-element guten-post-terms guten-YVtdZw"></div>
<!-- /wp:gutenverse/post-terms --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
