<?php
/**
 * Gutenverse Home Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 3', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-jGzT2W","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="jGzT2W"><section class="wp-block-gutenverse-section guten-element guten-section guten-jGzT2W layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Hfvgjy","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Hfvgjy animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Hfvgjy"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-v8QKdj","imgSrc":{"media":{"imageId":56,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":684,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com-1024x684.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com.webp","height":801,"width":1200,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"723","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"485","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-v8QKdj"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com.webp" height="801" width="1200"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-xnz2Y1","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="xnz2Y1"><section class="wp-block-gutenverse-section guten-element guten-section guten-xnz2Y1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-rBUKcy","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rBUKcy"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rBUKcy"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SqMGY4","type":6,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-SqMGY4">Labuan Bajo, NTT</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-GSYiqY","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GSYiqY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GSYiqY"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-hlw9eF","type":6,"textAlign":{"Mobile":"center","Tablet":"right","Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h4-style-2"},"margin":{"Tablet":{"unit":"px","dimension":{"right":"70"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"30","bottom":"","left":""}}},"padding":{"Tablet":{},"Mobile":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-hlw9eF">$249.00</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-BxNS8h","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
<div class="guten-element gutenverse-text-editor guten-BxNS8h"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-UfoMP5","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="UfoMP5"><section class="wp-block-gutenverse-section guten-element guten-section guten-UfoMP5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-0vAAD6","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0vAAD6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0vAAD6"><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-WNJjQP","title":"","starIcon":"default","rating":"5","total":"5","iconColorMarked":{"type":"variable","id":"secondary"},"iconColorUnmarked":{"type":"variable","id":"fifth"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
<div class="guten-element guten-star-rating guten-WNJjQP"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Eb4qfJ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Eb4qfJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Eb4qfJ"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-fqObuP","content":"Book Now","alignButton":{"Desktop":"right","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"40","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-2"},"hoverTextColor":{"type":"variable","id":"ninth"}} -->
<div class="guten-element guten-button-wrapper guten-fqObuP"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3iy2Tp","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3iy2Tp animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3iy2Tp"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-ueyqxi","imgSrc":{"media":{"imageId":67,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":204,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com-300x204.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com.webp","height":681,"width":1000,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-ueyqxi"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com.webp" height="681" width="1000"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-uOrvx1","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="uOrvx1"><section class="wp-block-gutenverse-section guten-element guten-section guten-uOrvx1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-PPgYiU","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PPgYiU"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PPgYiU"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-UhBvSH","type":6,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-UhBvSH">Rice Terraces, Bali</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-MnpExD","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"30"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MnpExD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MnpExD"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-6RyYvU","type":6,"textAlign":{"Tablet":"center","Mobile":"center","Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h4-style-2"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-6RyYvU">$299.00</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-mjNkV1","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
<div class="guten-element gutenverse-text-editor guten-mjNkV1"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-GoTRW5","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="GoTRW5"><section class="wp-block-gutenverse-section guten-element guten-section guten-GoTRW5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-XeawVq","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-XeawVq"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XeawVq"><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-Xy1xF0","title":"","starIcon":"default","rating":"5","total":"5","iconColorMarked":{"type":"variable","id":"secondary"},"iconColorUnmarked":{"type":"variable","id":"fifth"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Mobile":{}}} -->
<div class="guten-element guten-star-rating guten-Xy1xF0"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-8yzJk3","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"right":""}}},"padding":{"Tablet":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8yzJk3"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8yzJk3"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-dGeAbw","content":"Book Now","alignButton":{"Desktop":"right","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-2"},"hoverTextColor":{"type":"variable","id":"ninth"}} -->
<div class="guten-element guten-button-wrapper guten-dGeAbw"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-0lhJNz","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"30","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0lhJNz animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0lhJNz"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-reK5GV","imgSrc":{"media":{"imageId":68,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":225,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com-300x225.webp","orientation":"landscape"},"large":{"height":768,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com-1024x768.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com.webp","height":1125,"width":1500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Mobile":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-reK5GV"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com.webp" height="1125" width="1500"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-roy7ls","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="roy7ls"><section class="wp-block-gutenverse-section guten-element guten-section guten-roy7ls layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-FlHd45","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-FlHd45"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FlHd45"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ef8lC8","type":6,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-ef8lC8">Prambanan, Yogya</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-1vONrr","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"30"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1vONrr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1vONrr"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-cNPScD","type":6,"textAlign":{"Mobile":"center","Tablet":"center","Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h4-style-2"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-cNPScD">$199.00</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-yFW8QX","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
<div class="guten-element gutenverse-text-editor guten-yFW8QX"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-2RV4Gx","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="2RV4Gx"><section class="wp-block-gutenverse-section guten-element guten-section guten-2RV4Gx layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-1g1wQT","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1g1wQT"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1g1wQT"><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-4WdYJJ","title":"","starIcon":"default","rating":"5","total":"5","iconColorMarked":{"type":"variable","id":"secondary"},"iconColorUnmarked":{"type":"variable","id":"fifth"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Mobile":{}}} -->
<div class="guten-element guten-star-rating guten-4WdYJJ"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-t0yUht","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-t0yUht"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="t0yUht"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-7gDWjV","content":"Book Now","alignButton":{"Desktop":"right","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"33","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-2"},"hoverTextColor":{"type":"variable","id":"ninth"}} -->
<div class="guten-element guten-button-wrapper guten-7gDWjV"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
