<?php
/**
 * Gutenverse FAQ Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Section 3', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-MA14S5","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"70"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="MA14S5"><section class="wp-block-gutenverse-section guten-element guten-section guten-MA14S5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3fQVwF","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3fQVwF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3fQVwF"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-4Uhwo5","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="4Uhwo5"><section class="wp-block-gutenverse-section guten-element guten-section guten-4Uhwo5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-A4U61B","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-A4U61B"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="A4U61B"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-tLcMwv","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h3-style-2"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-tLcMwv animated guten-element-hide desktop-fadeInLeft">Reservation</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/accordions {"elementId":"guten-mTVb3w","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right","iconColor":{"type":"variable","id":"secondary"},"iconActiveColor":{"type":"variable","id":"secondary"},"titleBackgroundColor":{"type":"variable","id":"ninth"},"titleTextColor":{"type":"variable","id":"primary"},"titleActiveColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"accordion-title-font"},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":[]},"contentBackgroundColor":{"type":"variable","id":"ninth"},"contentTextColor":{"type":"variable","id":"fifth"},"contentTypography":{"type":"variable","id":"text-editor-font"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"40"}},"Tablet":[],"Mobile":[]},"accordionBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]},"all":{"type":"none","color":""}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":""}},"Tablet":[]},"contentBackgroundColorActive":{"type":"variable","id":"ninth"},"contentTextColorActive":{"type":"variable","id":"fifth"},"contentBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"10"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"titleBackgroundActiveColor":{"type":"variable","id":"ninth"},"titleBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}}} -->
<div class="guten-element guten-accordions guten-mTVb3w animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/accordion {"elementId":"guten-PhsjkV","first":true,"iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item active"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">Do i have to make reservation?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-c35H3u","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">What are your terms and conditions?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-YDeh1F","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">Where do I find my trip notes?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-OGQZyp","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OGQZyp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OGQZyp"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-icHKKp","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="icHKKp"><section class="wp-block-gutenverse-section guten-element guten-section guten-icHKKp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-jz00ZB","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"10"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jz00ZB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jz00ZB"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-XSy0fh","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h3-style-2"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-XSy0fh animated guten-element-hide desktop-fadeInRight">Preparation</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/accordions {"elementId":"guten-XG5fXG","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right","iconColor":{"type":"variable","id":"secondary"},"iconActiveColor":{"type":"variable","id":"secondary"},"titleBackgroundColor":{"type":"variable","id":"ninth"},"titleTextColor":{"type":"variable","id":"primary"},"titleActiveColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"accordion-title-font"},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":[]},"contentBackgroundColor":{"type":"variable","id":"ninth"},"contentTextColor":{"type":"variable","id":"fifth"},"contentTypography":{"type":"variable","id":"text-editor-font"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"40"}},"Tablet":[],"Mobile":[]},"accordionBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]},"all":{"type":"none","color":""}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":""}},"Tablet":[]},"contentBackgroundColorActive":{"type":"variable","id":"ninth"},"contentTextColorActive":{"type":"variable","id":"fifth"},"contentBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"10"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"titleBackgroundActiveColor":{"type":"variable","id":"ninth"},"titleBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}}} -->
<div class="guten-element guten-accordions guten-XG5fXG animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/accordion {"elementId":"guten-OsaCC4","first":true,"iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item active"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">What do i need to bring?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-TCo3EF","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">What are your terms and conditions?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-A4BRVP","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">Where do I find my trip notes?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
