<?php
/**
 * Gutenverse Destination Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Destination Section 3', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-HN14DV","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}},"Tablet":{"unit":"px","dimension":{"bottom":"80"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="HN14DV"><section class="wp-block-gutenverse-section guten-element guten-section guten-HN14DV animated guten-element-hide slow desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-zYj6AY","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20","bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-zYj6AY animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zYj6AY"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-MRKcMe","imgSrc":{"media":{"imageId":70,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com-1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com.webp","height":1001,"width":1500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"733","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"488","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-MRKcMe"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com.webp" height="1001" width="1500"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-lHQU5p","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="lHQU5p"><section class="wp-block-gutenverse-section guten-element guten-section guten-lHQU5p layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-vCaCmD","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vCaCmD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vCaCmD"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-AYA5PF","type":6,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-AYA5PF">Borobudur, Java</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-96aNBR","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default","Mobile":"flex-start"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-96aNBR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="96aNBR"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Xpfyi1","type":6,"textAlign":{"Tablet":"right","Mobile":"center","Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h4-style-2"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-Xpfyi1">$249.00</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-6GDZit","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
<div class="guten-element gutenverse-text-editor guten-6GDZit"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-SEYXqO","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="SEYXqO"><section class="wp-block-gutenverse-section guten-element guten-section guten-SEYXqO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-A8xNl0","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-A8xNl0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="A8xNl0"><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-X4qrIe","title":"","starIcon":"default","rating":"5","total":"5","iconColorMarked":{"type":"variable","id":"secondary"},"iconColorUnmarked":{"type":"variable","id":"fifth"}} -->
<div class="guten-element guten-star-rating guten-X4qrIe"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-AOZMVp","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-AOZMVp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AOZMVp"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-kxAcJY","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-2"},"hoverTextColor":{"type":"variable","id":"ninth"}} -->
<div class="guten-element guten-button-wrapper guten-kxAcJY"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-DEa1DZ","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DEa1DZ animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DEa1DZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-tn2cFs","imgSrc":{"media":{"imageId":287,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":225,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com-300x225.webp","orientation":"landscape"},"large":{"height":768,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com-1024x768.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com.webp","height":1920,"width":2560,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"352","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"233","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-tn2cFs"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com.webp" height="1920" width="2560"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-7k9VNZ","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="7k9VNZ"><section class="wp-block-gutenverse-section guten-element guten-section guten-7k9VNZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-qgnw1g","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qgnw1g"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qgnw1g"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-mO6Lqt","type":6,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-mO6Lqt">Gili Meno, NTB</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-pQncM1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pQncM1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pQncM1"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-X4Wxn6","type":6,"textAlign":{"Tablet":"center","Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h4-style-2"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-X4Wxn6">$299.00</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-S4ExAX","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"40"}}}} -->
<div class="guten-element gutenverse-text-editor guten-S4ExAX"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-0Remgi","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="0Remgi"><section class="wp-block-gutenverse-section guten-element guten-section guten-0Remgi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-OPYblc","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OPYblc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OPYblc"><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-zAPoeF","title":"","starIcon":"default","rating":"5","total":"5","iconColorMarked":{"type":"variable","id":"secondary"},"iconColorUnmarked":{"type":"variable","id":"fifth"}} -->
<div class="guten-element guten-star-rating guten-zAPoeF"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-QKRp5e","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QKRp5e"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QKRp5e"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-toCluG","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-2"},"hoverTextColor":{"type":"variable","id":"ninth"}} -->
<div class="guten-element guten-button-wrapper guten-toCluG"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-uhvBAf","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-uhvBAf animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="uhvBAf"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-gGh3tX","imgSrc":{"media":{"imageId":289,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":178,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com-300x178.webp","orientation":"landscape"},"large":{"height":609,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com-1024x609.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com.webp","height":1142,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"352","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"233","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-gGh3tX"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com.webp" height="1142" width="1920"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-VJoH1F","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="VJoH1F"><section class="wp-block-gutenverse-section guten-element guten-section guten-VJoH1F layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-BIWISW","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-BIWISW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BIWISW"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q7y6Mz","type":6,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-q7y6Mz">Bromo, Java</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-vnYmId","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vnYmId"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vnYmId"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-T8XXwJ","type":6,"textAlign":{"Tablet":"center","Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h4-style-2"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-T8XXwJ">$199.00</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-N2NPs9","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
<div class="guten-element gutenverse-text-editor guten-N2NPs9"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-cle9by","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="cle9by"><section class="wp-block-gutenverse-section guten-element guten-section guten-cle9by layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-AAKvmC","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-AAKvmC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AAKvmC"><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-cYY9o5","title":"","starIcon":"default","rating":"5","total":"5","iconColorMarked":{"type":"variable","id":"secondary"},"iconColorUnmarked":{"type":"variable","id":"fifth"}} -->
<div class="guten-element guten-star-rating guten-cYY9o5"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-HlR4fx","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HlR4fx"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HlR4fx"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-iBeSY7","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-2"},"hoverTextColor":{"type":"variable","id":"ninth"}} -->
<div class="guten-element guten-button-wrapper guten-iBeSY7"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
