<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"elementId":"guten-8kbaD8","background":{"type":"default","image":{"Desktop":{"id":32,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-sand-ocean-1200073-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"eighth"}},"opacity":"0.23","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-90","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"270","bottom":"250"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"140","bottom":"200"}}},"zIndex":{"Desktop":"1"},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="8kbaD8"><section class="wp-block-gutenverse-section guten-element guten-section guten-8kbaD8 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-UyWHwF","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-UyWHwF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UyWHwF"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h3-style-2","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"24"}},"weight":"600","spacing":{"Desktop":"0.075"},"transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-1","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"-1"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-8","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-q3mXI6 animated guten-element-hide desktop-fadeInUp">welcome to travey</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-oSnOnu","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"h1-style-2","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"px","point":"56"},"Mobile":{"unit":"px","point":"32"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"600"},"border":{"radius":{"Tablet":{}}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"20","left":"20","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-oSnOnu animated guten-element-hide desktop-fadeInUp">best way to find your dream place</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-g4Ps8x","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"tenth"},"typography":{"type":"variable","id":"h1-style-1","font":{"label":"Oswald","value":"Oswald","type":"google"},"size":{"Desktop":{"unit":"px","point":"200"},"Tablet":{"unit":"px","point":"152"},"Mobile":{"unit":"px","point":"76"}},"lineHeight":{"Desktop":{"unit":"px","point":"200"},"Tablet":{"unit":"px","point":"152"},"Mobile":{"unit":"px","point":"76"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-227","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-195"}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"-102"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":""}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-g4Ps8x animated guten-element-hide desktop-fadeInUp">travey</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-eMzUe0","content":"Discover Now","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-1","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"transform":"uppercase","spacing":{"Desktop":"0.075"},"weight":"600"},"hoverTextColor":{"type":"variable","id":"ninth"}} -->
<div class="guten-element guten-button-wrapper guten-eMzUe0"><a class="guten-button animated guten-element-hide desktop-fadeInUp guten-button-sm" href="#"><span>Discover Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
