<?php
/**
 * Gutenverse About Section 4 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 4', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"elementId":"guten-jE5fRc","background":{"type":"default","color":{"type":"variable","id":"ninth"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="jE5fRc"><section class="wp-block-gutenverse-section guten-element guten-section guten-jE5fRc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-KhvMhz","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KhvMhz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KhvMhz"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-oCEhrG","background":{"type":"default","color":""},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="oCEhrG"><section class="wp-block-gutenverse-section guten-element guten-section guten-oCEhrG layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Ljnylt","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Ljnylt"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Ljnylt"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Hs9SBQ","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-style-2"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-Hs9SBQ animated guten-element-hide desktop-fadeInUp">Travel Agents</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-gh5597","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"forth"},"typography":{"type":"variable","id":"h1-style-3"},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-8","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"-90"}},"Mobile":{"unit":"px","dimension":{"top":"-57"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-gh5597 animated guten-element-hide desktop-fadeInUp">guide</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-g9rPeG","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-10","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"27","bottom":"0","left":"27"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-g9rPeG animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-3FX1Y1","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":[]},"padding":{"Desktop":{},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="3FX1Y1"><section class="wp-block-gutenverse-section guten-element guten-section guten-3FX1Y1 animated guten-element-hide slow desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-lSYSih","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lSYSih animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lSYSih"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-sncPyv","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":203,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/person-sky-railway-photography-morning-1270261-pxhere.com.webp"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":[]},"profileBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"222","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"353","unit":"px"}},"imgHeight":{"Desktop":{"point":"347","unit":"px"},"Tablet":{"point":"218","unit":"px"},"Mobile":{"point":"275","unit":"px"}},"hoverPadding":{"Desktop":{}},"nameSpace":{"Desktop":"0"},"jobSpace":{"Desktop":"0"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-sncPyv"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( TRAVEY_URI ) . 'assets/img/person-sky-railway-photography-morning-1270261-pxhere.com.webp" alt=""/><div class="profile-body center"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-LvGJKL","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"ninth"},"bgColor":{"type":"variable","id":"secondary"},"hoverIconColor":{"type":"variable","id":"secondary"},"hoverBgColor":{"type":"variable","id":"ninth"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-LvGJKL circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-lxf3Sv"} -->
<div class="guten-element guten-social-icon guten-lxf3Sv facebook"><a id="guten-lxf3Sv"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-jSL3O7"} -->
<div class="guten-element guten-social-icon guten-jSL3O7 twitter"><a id="guten-jSL3O7"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-hQNLcK"} -->
<div class="guten-element guten-social-icon guten-hQNLcK instagram"><a id="guten-hQNLcK"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-gWRnWm","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="gWRnWm"><section class="wp-block-gutenverse-section guten-element guten-section guten-gWRnWm layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-lyMryZ","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":225,"g":225,"b":225,"a":0.82}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30","left":"30","top":"-40"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15"}},"Tablet":{}},"zIndex":{"Desktop":"2"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lyMryZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lyMryZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SY5YbC","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-SY5YbC">Rubie Talley</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-dA9BFB","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
<div class="guten-element gutenverse-text-editor guten-dA9BFB"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Tour Guide</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-qYSrT3","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qYSrT3 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qYSrT3"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-UQG5DL","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":200,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-tree-nature-forest-path-grass-1412616-pxhere.com.webp"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"222","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"353","unit":"px"}},"imgHeight":{"Desktop":{"point":"347","unit":"px"},"Tablet":{"point":"218","unit":"px"},"Mobile":{"point":"275","unit":"px"}},"hoverPadding":{"Desktop":{}},"nameSpace":{"Desktop":"0"},"jobSpace":{"Desktop":"0"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-UQG5DL"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-tree-nature-forest-path-grass-1412616-pxhere.com.webp" alt=""/><div class="profile-body center"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-QF1uzn","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"ninth"},"bgColor":{"type":"variable","id":"secondary"},"hoverIconColor":{"type":"variable","id":"secondary"},"hoverBgColor":{"type":"variable","id":"ninth"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-QF1uzn circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-AAZfjD"} -->
<div class="guten-element guten-social-icon guten-AAZfjD facebook"><a id="guten-AAZfjD"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-2uIgLK"} -->
<div class="guten-element guten-social-icon guten-2uIgLK twitter"><a id="guten-2uIgLK"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-zCG93O"} -->
<div class="guten-element guten-social-icon guten-zCG93O instagram"><a id="guten-zCG93O"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-ju2DGe","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="ju2DGe"><section class="wp-block-gutenverse-section guten-element guten-section guten-ju2DGe layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-4P7cja","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":225,"g":225,"b":225,"a":0.82}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30","left":"30","top":"-40"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15"}},"Tablet":{}},"zIndex":{"Desktop":"2"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4P7cja"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="4P7cja"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-gBs5QI","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-gBs5QI">Marcel Frame</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-s7zFDQ","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"}} -->
<div class="guten-element gutenverse-text-editor guten-s7zFDQ"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Tour Guide</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-AY11zD","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{},"Mobile":[],"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-AY11zD animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AY11zD"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-byy5Hu","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":201,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/nature-walking-person-mountain-snow-cold-848729-pxhere.com.webp"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"222","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"353","unit":"px"}},"imgHeight":{"Desktop":{"point":"347","unit":"px"},"Tablet":{"point":"218","unit":"px"},"Mobile":{"point":"275","unit":"px"}},"hoverPadding":{"Desktop":{}},"nameSpace":{"Desktop":"0"},"jobSpace":{"Desktop":"0"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-byy5Hu"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( TRAVEY_URI ) . 'assets/img/nature-walking-person-mountain-snow-cold-848729-pxhere.com.webp" alt=""/><div class="profile-body center"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-kxzKqz","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"ninth"},"bgColor":{"type":"variable","id":"secondary"},"hoverIconColor":{"r":242,"g":139,"b":56,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-kxzKqz circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-H6WCPi"} -->
<div class="guten-element guten-social-icon guten-H6WCPi facebook"><a id="guten-H6WCPi"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-sDajN9"} -->
<div class="guten-element guten-social-icon guten-sDajN9 twitter"><a id="guten-sDajN9"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-w5LuFQ"} -->
<div class="guten-element guten-social-icon guten-w5LuFQ instagram"><a id="guten-w5LuFQ"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-dx9dqs","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="dx9dqs"><section class="wp-block-gutenverse-section guten-element guten-section guten-dx9dqs layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-RYIJsX","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":225,"g":225,"b":225,"a":0.82}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30","left":"30","top":"-40"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15"}},"Tablet":{}},"zIndex":{"Desktop":"2"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RYIJsX"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RYIJsX"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-BoHVgq","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h4-style-1"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-BoHVgq">Dina Driscoll</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-OshQw3","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-font"}} -->
<div class="guten-element gutenverse-text-editor guten-OshQw3"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Tour Guide</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
