<?php
/**
 * Gutenverse Home Section 5 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 5', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-yYySSj","background":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="yYySSj"><section class="wp-block-gutenverse-section guten-element guten-section guten-yYySSj layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-jp5AkC","background":{"type":"gradient","color":{"r":255,"g":255,"b":255,"a":1},"gradientColor":[{"color":"rgba(21, 43, 90, 1)","active":false,"opacity":1,"id":4,"offset":"0.896"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":2,"offset":"0.898"}]},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"flex-end"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"15","bottom":"18","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"80","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}},"zIndex":{"Tablet":""},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jp5AkC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jp5AkC"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-kYJoXI","textAlign":{"Tablet":"center"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"h2-style-2"},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{},"Tablet":{}},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-kYJoXI animated guten-element-hide desktop-fadeInLeft">Take a Break &amp; Checkout<br>Our Top Destinations</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-IoJQQx","type":1,"textAlign":{"Tablet":"center"},"color":{"type":"variable","id":"tenth"},"typography":{"type":"variable","id":"h1-style-3"},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-18","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"-106"}},"Mobile":{"unit":"px","dimension":{"top":"-74"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"positioningType":{"Desktop":"default","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-IoJQQx animated guten-element-hide desktop-fadeInLeft">Popular</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-xoKvTV","alignment":{"Tablet":"center"},"textColor":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"text-editor-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"30","bottom":"","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"positioningType":{"Desktop":"default","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-xoKvTV animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-dBZAAS","content":"explore more","buttonWidth":{"Desktop":"","Tablet":""},"alignButton":{"Desktop":"left","Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Tablet":{},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"ninth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":""}},"Tablet":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"40"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"ninth"},"typography":{"type":"variable","id":"button-style-2"},"hoverTextColor":{"type":"variable","id":"primary"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-button-wrapper guten-dBZAAS"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>explore more</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-8nbEt0","background":{"type":"default","image":{"Desktop":{"id":58,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-nature-rock-105297-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":""},"backgroundHover":{},"backgroundOverlay":{"type":"default","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.820"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":2,"offset":"0.824"}]},"opacity":"1","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-46"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"100"}}},"zIndex":{"Tablet":"2"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8nbEt0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8nbEt0"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-Mo6zNy","icon":"gtn gtn-play-button","iconAlign":{"Desktop":"center"},"iconColorOne":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"20"},"iconColorTwo":{"type":"variable","id":"ninth"},"iconColorHoverOne":{"type":"variable","id":"ninth"},"iconColorHoverTwo":{"type":"variable","id":"secondary"},"iconShape":"circle","margin":{"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Tablet":{"unit":"%","dimension":{"top":"20","bottom":"20"}}},"zIndex":{"Tablet":""}} -->
<div class="wp-block-gutenverse-icon guten-element guten-Mo6zNy guten-icon"><span class="guten-icon-wrapper circle stacked"><i class="gtn gtn-play-button"></i></span></div>
<!-- /wp:gutenverse/icon --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
