<?php
/**
 * Gutenverse FAQ Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Section 2', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-y9BWoM","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="y9BWoM"><section class="wp-block-gutenverse-section guten-element guten-section guten-y9BWoM layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-moSZfz","order":{"Tablet":2},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-moSZfz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="moSZfz"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-2YoWDZ","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="2YoWDZ"><section class="wp-block-gutenverse-section guten-element guten-section guten-2YoWDZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-BeYhX1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-BeYhX1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BeYhX1"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-e60la4","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h3-style-2"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":{},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-e60la4 animated guten-element-hide desktop-fadeInLeft">Payment</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/accordions {"elementId":"guten-8ksNeS","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right","iconColor":{"type":"variable","id":"secondary"},"iconActiveColor":{"type":"variable","id":"secondary"},"titleBackgroundColor":{"type":"variable","id":"ninth"},"titleTextColor":{"type":"variable","id":"primary"},"titleActiveColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"accordion-title-font"},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"15"}},"Tablet":{},"Mobile":{}},"contentBackgroundColor":{"type":"variable","id":"ninth"},"contentTextColor":{"type":"variable","id":"fifth"},"contentTypography":{"type":"variable","id":"text-editor-font"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"40"}},"Tablet":{},"Mobile":{}},"accordionBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{}},"all":{"type":"none","color":""}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"vertical":"0","blur":"0","position":"outline","color":"","spread":"0","horizontal":"0"},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"accordionBorderActive":{"radius":{"Desktop":{}}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":""}},"Tablet":{}},"contentBackgroundColorActive":{"type":"variable","id":"ninth"},"contentTextColorActive":{"type":"variable","id":"fifth"},"contentBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"10"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}},"titleBackgroundActiveColor":{"type":"variable","id":"ninth"},"titleBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"third"}}}} -->
<div class="guten-element guten-accordions guten-8ksNeS animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/accordion {"elementId":"guten-aVZHc2","first":true,"iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item active"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">What are acceptable payment methods?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-rdPI7d","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">How Much does it cost to do a private tour?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-A7PDpv","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">How can I pay for my booking?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ICqO8T","order":{"Tablet":1},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ICqO8T"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ICqO8T"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-abAHAF","imgSrc":{"media":{"imageId":195,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":199,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com-300x199.webp","orientation":"landscape"},"large":{"height":680,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com-1024x680.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com.webp","height":1275,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"border":{"radius":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"borderHover":{"radius":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"left":"0"}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-abAHAF animated guten-element-hide desktop-fadeInRight"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com.webp" height="1275" width="1920"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
