<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse Project FAQ', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-PjDcPz","background":{},"backgroundHover":{},"border":{"radius":{"Desktop":{}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"20","bottom":"100","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"","bottom":"60","left":""}},"Mobile":{"unit":"px","dimension":{"top":"50","bottom":"50"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="PjDcPz"><section class="wp-block-gutenverse-section guten-element guten-section guten-PjDcPz layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-7xfLYd","order":{"Tablet":2},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"flex-start"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-7xfLYd"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7xfLYd"><div class="guten-column-wrapper"><!-- wp:gutenverse/accordions {"elementId":"guten-st6oyD","iconPosition":"right","iconColor":{"type":"variable","id":"primary"},"iconActiveColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"15"},"titleTag":"h6","titleTextColor":{"type":"variable","id":"primary"},"titleActiveColor":{"type":"variable","id":"secondary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{},"Tablet":{}},"contentTextColor":{"type":"variable","id":"fourth"},"contentTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}},"Tablet":{}},"accordionBorder":{"radius":{"Desktop":{},"Mobile":{}},"all":{"type":"none"}},"titleBorder":{"radius":{"Desktop":{},"Mobile":{}}},"contentBorder":{"radius":{"Desktop":{}}},"border":{"radius":{"Desktop":{}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{}},"contentTextColorActive":{"type":"variable","id":"fourth"},"contentBorderActive":{"radius":{"Desktop":{}}},"titleBorderActive":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"r":220,"g":220,"b":220,"a":1}}}} -->
<div class="guten-element guten-accordions guten-st6oyD animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/accordion {"elementId":"guten-704na7","first":true,"iconPosition":"right","titleTag":"h6"} -->
<div class="accordion-item active"><div class="accordion-heading"><h6 class="accordion-text">How long does it take to build a website?</h6><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-minus"></i></span><span class="accordion-icon-closed"><i class="fas fa-plus"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes nascetur.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-L9Tqat","iconPosition":"right","titleTag":"h6"} -->
<div class="accordion-item"><div class="accordion-heading"><h6 class="accordion-text">Do you redesign existing websites?</h6><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-minus"></i></span><span class="accordion-icon-closed"><i class="fas fa-plus"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes nascetur.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-d8C7aE","iconPosition":"right","titleTag":"h6"} -->
<div class="accordion-item"><div class="accordion-heading"><h6 class="accordion-text">How do you evaluate a web agency</h6><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-minus"></i></span><span class="accordion-icon-closed"><i class="fas fa-plus"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes nascetur.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-XdQ9Qn","iconPosition":"right","titleTag":"h6"} -->
<div class="accordion-item"><div class="accordion-heading"><h6 class="accordion-text">What makes a good web design agency?</h6><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-minus"></i></span><span class="accordion-icon-closed"><i class="fas fa-plus"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes nascetur.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ZfIypl","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"flex-start"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"30","right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"50","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"40","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ZfIypl"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ZfIypl"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-Lm8t8p","alignText":{"Desktop":"flex-start"},"subTag":"h4","text":"General ","focusText":"Question","subText":"FAQ","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","bottom":""}},"Tablet":{}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":""}},"Tablet":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.537"},{"color":"rgba(234, 186, 255, 1)","opacity":1,"active":true,"id":2,"offset":"0.539"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"secondary"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{},"Tablet":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<div class="guten-element guten-advanced-heading guten-Lm8t8p animated guten-element-hide desktop-fadeInRight"><h4 class="heading-subtitle">FAQ</h4><div class="heading-section "><h2 class="heading-title">General <span class="heading-focus">Question</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-07shGZ","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"80","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"200","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-07shGZ animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor massa.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-V01ou7","content":"View More","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":{},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}}},"showIcon":true,"icon":"gtn gtn-long-arrow-alt-right-solid","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"},"right":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-V01ou7"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>View More</span><i class="fa-lg gtn gtn-long-arrow-alt-right-solid"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
