<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse Home Client Logos', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-PXnwUr","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"50","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="PXnwUr"><section class="wp-block-gutenverse-section guten-element guten-section guten-PXnwUr layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":26,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-G1MRmF","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"padding":{"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-G1MRmF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="G1MRmF"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-pkxPSr","alignText":{"Mobile":"center"},"titleTag":"h3","text":"Trusted by ","focusText":"500+ Companies","subText":"","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h3-bold-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subMargin":{"Desktop":{}},"subPadding":{"Desktop":{}},"margin":{"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{}},"padding":{"Tablet":{},"Mobile":{},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-advanced-heading guten-pkxPSr animated guten-element-hide desktop-fadeInLeft"><div class="heading-section "><h3 class="heading-title">Trusted by <span class="heading-focus">500+ Companies</span></h3></div><span class="heading-subtitle"></span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":74,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-FeY7Qm","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-FeY7Qm"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FeY7Qm"><div class="guten-column-wrapper"><!-- wp:gutenverse/logo-slider {"elementId":"guten-tHeFaV","logos":[{"title":"One","_key":"bpyY5w","src":{"id":124,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/financio-client-logo-1.webp"}},{"title":"Two","_key":"94trKw","src":{"id":125,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/Renovater-client-logo.webp"}},{"title":"Three","_key":"hYIa1Z","src":{"id":126,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/Intrace-client-logo.webp"}},{"title":"Four","_key":"POuiik","src":{"id":127,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/Startupzy-logo-client-1.webp"}}],"imagePadding":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":"30","top":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"imageMargin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"imageHoverPadding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"imageHoverMargin":{"Tablet":{},"Mobile":{}},"imageBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"imageBorderHover":{"radius":{"Tablet":{},"Mobile":{}}},"spacing":{"Desktop":"30","Tablet":"0","Mobile":"20"},"itemShowed":{"Desktop":"4","Tablet":"3","Mobile":"2"},"loop":true,"dotsRadius":{"Tablet":{},"Desktop":{}},"arrowPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"arrowMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"arrowOpacity":{"Desktop":""},"arrowBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"opacity":"0.7","margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-tHeFaV animated guten-element-hide desktop-fadeInRight arrow-bottom-edge"><div class="client-list"><div id="guten-tHeFaV" class="swiper-container" data-loop="true" data-autoplay="false" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:20,&quot;slidesPerView&quot;:2},&quot;768&quot;:{&quot;spaceBetween&quot;:0,&quot;slidesPerView&quot;:3},&quot;1024&quot;:{&quot;spaceBetween&quot;:30,&quot;slidesPerView&quot;:4}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/financio-client-logo-1.webp" alt="One"/><img class="hover-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/financio-client-logo-1.webp" alt="One"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/Renovater-client-logo.webp" alt="Two"/><img class="hover-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/Renovater-client-logo.webp" alt="Two"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/Intrace-client-logo.webp" alt="Three"/><img class="hover-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/Intrace-client-logo.webp" alt="Three"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/Startupzy-logo-client-1.webp" alt="Four"/><img class="hover-image" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/Startupzy-logo-client-1.webp" alt="Four"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
