<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse Team Details', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-ZRchDF","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"30","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"20","bottom":"30","left":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="ZRchDF"><section class="wp-block-gutenverse-section guten-element guten-section guten-ZRchDF layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-sRwJFz","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sRwJFz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sRwJFz"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-jXqRWF","alignText":{"Desktop":"center"},"subTag":"h4","text":"Best Team ","focusText":"Partner","subText":"My Partner","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.541"},{"color":"rgba(234, 186, 255, 1)","opacity":1,"active":true,"id":2,"offset":"0.543"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"secondary"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<div class="guten-element guten-advanced-heading guten-jXqRWF animated guten-element-hide desktop-fadeInDown"><h4 class="heading-subtitle">My Partner</h4><div class="heading-section "><h2 class="heading-title">Best Team <span class="heading-focus">Partner</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"540"},"isChild":true,"height":{},"gap":"no","elementId":"guten-QqlfHt","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="QqlfHt"><section class="wp-block-gutenverse-section guten-element guten-section guten-QqlfHt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Pz89H5","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Pz89H5"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Pz89H5"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-5HmVlm","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-5HmVlm animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor massa cum sociis natoque.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-FUKWu1","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"","right":"","left":""}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="FUKWu1"><section class="wp-block-gutenverse-section guten-element guten-section guten-FUKWu1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":33.33},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-nS56qW","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nS56qW animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nS56qW"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-8Q4xKr","profileType":"overlay","overlayType":"scale","overlayPosition":"center","src":{"id":1166,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/man-tree-plant-street-house-flower-511611-pxhere.com-team.webp"},"nameTag":"h4","name":"","job":"","alignment":{"Desktop":"center"},"profilePadding":{"Desktop":{}},"detailsPadding":{"Desktop":{}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-55"}}},"padding":{"Desktop":{}},"hoverPadding":{"Desktop":{}},"hoverBgColor":{"r":1,"g":1,"b":29,"a":0.6},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-8Q4xKr"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="' . esc_url( VORFOLIO_URI ) . 'assets/img/man-tree-plant-street-house-flower-511611-pxhere.com-team.webp" alt=""/><div class="profile-body center"><h4 class="profile-title "></h4><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-zUh3RE","iconSize":{"Desktop":{"point":"20","unit":"px"}},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"secondary"},"iconBorder":{"radius":{"Desktop":{}}},"itemPadding":{"Desktop":{}},"hoverIconColor":{"type":"variable","id":"secondary"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-zUh3RE circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-mbllOn"} -->
<div class="guten-element guten-social-icon guten-mbllOn facebook"><a id="guten-mbllOn" href="#"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-IjxYvX"} -->
<div class="guten-element guten-social-icon guten-IjxYvX twitter"><a id="guten-IjxYvX" href="#"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-lO86O6"} -->
<div class="guten-element guten-social-icon guten-lO86O6 instagram"><a id="guten-lO86O6" href="#"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-JDDf00","alignText":{"Desktop":"center"},"titleTag":"h3","text":"Erick Doe","focusText":"","subText":"Graphic Designer","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{},"Tablet":{}},"focusMargin":{"Desktop":{}},"focusPadding":{"Desktop":{}},"subColor":{"type":"variable","id":"fourth"},"subTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"subMargin":{"Desktop":{},"Tablet":{}},"subPadding":{"Desktop":{},"Tablet":{}},"background":{"type":"default","gradientColor":[{"color":"rgba(67, 7, 81, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(9, 35, 80, 1)","active":true,"opacity":1,"id":2,"offset":"0.514"}],"gradientType":"radial","gradientRadial":"top right","color":{"type":"variable","id":"eleventh"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30","left":"30","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Tablet":{}},"zIndex":{"Desktop":"1"}} -->
<div class="guten-element guten-advanced-heading guten-JDDf00"><div class="heading-section "><h3 class="heading-title">Erick Doe<span class="heading-focus"></span></h3></div><span class="heading-subtitle">Graphic Designer</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":33.33},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-GkLEvV","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GkLEvV animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GkLEvV"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-XTiaAy","profileType":"overlay","overlayType":"scale","overlayPosition":"center","src":{"id":1167,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/man-person-looking-dark-male-young-718764-pxhere.webp"},"nameTag":"h4","name":"","job":"","alignment":{"Desktop":"center"},"profilePadding":{"Desktop":{}},"detailsPadding":{"Desktop":{}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-55"}}},"padding":{"Desktop":{}},"hoverPadding":{"Desktop":{}},"hoverBgColor":{"r":1,"g":1,"b":29,"a":0.6},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-XTiaAy"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="' . esc_url( VORFOLIO_URI ) . 'assets/img/man-person-looking-dark-male-young-718764-pxhere.webp" alt=""/><div class="profile-body center"><h4 class="profile-title "></h4><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-2Nzw37","iconSize":{"Desktop":{"point":"20","unit":"px"}},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"secondary"},"hoverIconColor":{"type":"variable","id":"secondary"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-2Nzw37 circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-ivMkAG"} -->
<div class="guten-element guten-social-icon guten-ivMkAG facebook"><a id="guten-ivMkAG" href="#"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-XwQGIQ"} -->
<div class="guten-element guten-social-icon guten-XwQGIQ twitter"><a id="guten-XwQGIQ" href="#"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-IiKqTY"} -->
<div class="guten-element guten-social-icon guten-IiKqTY instagram"><a id="guten-IiKqTY" href="#"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-VkrTb8","alignText":{"Desktop":"center"},"titleTag":"h3","text":"Fred William","focusText":"","subText":"Logo Designer","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{},"Mobile":{}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{}},"focusMargin":{"Desktop":{}},"focusPadding":{"Desktop":{}},"subColor":{"type":"variable","id":"fourth"},"subTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"subMargin":{"Desktop":{},"Tablet":{}},"subPadding":{"Desktop":{},"Tablet":{}},"background":{"type":"default","gradientColor":[{"color":"rgba(67, 7, 81, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(9, 35, 80, 1)","active":true,"opacity":1,"id":2,"offset":"0.514"}],"gradientType":"radial","gradientRadial":"top right","color":{"type":"variable","id":"eleventh"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Tablet":{}},"zIndex":{"Desktop":"1"}} -->
<div class="guten-element guten-advanced-heading guten-VkrTb8"><div class="heading-section "><h3 class="heading-title">Fred William<span class="heading-focus"></span></h3></div><span class="heading-subtitle">Logo Designer</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-a3sgDH","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-a3sgDH animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="a3sgDH"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-ABo01V","profileType":"overlay","overlayType":"scale","overlayPosition":"center","src":{"id":1168,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/man-person-people-hair-white-photography-601668-pxhere.com.webp"},"nameTag":"h4","name":"","job":"","alignment":{"Desktop":"center"},"profilePadding":{"Desktop":{}},"detailsPadding":{"Desktop":{}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-55"}}},"padding":{"Desktop":{}},"hoverPadding":{"Desktop":{}},"hoverBgColor":{"r":1,"g":1,"b":29,"a":0.6},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-ABo01V"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="' . esc_url( VORFOLIO_URI ) . 'assets/img/man-person-people-hair-white-photography-601668-pxhere.com.webp" alt=""/><div class="profile-body center"><h4 class="profile-title "></h4><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-Oe01jV","iconSize":{"Desktop":{"point":"20","unit":"px"}},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"secondary"},"hoverIconColor":{"type":"variable","id":"secondary"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-Oe01jV circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-IByvFK"} -->
<div class="guten-element guten-social-icon guten-IByvFK facebook"><a id="guten-IByvFK" href="#"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-CTFbw8"} -->
<div class="guten-element guten-social-icon guten-CTFbw8 twitter"><a id="guten-CTFbw8" href="#"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-eiXkEM"} -->
<div class="guten-element guten-social-icon guten-eiXkEM instagram"><a id="guten-eiXkEM" href="#"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-3OKDar","alignText":{"Desktop":"center"},"titleTag":"h3","text":"Brian Sign","focusText":"","subText":"Web Designer","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{},"Mobile":{}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{},"Tablet":{}},"focusMargin":{"Desktop":{}},"focusPadding":{"Desktop":{}},"subColor":{"type":"variable","id":"fourth"},"subTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"subMargin":{"Desktop":{},"Tablet":{}},"subPadding":{"Desktop":{},"Tablet":{}},"background":{"type":"default","gradientColor":[{"color":"rgba(67, 7, 81, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(9, 35, 80, 1)","active":true,"opacity":1,"id":2,"offset":"0.514"}],"gradientType":"radial","gradientRadial":"top right","color":{"type":"variable","id":"eleventh"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Tablet":{}},"zIndex":{"Desktop":"1"}} -->
<div class="guten-element guten-advanced-heading guten-3OKDar"><div class="heading-section "><h3 class="heading-title">Brian Sign<span class="heading-focus"></span></h3></div><span class="heading-subtitle">Web Designer</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
