<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Form', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1140"},"height":{},"gap":"no","elementId":"guten-GpF4nm","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"50","bottom":"40","right":"20","left":"20"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="GpF4nm"><section class="wp-block-gutenverse-section guten-element guten-section guten-GpF4nm layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-HRYM4u","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HRYM4u"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HRYM4u"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-PM0amU","alignText":{"Desktop":"flex-start"},"subTag":"h4","text":"Get In ","focusText":"Touch","subText":"Contact Us","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.537"},{"color":"rgba(234, 186, 255, 1)","opacity":1,"active":true,"id":2,"offset":"0.539"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"secondary"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":""}} -->
<div class="guten-element guten-advanced-heading guten-PM0amU animated guten-element-hide desktop-fadeInLeft"><h4 class="heading-subtitle">Contact Us</h4><div class="heading-section "><h2 class="heading-title">Get In <span class="heading-focus">Touch</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-LV2b3B","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"30","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"80","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-LV2b3B animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor massa.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-0YW5s2","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="0YW5s2"><section class="wp-block-gutenverse-section guten-element guten-section guten-0YW5s2 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":52,"Mobile":null},"elementId":"guten-6p5FOv","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6p5FOv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6p5FOv"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-2xfMhz","title":"Office Location","titleTag":"h3","description":"Jl. Raya Kuta No. 88 Badung - Bali","icon":"gtn gtn-map-marked-alt-solid","iconSize":{"Desktop":"29"},"iconBoxOverlayDirection":"right","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"iconColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"secondary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"25","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":""}},"Tablet":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"-70"}},"Mobile":{},"Tablet":{}},"descColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-2xfMhz animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-right"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-map-marked-alt-solid"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Office Location</h3><p class="icon-box-description">Jl. Raya Kuta No. 88 Badung - Bali</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":48,"Mobile":null},"elementId":"guten-TY1WMN","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TY1WMN"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TY1WMN"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-pRz9Na","title":"Email","titleTag":"h3","description":"vorfolio@domain.com","icon":"gtn gtn-envelope","iconSize":{"Desktop":"29"},"iconBoxOverlayDirection":"right","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"iconColor":{"type":"variable","id":"secondary"},"iconBgColor":{"type":"variable","id":"eleventh"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"","top":""}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"25","left":"5"}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"20"}},"Tablet":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"-70"}},"Mobile":{},"Tablet":{}},"descColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-pRz9Na animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-right"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-envelope"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Email</h3><p class="icon-box-description">vorfolio@domain.com</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-6OPN0i","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="6OPN0i"><section class="wp-block-gutenverse-section guten-element guten-section guten-6OPN0i layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":52,"Mobile":null},"elementId":"guten-5ow0PU","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"15","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5ow0PU"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5ow0PU"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-xvmrQh","title":"Opening Hours","titleTag":"h3","description":"Monday - Friday : 09 AM - 07 PM","icon":"gtn gtn-clock-solid","iconSize":{"Desktop":"29"},"iconBoxOverlayDirection":"right","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"containerPaddingHover":{"Desktop":{}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"containerBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Mobile":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"iconColor":{"type":"variable","id":"secondary"},"iconBgColor":{"type":"variable","id":"eleventh"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"25","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"-70"}},"Mobile":{},"Tablet":{}},"descColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"800"}} -->
<div class="guten-element guten-xvmrQh animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-right"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-clock-solid"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Opening Hours</h3><p class="icon-box-description">Monday - Friday : 09 AM - 07 PM</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":48},"elementId":"guten-yQQzTC","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-yQQzTC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="yQQzTC"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-IGWQRi","title":"Give Us A Call","titleTag":"h3","description":"(+62) 361 7892456","icon":"gtn gtn-phone-solid","iconSize":{"Desktop":"29"},"iconBoxOverlayDirection":"right","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":{}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"containerBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Mobile":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"iconColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"secondary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"25","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":{}},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"-70"}},"Mobile":{},"Tablet":{}},"descColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-IGWQRi animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-right"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone-solid"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Give Us A Call</h3><p class="icon-box-description">(+62) 361 7892456</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-eVe4dM","background":{"type":"default","color":{"type":"variable","id":"eleventh"}},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"10","right":"30","bottom":"30","left":"30"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eVe4dM animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="eVe4dM"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-GeR05R","formId":{"label":"Form Contact","value":338},"hideAfterSubmit":false,"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]}} -->
<form style="display:none" class="guten-element guten-form-builder guten-GeR05R" data-form-id="338" data-hide-after="false"><!-- wp:gutenverse/section {"width":{"Desktop":"1140"},"isChild":true,"height":{},"gap":"no","elementId":"guten-hwC8Lk","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="hwC8Lk"><section class="wp-block-gutenverse-section guten-element guten-section guten-hwC8Lk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-hTdIYs","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hTdIYs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hTdIYs"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-5vWky5","showLabel":false,"inputPlaceholder":"First Name","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":{}}},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{},"Mobile":{}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"20","right":"20"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":{},"Tablet":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"ninth"}},"inputTypography":{"type":"variable","id":"title-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"ninth"}}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-5vWky5 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="First Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-kEfpGR","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kEfpGR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="kEfpGR"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-QgMaRN","showLabel":false,"inputPlaceholder":"Last Name","showHelper":false,"border":{"radius":{"Desktop":{}}},"margin":{"Mobile":{}},"padding":{"Mobile":{}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"20","right":"20"}},"Tablet":{}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"ninth"}},"inputTypography":{"type":"variable","id":"title-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"ninth"}}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-QgMaRN hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Last Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":1170},"isChild":true,"height":{},"gap":"no","elementId":"guten-rJufvn","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":[]},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="rJufvn"><section class="wp-block-gutenverse-section guten-element guten-section guten-rJufvn layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-3nBUBZ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"","bottom":"","top":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3nBUBZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3nBUBZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-email {"elementId":"guten-QJbdoH","showLabel":false,"showHelper":false,"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"inputPlaceholder":"Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":{},"Tablet":{}},"inputMargin":{"Desktop":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"ninth"}},"inputTypography":{"type":"variable","id":"title-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"ninth"}}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBorderFocus":{"radius":{"Desktop":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-QJbdoH hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-6TRFpW","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6TRFpW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6TRFpW"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-Nqblcc","showLabel":false,"inputPlaceholder":"Subject","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"20","right":"20"}},"Mobile":{}},"inputMargin":{"Desktop":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"ninth"}},"inputTypography":{"type":"variable","id":"title-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"ninth"}}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBorderFocus":{"radius":{"Desktop":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-Nqblcc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-IYqA3y","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{},"Mobile":{}},"inputHeight":{"Desktop":"200"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":{}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"ninth"}},"inputTypography":{"type":"variable","id":"title-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"ninth"}}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-IYqA3y hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-07OW3E","content":"Send Message","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"icon":"gtn gtn-long-arrow-alt-right-solid","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"positioningType":{"Desktop":"default"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-07OW3E"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
