<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse Project Detail Description', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1140"},"height":{},"gap":"no","elementId":"guten-YjzKVX","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"30","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"20","bottom":"40","left":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="YjzKVX"><section class="wp-block-gutenverse-section guten-element guten-section guten-YjzKVX layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-6VOamG","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6VOamG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6VOamG"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-IIAx7t","alignText":{"Desktop":"flex-start"},"subTag":"h4","text":"Creative ","focusText":"Agency","subText":"UI / UX Design","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.537"},{"color":"rgba(234, 186, 255, 1)","opacity":1,"active":true,"id":2,"offset":"0.539"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"secondary"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="guten-element guten-advanced-heading guten-IIAx7t animated guten-element-hide desktop-fadeInLeft"><h4 class="heading-subtitle">UI / UX Design</h4><div class="heading-section "><h2 class="heading-title">Creative <span class="heading-focus">Agency</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/image {"elementId":"guten-zojNTd","imgSrc":{"media":{"imageId":1145,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/zeever-150x150.webp","orientation":"landscape"},"medium":{"height":225,"width":300,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/zeever-300x225.webp","orientation":"landscape"},"large":{"height":768,"width":1024,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/zeever-1024x768.webp","orientation":"landscape"},"full":{"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/zeever.webp","height":858,"width":1144,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"align":{"Desktop":"left"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-zojNTd animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/zeever.webp" height="858" width="1144"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-VCwnMY","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VCwnMY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VCwnMY"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-LV2b3B","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-LV2b3B animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean eget commodo ligula dolor. Cum sociis natoque penatibus et magnis dis parturient montes aenean leo ligula. </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-E3JeCp","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-E3JeCp animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140,"Mobile":""},"isChild":true,"height":{},"gap":"no","elementId":"guten-rH1DpL","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"right":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="rH1DpL"><section class="wp-block-gutenverse-section guten-element guten-section guten-rH1DpL layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-aCXtPT","background":{"type":"default","color":{"type":"variable","id":"eleventh"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"80","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"20","left":"40"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-aCXtPT animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="aCXtPT"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-hDmAHV","type":3,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h3-bold-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-hDmAHV">Project Information</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/divider {"elementId":"guten-hDIsM3","width":{"Desktop":"100"},"dividerColor":{"r":196,"g":198,"b":220,"a":1},"size":{"Desktop":"1"},"gap":{"Desktop":""},"dividerAlign":{"Desktop":"left"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-hDIsM3"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-8FncCc","alignText":{"Desktop":"flex-start"},"titleTag":"h5","text":"Client Name : ","focusText":"Zeever","subText":"","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"secondary"},"mainTypography":{"type":"variable","id":"h5-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h5-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"secondary"},"subTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{}},"subPadding":{"Desktop":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
<div class="guten-element guten-advanced-heading guten-8FncCc"><div class="heading-section "><h5 class="heading-title">Client Name : <span class="heading-focus">Zeever</span></h5></div><span class="heading-subtitle"></span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-PKiApy","alignText":{"Desktop":"flex-start"},"titleTag":"h5","text":"Date : ","focusText":"August 29th, 2022","subText":"","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"secondary"},"mainTypography":{"type":"variable","id":"h5-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h5-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"r":47,"g":108,"b":252,"a":1},"subTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{}},"subPadding":{"Desktop":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
<div class="guten-element guten-advanced-heading guten-PKiApy"><div class="heading-section "><h5 class="heading-title">Date : <span class="heading-focus">August 29th, 2022</span></h5></div><span class="heading-subtitle"></span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-LJTBGa","alignText":{"Desktop":"flex-start"},"titleTag":"h5","text":"Location : ","focusText":"Indonesia","subText":"","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"secondary"},"mainTypography":{"type":"variable","id":"h5-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h5-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"secondary"},"subTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{}},"subPadding":{"Desktop":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
<div class="guten-element guten-advanced-heading guten-LJTBGa"><div class="heading-section "><h5 class="heading-title">Location : <span class="heading-focus">Indonesia</span></h5></div><span class="heading-subtitle"></span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1140"},"height":{},"gap":"no","elementId":"guten-YriOQw","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"100","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"80","left":"20"}},"Mobile":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="YriOQw"><section class="wp-block-gutenverse-section guten-element guten-section guten-YriOQw layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-npEAyg","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"800"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-npEAyg animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="npEAyg"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-D1yHiP","type":3,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h3-bold-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-D1yHiP">How I Start This Project</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-pasJpt","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"columns":{"Desktop":"1","Tablet":""},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}}} -->
<div class="guten-element gutenverse-text-editor guten-pasJpt"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean sociis commodo ligula eget dolor. Cum natoque penatibus et magnis dis parturient montes aenean leo ligula.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-9XS8vu","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"columns":{"Desktop":"1","Tablet":""},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}}} -->
<div class="guten-element gutenverse-text-editor guten-9XS8vu"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Curabitur ullamcorper ultricies nisi nam eget dui etiam rhoncus.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-tv38qc","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1000"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tv38qc animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="tv38qc"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-nMMxXN","type":3,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h3-bold-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-nMMxXN">Challange On This Project</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-8QJDvW","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"secondary"},"textColor":{"type":"variable","id":"fourth"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{}}} -->
<div class="guten-element guten-icon-list guten-8QJDvW"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-AJ7lfP"} -->
<div class="guten-element guten-icon-list-item guten-AJ7lfP"><a id="guten-AJ7lfP"><i class="fas fa-check"></i><span class="list-text ">Vivamus elementum semper nisi.</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-8Hn9cZ"} -->
<div class="guten-element guten-icon-list-item guten-8Hn9cZ"><a id="guten-8Hn9cZ"><i class="fas fa-check"></i><span class="list-text ">Aenean vulputate eleifend tellus.</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-cWQQFM"} -->
<div class="guten-element guten-icon-list-item guten-cWQQFM"><a id="guten-cWQQFM"><i class="fas fa-check"></i><span class="list-text ">Aliquam lorem ante dapibus in.</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/section {"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-yrOqzz","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="yrOqzz"><section class="wp-block-gutenverse-section guten-element guten-section guten-yrOqzz layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":34,"Tablet":25,"Mobile":53},"elementId":"guten-qJd5sW","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"flex-start","Tablet":"default"},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qJd5sW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qJd5sW"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Da3kEP","type":6,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{}},"positioningType":{"Desktop":"inline"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-Da3kEP">Share This Project :</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66,"Mobile":47},"elementId":"guten-SwUdEJ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-SwUdEJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SwUdEJ"><div class="guten-column-wrapper"><!-- wp:gutenverse/social-share {"elementId":"guten-P7ShDq","iconPading":{"Desktop":{},"Mobile":{}},"textPading":{"Desktop":{},"Mobile":{}},"iconColor":{"type":"variable","id":"white"},"iconBackgroundColor":{"type":"variable","id":"secondary"},"borderType":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":{},"Mobile":{}}},"iconColorHover":{"type":"variable","id":"white"},"iconBackgroundColorHover":{"type":"variable","id":"thirteenth"},"borderTypeHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"-3","right":"-3","bottom":"-3","left":"-3"}}}},"iconSize":{"Mobile":{"point":"12","unit":"px"}},"alignment":{"Desktop":"flex-start","Mobile":"flex-start","Tablet":"flex-start"},"gap":{"Desktop":"17","Mobile":"10"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Tablet":{},"Mobile":{}},"padding":{"Tablet":{},"Mobile":{}},"positioningType":{"Tablet":"default"}} -->
<div class="guten-element guten-social-share guten-P7ShDq horizontal guten-social-share"><!-- wp:gutenverse/social-share-facebook {"elementId":"guten-hi1yDw","iconPading":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"textPading":{"Desktop":{}},"showText":false,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} /-->

<!-- wp:gutenverse/social-share-twitter {"elementId":"guten-tB496V","iconPading":{"Desktop":{}},"textPading":{"Desktop":{}},"showText":false,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} /-->

<!-- wp:gutenverse/social-share-whatsapp {"elementId":"guten-YoBpZr","showText":false,"border":{"radius":{"Desktop":{}}}} /--></div>
<!-- /wp:gutenverse/social-share --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
