<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1140"},"height":{},"gap":"no","elementId":"guten-EjVPp5","heightControl":"fit","background":{"type":"default","color":{"type":"variable","id":"fourteenth"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1144,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/BG-gaussian-blur-3.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"1","border":{"radius":{"Desktop":{}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"-59","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"160","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="EjVPp5"><section class="wp-block-gutenverse-section guten-element guten-section guten-EjVPp5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-YytRR3","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YytRR3 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="YytRR3"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-l32Ewe","alignText":{"Desktop":"center"},"titleTag":"h1","subTag":"h3","text":"","focusText":"404","subText":"Page Not Found","showLine":"none","lineMargin":{"Desktop":{}},"mainMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"404-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"150"},"Tablet":{"unit":"px","point":"140"},"Mobile":{"unit":"px","point":"120"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(126, 32, 207, 0)","active":false,"opacity":0,"id":2,"offset":"0.594"},{"color":"rgba(207, 130, 251, 1)","opacity":1,"active":false,"id":1,"offset":"0.594"},{"color":"rgba(196, 113, 247, 1)","active":true,"opacity":1,"id":3,"offset":"1.000"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"white"},"subTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"700"},"subMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"subPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="guten-element guten-advanced-heading guten-l32Ewe"><div class="heading-section "><h1 class="heading-title"><span class="heading-focus">404</span></h1></div><h3 class="heading-subtitle">Page Not Found</h3></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-JXaDGD","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"","left":"","top":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":{}}} -->
<div class="guten-element gutenverse-text-editor guten-JXaDGD"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit aenean commodo.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-TtSZxu","columns":{"Desktop":"1"},"background":[],"backgroundHover":[],"border":[],"borderHover":[],"animation":[]} -->
<div class="guten-element gutenverse-text-editor guten-TtSZxu"><div class="text-content-inner"><!-- wp:search {"label":"","width":75,"widthUnit":"%","buttonText":"Search","buttonUseIcon":true,"align":"center","style":{"border":{"radius":"5px","width":"0px","style":"none"}},"backgroundColor":"secondary","textColor":"white"} /--></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
