<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-EjVPp5","background":{"type":"default","color":{"type":"variable","id":"fourteenth"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1128,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/BG-Blur.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}}},"opacity":"1","border":{"radius":{"Desktop":{}}},"topDivider":{},"bottomDivider":{"type":"tilt_g","flip":false,"colorMode":"gradient","color":{"r":255,"g":255,"b":255,"a":1},"height":{"Desktop":"300","Tablet":"200","Mobile":"150"},"width":{"Desktop":"100"},"gradientColor":[{"color":"rgba(56, 79, 102, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(59, 40, 101, 1)","active":true,"opacity":1,"id":5,"offset":"1.000"}],"gradientAngle":"0","gradientColor3":[{"color":"rgba(47, 108, 252, 1)","opacity":1,"active":false,"id":2,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"}],"gradientColor2":[{"color":"rgba(185, 92, 242, 0.2)","active":true,"opacity":0.2,"id":13,"offset":"0.000"},{"color":"rgba(47, 108, 252, 0.2)","active":false,"opacity":0.2,"id":5,"offset":"1.000"}],"gradientAngle2":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"390","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"160","right":"20","bottom":"380","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"140","right":"","bottom":"360","left":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="EjVPp5"><section class="wp-block-gutenverse-section guten-element guten-section guten-EjVPp5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="231" class="guten-shape-fill" preserveAspectRatio="none" viewBox="0 0 1200 231" width="1200" xmlns="http://www.w3.org/2000/svg"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="0" x2="1200" y1="115.52" y2="115.52"><stop offset="0" stop-color="#fff"></stop><stop offset="1"></stop></linearGradient><linearGradient id="b" gradientUnits="userSpaceOnUse" x1="0" x2="1200" y1="85.41" y2="85.41"><stop offset="0" stop-color="#ccc"></stop><stop offset="1" stop-color="#fff"></stop></linearGradient><clipPath id="c"><path d="m0 0h1200v231h-1200z"></path></clipPath><g><path d="m1200 0v126.06l-1200 104.99v-231.05z" fill="url(#divider-bottom-guten-EjVPp5)"></path><path d="m1200 0v65.84l-1200 104.98v-170.82z" fill="url(#divider-bottom-guten-EjVPp5-2)"></path><path d="m1200 0v5.61l-1200 104.98v-110.59z" fill="url(#divider-bottom-guten-EjVPp5-3)"></path></g><linearGradient id="divider-bottom-guten-EjVPp5" gradientTransform="rotate(0)"><stop style="stop-color:rgba(56, 79, 102, 1)" offset="0%"></stop><stop style="stop-color:rgba(59, 40, 101, 1)" offset="100%"></stop></linearGradient><linearGradient id="divider-bottom-guten-EjVPp5-2" gradientTransform="rotate(0)"><stop style="stop-color:rgba(185, 92, 242, 0.2)" offset="0%"></stop><stop style="stop-color:rgba(47, 108, 252, 0.2)" offset="100%"></stop></linearGradient><linearGradient id="divider-bottom-guten-EjVPp5-3"><stop style="stop-color:rgba(47, 108, 252, 1)" offset="0%"></stop><stop style="stop-color:rgba(255, 255, 255, 1)" offset="0%"></stop></linearGradient></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":57.19,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-YytRR3","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"150"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YytRR3 animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="YytRR3"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-l32Ewe","titleTag":"h1","text":"Hi, My Name Alice ","focusText":"I\'m Professional","subText":"","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"h1-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":{}},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"h1-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(126, 32, 207, 0)","active":false,"opacity":0,"id":2,"offset":"0.594"},{"color":"rgba(207, 130, 251, 1)","opacity":1,"active":false,"id":1,"offset":"0.594"},{"color":"rgba(196, 113, 247, 1)","active":true,"opacity":1,"id":3,"offset":"1.000"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subMargin":{"Desktop":{},"Tablet":{}},"subPadding":{"Desktop":{},"Tablet":{}},"border":{"radius":{"Desktop":{}}}} -->
<div class="guten-element guten-advanced-heading guten-l32Ewe"><div class="heading-section "><h1 class="heading-title">Hi, My Name Alice <span class="heading-focus">I\'m Professional</span></h1></div><span class="heading-subtitle"></span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-v8uSDv","type":1,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h1-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"margin":{"Tablet":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-v8uSDv">Web Designer</h1>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":42.81,"Tablet":72.26,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-iibZe6","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-iibZe6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="iibZe6"><div class="guten-column-wrapper">

<!-- wp:gutenverse/popup-builder {"elementId":"guten-iufYe3","width":{"Desktop":{"point":"820","unit":"px"},"Tablet":{"point":"740","unit":"px"},"Mobile":{"unit":"px","point":"320"}},"containerPadding":{"Desktop":{}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"backgroundColor":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"20"},"overlayColor":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.77}},"closeButtonColor":{"Desktop":{"type":"variable","id":"white"},"Mobile":{"type":"variable","id":"primary"}},"closeButtonBgColor":{"type":"default","color":{"type":"variable","id":"twelfth"}},"closeButtonSize":{"Desktop":"18","Mobile":"16"},"closePositioningLeft":{"Desktop":{"point":"776","unit":"px"},"Tablet":{"point":"696","unit":"px"},"Mobile":{"point":"282","unit":"px"}},"closePositioningRight":{"Desktop":{"point":"20","unit":"px"}},"closePositioningTop":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"closePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"closeBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":{},"Mobile":{}}},"closeBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}}},"openWaitTime":""} -->
<div class="guten-element guten-popup-builder guten-iufYe3" data-trigger="load" data-wait="" data-close-overlay="true"><div class="guten-popup guten-popup-center guten-popup-side-space"><div class="guten-popup-overlay"></div><div class="guten-popup-wrapper guten-popup-wrapper-center"><div class="guten-popup-content animated guten-element-hide desktop-fadeInUp"><div class="guten-popup-close"><i class="gtn gtn-x-line"></i></div><div class="guten-popup-container"><!-- wp:gutenverse/popup-container {"elementId":"guten-WPiHNb","position":"above"} -->
<div class="guten-element guten-popup-content-inner above"><div class="guten-popup-content-wrapper"><!-- wp:gutenverse/section {"width":{"Desktop":1140},"gap":"no","elementId":"guten-wEGS1e","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Mobile":{},"Desktop":{}},"padding":{"Mobile":{},"Desktop":{}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="wEGS1e"><section class="wp-block-gutenverse-section guten-element guten-section guten-wEGS1e layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":null,"Mobile":null},"elementId":"guten-VJnpE3","background":{"type":"default","color":{"type":"variable","id":"white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","left":"20","top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":{}}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"50","bottom":"80","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VJnpE3"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VJnpE3"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-hVJ4AC","alignText":{"Desktop":"center"},"subTag":"h4","text":"Join Our ","focusText":"Newsletter","subText":"","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mainPadding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.541"},{"color":"rgba(234, 186, 255, 1)","opacity":1,"active":true,"id":2,"offset":"0.543"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<div class="guten-element guten-advanced-heading guten-hVJ4AC"><h4 class="heading-subtitle"></h4><div class="heading-section "><h2 class="heading-title">Join Our <span class="heading-focus">Newsletter</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-k5SKVW","dropcapMargin":{},"dropcapPadding":{},"columns":{"Desktop":"1","Tablet":""},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"3","left":"3","top":"","bottom":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-k5SKVW"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Be the first to get exclusive offers and the latest design, projects and news directly to your inbox.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-input-email {"elementId":"guten-FVdYdy","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"5","left":"5","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"youremail@domain.com","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","bottom":"15","right":"20","left":"30"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","right":"","left":""}},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"ninth"}},"inputTypography":{"type":"variable","id":"title-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"ninth"}}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-FVdYdy hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="youremail@domain.com" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-L8NRF2","content":"Subscribe Now","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"5","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Mobile":{}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-L8NRF2"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Subscribe Now</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Mobile":null},"elementId":"guten-P1amJK","background":{"type":"default","image":{"Desktop":{"id":19,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_E5GUBD8MWN.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"-70","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}}},"opacity":"0.7","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"20","left":"","right":"20"}}}},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-P1amJK hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="P1amJK"><div class="guten-column-wrapper"></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/popup-container --></div></div></div></div></div>
<!-- /wp:gutenverse/popup-builder -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-mxFyIR","dropcapMargin":{},"dropcapPadding":{},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-mxFyIR animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa cum sociis natoque penatibus et magnis dis parturient montes.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-HVU6v1","verticalAlign":"center","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"","right":"","left":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="HVU6v1"><section class="wp-block-gutenverse-section guten-element guten-section guten-HVU6v1 animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":31,"Tablet":28,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-L76qez","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Tablet":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-L76qez"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="L76qez"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-vD3ykf","imgSrc":{"media":{"imageId":1134,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/man-tree-plant-street-house-flower-511611-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/man-tree-plant-street-house-flower-511611-pxhere.com-300x300.webp","orientation":"landscape"},"full":{"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/man-tree-plant-street-house-flower-511611-pxhere.com.webp","height":500,"width":500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-vD3ykf"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/man-tree-plant-street-house-flower-511611-pxhere.com.webp" height="500" width="500"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-KmNSfq","imgSrc":{"media":{"imageId":1135,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_MLEPUKHYUU-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_MLEPUKHYUU-300x300.webp","orientation":"landscape"},"full":{"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_MLEPUKHYUU.webp","height":500,"width":500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-KmNSfq"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_MLEPUKHYUU.webp" height="500" width="500"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-U0mp05","imgSrc":{"media":{"imageId":1136,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/ambitious-attractive-boss-business-businessman-challenge-1652043-pxhere-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/ambitious-attractive-boss-business-businessman-challenge-1652043-pxhere-300x300.webp","orientation":"landscape"},"full":{"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/ambitious-attractive-boss-business-businessman-challenge-1652043-pxhere.webp","height":500,"width":500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-U0mp05"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/ambitious-attractive-boss-business-businessman-challenge-1652043-pxhere.webp" height="500" width="500"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-RYm2RI","imgSrc":{"media":{"imageId":1137,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_COOWAKH2W5-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_COOWAKH2W5-300x300.webp","orientation":"landscape"},"full":{"url":"' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_COOWAKH2W5.webp","height":500,"width":500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-RYm2RI"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( VORFOLIO_URI ) . 'assets/img/StockSnap_COOWAKH2W5.webp" height="500" width="500"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":69,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-TKr5Nu","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TKr5Nu"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TKr5Nu"><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-WkuAUj","title":"","align":{"Desktop":"flex-start"},"starIcon":"fill","rating":"5","total":"5","gap":{"Desktop":"0"},"iconSize":{"Desktop":"14","Mobile":"12"},"iconGap":{"Desktop":"5","Mobile":"4"},"iconColorMarked":{"type":"variable","id":"sixth"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"2"}}},"padding":{"Desktop":{}}} -->
<div class="guten-element guten-star-rating guten-WkuAUj"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-Ws0hjn","titleTag":"span","text":"Over ","focusText":"2k+ reviews","subText":"","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"text-14-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"mainMargin":{"Desktop":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Mobile":{}},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"text-14-bold-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"700"},"focusMargin":{"Desktop":{},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subMargin":{"Desktop":{}},"subPadding":{"Desktop":{}}} -->
<div class="guten-element guten-advanced-heading guten-Ws0hjn"><div class="heading-section "><span class="heading-title">Over <span class="heading-focus">2k+ reviews</span></span></div><span class="heading-subtitle"></span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-3zn5QG","content":"Get Started ","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":{},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}}},"showIcon":true,"icon":"gtn gtn-long-arrow-alt-right-solid","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"},"right":{"type":"none"}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-3zn5QG"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Get Started </span><i class="fa-lg gtn gtn-long-arrow-alt-right-solid"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-nsA4Ao","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Mobile":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50","top":"","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="nsA4Ao"><section class="wp-block-gutenverse-section guten-element guten-section guten-nsA4Ao layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Aq3fUU","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-340","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0","right":"20","left":"20","top":"-320"}}},"padding":{"Desktop":{},"Tablet":{}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Aq3fUU animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Aq3fUU"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-zK29Bg","background":{"type":"default","image":{"Desktop":{"id":1138,"image":"' . esc_url( VORFOLIO_URI ) . 'assets/img/african-asian-blonde-brainstorm-business-businessman-1629588-pxhere.com.webp"}},"position":{"Desktop":"top center","Mobile":"custom"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"},"yposition":{"Mobile":{"point":"1","unit":"px"}},"xposition":{"Mobile":{"point":"-400","unit":"px"}}},"backgroundHover":{},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"","left":"","top":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"400","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"350","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"350","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="zK29Bg"><section class="wp-block-gutenverse-section guten-element guten-section guten-zK29Bg layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":34,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-eCzciN","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"position":{"Desktop":"bottom left"}},"backgroundHover":{},"verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-1","left":"-1"}},"Mobile":{"unit":"px","dimension":{"right":"30","top":"0","bottom":"","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"0","left":"0"}},"Tablet":{}},"animation":{},"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eCzciN"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="eCzciN"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-f6bjsg","icon":"gtn gtn-play-button","iconAlign":{"Desktop":null},"iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"13","unit":"px"},"Mobile":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":""},"iconColorTwo":{"type":"variable","id":"white"},"iconShape":"circle","iconBorderRadius":{},"url":"#","animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"},"background":{"type":"default","color":{"type":"variable","id":"secondary"},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"20"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"14","bottom":"14","right":"18","left":"22"}},"Mobile":{"unit":"px","dimension":{"top":"12","right":"16","bottom":"12","left":"20"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-f6bjsg guten-icon animated guten-element-hide desktop-fadeInLeft"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-play-button"></i></a></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/heading {"elementId":"guten-3MiyxD","type":5,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-bold-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"positioningType":{"Desktop":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-3MiyxD animated guten-element-hide desktop-fadeInLeft">Watch Introduction</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-ZtRKcD","textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"15","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"800"},"hideMobile":true} -->
<div class="guten-element gutenverse-text-editor guten-ZtRKcD animated guten-element-hide desktop-fadeInLeft hide-mobile"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-vQ0ocU","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vQ0ocU hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vQ0ocU"><div class="guten-column-wrapper"></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
