<?php
/**
 * Pattern Title content.
 */
return array(
	'title'      => __( 'Gutenverse Services Pricing', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-qTBPHS","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"80","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"50","left":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="qTBPHS"><section class="wp-block-gutenverse-section guten-element guten-section guten-qTBPHS layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-4qutXp","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4qutXp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="4qutXp"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-PM0amU","alignText":{"Desktop":"center"},"subTag":"h4","text":"Flexible Pricing Just ","focusText":"For You","subText":"Pricing","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Mobile":{}},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.537"},{"color":"rgba(234, 186, 255, 1)","opacity":1,"active":true,"id":2,"offset":"0.539"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"secondary"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"subPadding":{"Desktop":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<div class="guten-element guten-advanced-heading guten-PM0amU animated guten-element-hide desktop-fadeInDown"><h4 class="heading-subtitle">Pricing</h4><div class="heading-section "><h2 class="heading-title">Flexible Pricing Just <span class="heading-focus">For You</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"540"},"isChild":true,"height":{},"gap":"no","elementId":"guten-faDlik","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="faDlik"><section class="wp-block-gutenverse-section guten-element guten-section guten-faDlik layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-7OutbF","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-7OutbF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7OutbF"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-DYR1ZP","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-DYR1ZP animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor massa cum sociis natoque.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-oVHMhp","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="oVHMhp"><section class="wp-block-gutenverse-section guten-element guten-section guten-oVHMhp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-F765aW","background":{"type":"default","color":{"type":"variable","id":"eleventh"}},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"15","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"50","right":"30","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-F765aW animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="F765aW"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-fnyN2W","alignText":{"Desktop":"center"},"titleTag":"span","subTag":"h4","text":"$59","focusText":"/ month","subText":"Basic","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"secondary"},"mainTypography":{"type":"variable","id":"price-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"12560"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"fourth"},"focusTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"primary"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}}} -->
<div class="guten-element guten-advanced-heading guten-fnyN2W"><h4 class="heading-subtitle">Basic</h4><div class="heading-section "><span class="heading-title">$59<span class="heading-focus">/ month</span></span></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-8WQw85","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-8WQw85"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/divider {"elementId":"guten-isc4pP","width":{"Desktop":"70"},"dividerColor":{"type":"variable","id":"seventh"},"size":{"Desktop":"1"},"gap":{"Desktop":""},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-isc4pP"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-uY1WSZ","spaceBetween":{"Desktop":"25"},"alignList":{"Desktop":"center"},"iconColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"15"},"textColor":{"type":"variable","id":"fourth"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<div class="guten-element guten-icon-list guten-uY1WSZ"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-eSW1JC"} -->
<div class="guten-element guten-icon-list-item guten-eSW1JC"><a id="guten-eSW1JC"><i class="fas fa-check"></i><span class="list-text ">1 Month Maintenance</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-2AnyyH"} -->
<div class="guten-element guten-icon-list-item guten-2AnyyH"><a id="guten-2AnyyH"><i class="fas fa-check"></i><span class="list-text ">Free Consultation</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-5xy0TM"} -->
<div class="guten-element guten-icon-list-item guten-5xy0TM"><a id="guten-5xy0TM"><i class="fas fa-check"></i><span class="list-text ">1 Free Optimization</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-i2G5Ir"} -->
<div class="guten-element guten-icon-list-item guten-i2G5Ir"><a id="guten-i2G5Ir"><i class="fas fa-check"></i><span class="list-text ">24/7 Support</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/button {"elementId":"guten-7VPcye","content":"Get Started","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}}},"showIcon":true,"icon":"gtn gtn-long-arrow-alt-right-solid","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"},"right":{"type":"none"}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-7VPcye"><a class="guten-button guten-button-sm" href="#"><span>Get Started</span><i class="fa-lg gtn gtn-long-arrow-alt-right-solid"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-F79re4","background":{"type":"default","color":{"type":"variable","id":"secondary"}},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"30","bottom":"50","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-F79re4 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="F79re4"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-gcSM37","alignText":{"Desktop":"center"},"titleTag":"span","subTag":"h4","text":"$99","focusText":"/ month","subText":"Professional","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"price-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"12560"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"fifth"},"focusTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"white"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}}} -->
<div class="guten-element guten-advanced-heading guten-gcSM37"><h4 class="heading-subtitle">Professional</h4><div class="heading-section "><span class="heading-title">$99<span class="heading-focus">/ month</span></span></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-JzRsff","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-JzRsff"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/divider {"elementId":"guten-bgoBNm","width":{"Desktop":"70"},"dividerColor":{"type":"variable","id":"white"},"size":{"Desktop":"1"},"gap":{"Desktop":""},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-bgoBNm"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-Fsxzcr","spaceBetween":{"Desktop":"25"},"alignList":{"Desktop":"center"},"iconColor":{"type":"variable","id":"white"},"iconSize":{"Desktop":"15"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<div class="guten-element guten-icon-list guten-Fsxzcr"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-27JwrP"} -->
<div class="guten-element guten-icon-list-item guten-27JwrP"><a id="guten-27JwrP"><i class="fas fa-check"></i><span class="list-text ">1 Month Maintenance</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-j9E1Vh"} -->
<div class="guten-element guten-icon-list-item guten-j9E1Vh"><a id="guten-j9E1Vh"><i class="fas fa-check"></i><span class="list-text ">Free Consultation</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-r0TJhx"} -->
<div class="guten-element guten-icon-list-item guten-r0TJhx"><a id="guten-r0TJhx"><i class="fas fa-check"></i><span class="list-text ">1 Free Optimization</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-FjHOl6"} -->
<div class="guten-element guten-icon-list-item guten-FjHOl6"><a id="guten-FjHOl6"><i class="fas fa-check"></i><span class="list-text ">24/7 Support</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/button {"elementId":"guten-9ObbbO","content":"Get Started","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"fifth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none","width":"","color":""}},"buttonBorderHover":{"radius":{"Desktop":{}}},"showIcon":true,"icon":"gtn gtn-long-arrow-alt-right-solid","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"},"right":{"type":"none"}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"secondary"},"iconColor":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-9ObbbO"><a class="guten-button guten-button-sm" href="#"><span>Get Started</span><i class="fa-lg gtn gtn-long-arrow-alt-right-solid"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-kiN4TC","background":{"type":"default","color":{"type":"variable","id":"eleventh"}},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"20","top":"0","bottom":"0"}},"Tablet":{"unit":"%","dimension":{"right":"26","left":"26","top":"4"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"50","right":"30","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kiN4TC animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="kiN4TC"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-LXJYKl","alignText":{"Desktop":"center"},"titleTag":"span","subTag":"h4","text":"$169","focusText":"/ month","subText":"Team","showSub":"top","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"type":"variable","id":"secondary"},"mainTypography":{"type":"variable","id":"price-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"12560"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"mainPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"focusColor":{"type":"variable","id":"fourth"},"focusTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{}},"subColor":{"type":"variable","id":"primary"},"subTypography":{"type":"variable","id":"h4-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}}} -->
<div class="guten-element guten-advanced-heading guten-LXJYKl"><h4 class="heading-subtitle">Team</h4><div class="heading-section "><span class="heading-title">$169<span class="heading-focus">/ month</span></span></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-gAWQ6Z","dropcapMargin":{},"dropcapPadding":{},"dropcapBorderWidth":{},"dropcapBorderRadius":{},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-gAWQ6Z"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/divider {"elementId":"guten-ffFSRd","width":{"Desktop":"70"},"dividerColor":{"type":"variable","id":"seventh"},"size":{"Desktop":"1"},"gap":{"Desktop":""},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-ffFSRd"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-HmODND","spaceBetween":{"Desktop":"25"},"alignList":{"Desktop":"center"},"iconColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"15"},"textColor":{"type":"variable","id":"fourth"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
<div class="guten-element guten-icon-list guten-HmODND"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-rWBkW2"} -->
<div class="guten-element guten-icon-list-item guten-rWBkW2"><a id="guten-rWBkW2"><i class="fas fa-check"></i><span class="list-text ">1 Month Maintenance</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-bW9504"} -->
<div class="guten-element guten-icon-list-item guten-bW9504"><a id="guten-bW9504"><i class="fas fa-check"></i><span class="list-text ">Free Consultation</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-EBHYtI"} -->
<div class="guten-element guten-icon-list-item guten-EBHYtI"><a id="guten-EBHYtI"><i class="fas fa-check"></i><span class="list-text ">1 Free Optimization</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-AS92QB"} -->
<div class="guten-element guten-icon-list-item guten-AS92QB"><a id="guten-AS92QB"><i class="fas fa-check"></i><span class="list-text ">24/7 Support</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/button {"elementId":"guten-zO7Vdp","content":"Get Started","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}}},"showIcon":true,"icon":"gtn gtn-long-arrow-alt-right-solid","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"},"right":{"type":"none"}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-zO7Vdp"><a class="guten-button guten-button-sm" href="#"><span>Get Started</span><i class="fa-lg gtn gtn-long-arrow-alt-right-solid"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
