<?php
/**
 * Gutenverse Our Skills content.
 */
return array(
	'title'      => __( 'Gutenverse Our Skills', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"height":{},"elementId":"guten-Dprc0W","background":{"type":"default","color":{"type":"variable","id":"zeever-third"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="Dprc0W"><section class="wp-block-gutenverse-section guten-element guten-section guten-Dprc0W layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-j6ojyR","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-j6ojyR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="j6ojyR"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-sK0EZN","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="sK0EZN"><section class="wp-block-gutenverse-section guten-element guten-section guten-sK0EZN layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-UyU4sb","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-UyU4sb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UyU4sb"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-5HbOWr","color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"h2-font"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"80"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-5HbOWr animated guten-element-hide desktop-fadeInLeft">Here Are Some Of Our Great Skills</h2>
            <!-- /wp:gutenverse/heading -->

            <!-- wp:gutenverse/text-editor {"elementId":"guten-pUn1hd","columns":{"Desktop":"1"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"100","bottom":"20","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="guten-element gutenverse-text-editor guten-pUn1hd"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->

            <!-- wp:gutenverse/progress-bar {"elementId":"guten-Z3dpAf","title":"UI Design","percentage":"91","barColor":{"type":"variable","id":"zeever-border"},"trackColor":{"type":"variable","id":"zeever-secondary"},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h4-alt-font"},"percentColor":{"type":"variable","id":"zeever-bodytext"},"percentTypography":{"type":"variable","id":"body-text-font"}} -->
            <div class="guten-element guten-progress-bar guten-Z3dpAf"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">UI Design</span></div><div class="skill-bar"><div class="skill-track" data-width="91" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->

            <!-- wp:gutenverse/progress-bar {"elementId":"guten-76TLLi","title":" Digital Strategy","percentage":"94","barColor":{"type":"variable","id":"zeever-border"},"trackColor":{"type":"variable","id":"zeever-secondary"},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h4-alt-font"},"percentColor":{"type":"variable","id":"zeever-bodytext"},"percentTypography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-progress-bar guten-76TLLi"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title"> Digital Strategy</span></div><div class="skill-bar"><div class="skill-track" data-width="94" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->

            <!-- wp:gutenverse/progress-bar {"elementId":"guten-np7sUQ","title":" Content Writing","percentage":"89","barColor":{"type":"variable","id":"zeever-border"},"trackColor":{"type":"variable","id":"zeever-secondary"},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h4-alt-font"},"percentColor":{"type":"variable","id":"zeever-bodytext"},"percentTypography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-progress-bar guten-np7sUQ"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title"> Content Writing</span></div><div class="skill-bar"><div class="skill-track" data-width="89" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->

            <!-- wp:gutenverse/progress-bar {"elementId":"guten-QNRhTO","title":"Social Media","percentage":"92","barColor":{"type":"variable","id":"zeever-border"},"trackColor":{"type":"variable","id":"zeever-secondary"},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"barPadding":{"Desktop":{},"Mobile":{}},"barMargin":{"Desktop":{},"Mobile":{}},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h4-alt-font"},"percentColor":{"type":"variable","id":"zeever-bodytext"},"percentTypography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-progress-bar guten-QNRhTO"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Social Media</span></div><div class="skill-bar"><div class="skill-track" data-width="92" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar --></div></div></div>
            <!-- /wp:gutenverse/column -->

            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-dBWwNb","background":{"type":"default","image":{"Desktop":{"id":98,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/employee-meeting-work-job-working-argentina-1599048-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-dBWwNb animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dBWwNb"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-CbBwDv","space":{"Mobile":{"point":"320","unit":"px"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Mobile":{}}} -->
            <div class="guten-element guten-spacer guten-CbBwDv"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
