<?php
/**
 * Gutenverse Contact Detail content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Detail', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"elementId":"guten-oVnLob","background":{"type":"default","color":{"type":"variable","id":"black"}},"border":{"radius":{"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"40","top":"40"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="oVnLob"><section class="wp-block-gutenverse-section guten-element guten-section guten-oVnLob layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-rBMcxH","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rBMcxH"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rBMcxH"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-pvkFAE","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"h2-font"},"positioningType":{"Desktop":"default"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-pvkFAE">Contact Us.</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-GKNHka","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"zeever-secondary"},"typography":{"type":"variable","id":"h5-font"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-GKNHka">Get in touch with zeever</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"gap":"no","elementId":"guten-fiToeQ","margin":{"Desktop":{"unit":"px","dimension":{"top":"80"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="fiToeQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-fiToeQ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-FTsbXZ","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-FTsbXZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FTsbXZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-frDCjc","icon":"gtn gtn-phone1-light","iconAlign":{"Desktop":"center"},"iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"42","unit":"px"},"Mobile":{"point":"30","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"zeever-secondary"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-frDCjc guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-phone1-light"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/heading {"elementId":"guten-3aYpzL","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"h3-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-3aYpzL">Phone Number</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-pUn1hd","columns":{"Desktop":"1"},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-pUn1hd"><div class="text-content-inner"><!-- wp:paragraph -->
<p>(+021) 123 – 456</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-zAh4nn","columns":{"Desktop":"1"},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-zAh4nn"><div class="text-content-inner"><!-- wp:paragraph -->
<p>(+021) 582 – 369</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-AUdTnL","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":[]},"left":{"type":"solid","width":"2","color":{"type":"variable","id":"zeever-secondary"}},"right":{"type":"solid","width":"2","color":{"type":"variable","id":"zeever-secondary"}}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"30","right":"30"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-AUdTnL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AUdTnL"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-HROil5","icon":"gtn gtn-map-marker-light","iconAlign":{"Desktop":"center"},"iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"42","unit":"px"},"Mobile":{"point":"30","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"zeever-secondary"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-HROil5 guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-map-marker-light"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/heading {"elementId":"guten-vHqplE","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"h3-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-vHqplE">Location</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-JZDWvS","columns":{"Desktop":"1"},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-JZDWvS"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Jl. Sunset Road No.815 Kuta, </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-4eITI4","columns":{"Desktop":"1"},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-4eITI4"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Badung, Bali – 80361</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-HSE8WK","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HSE8WK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HSE8WK"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-PVtSq0","icon":"gtn gtn-email1-light","iconAlign":{"Desktop":"center"},"iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"42","unit":"px"},"Mobile":{"point":"30","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"zeever-secondary"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-PVtSq0 guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-email1-light"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/heading {"elementId":"guten-fNOfuR","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"h3-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-fNOfuR">Send Message</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-bJ2nH4","columns":{"Desktop":"1"},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-bJ2nH4"><div class="text-content-inner"><!-- wp:paragraph -->
<p>support@domain.com</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Zym8YR","columns":{"Desktop":"1"},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-Zym8YR"><div class="text-content-inner"><!-- wp:paragraph -->
<p>contact@domain.com</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"elementId":"guten-GpF4nm","background":{"type":"default","color":{"type":"variable","id":"zeever-third"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"60","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="GpF4nm"><section class="wp-block-gutenverse-section guten-element guten-section guten-GpF4nm layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-eVe4dM","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eVe4dM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="eVe4dM"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-0lApJl","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"h2-font"},"positioningType":{"Desktop":"default"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-0lApJl">Send Us A Message!</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-O1649j","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"zeever-secondary"},"typography":{"type":"variable","id":"h5-font"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-O1649j">IF you have any question</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-GeR05R","formId":{"label":"Form Contact","value":338},"hideAfterSubmit":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<form style="display:none" class="guten-element guten-form-builder guten-GeR05R" data-form-id="338" data-hide-after="false"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"isChild":true,"gap":"no","elementId":"guten-hwC8Lk","wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="hwC8Lk"><section class="wp-block-gutenverse-section guten-element guten-section guten-hwC8Lk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-hTdIYs","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hTdIYs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hTdIYs"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-5vWky5","showLabel":false,"inputPlaceholder":"First Name","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"20"}},"Tablet":[]},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"zeever-bodytext"}},"inputTypography":{"type":"variable","id":"body-text-font"},"inputColorNormal":{"Desktop":{"type":"variable","id":"zeever-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"zeever-form"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-5vWky5 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="First Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-kEfpGR","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kEfpGR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="kEfpGR"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-QgMaRN","showLabel":false,"inputPlaceholder":"First Name","showHelper":false,"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"20"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"zeever-bodytext"}},"inputTypography":{"type":"variable","id":"body-text-font"},"inputColorNormal":{"Desktop":{"type":"variable","id":"zeever-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"zeever-form"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-QgMaRN hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="First Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"isChild":true,"gap":"no","elementId":"guten-rJufvn","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="rJufvn"><section class="wp-block-gutenverse-section guten-element guten-section guten-rJufvn layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3nBUBZ","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3nBUBZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3nBUBZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-email {"elementId":"guten-QJbdoH","showLabel":false,"showHelper":false,"inputPlaceholder":"Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"zeever-bodytext"}},"inputTypography":{"type":"variable","id":"body-text-font"},"inputColorNormal":{"Desktop":{"type":"variable","id":"zeever-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"zeever-form"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-QJbdoH hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-6TRFpW","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6TRFpW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6TRFpW"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-Nqblcc","showLabel":false,"inputPlaceholder":"Subject","showHelper":false,"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"20"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"zeever-bodytext"}},"inputTypography":{"type":"variable","id":"body-text-font"},"inputColorNormal":{"Desktop":{"type":"variable","id":"zeever-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"zeever-form"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-Nqblcc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-IYqA3y","showLabel":false,"showHelper":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"inputHeight":{"Desktop":"220"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"zeever-bodytext"}},"inputTypography":{"type":"variable","id":"body-text-font"},"inputColorNormal":{"Desktop":{"type":"variable","id":"zeever-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"zeever-form"}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-IYqA3y hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-q9SenD","content":"Send Message","buttonBackground":{"type":"default","color":{"r":253,"g":251,"b":251,"a":0}},"buttonBackgroundHover":{"type":"default","color":""},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"zeever-secondary"}}},"buttonBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"zeever-button-border"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"button-font"},"hoverTextColor":{"type":"variable","id":"zeever-primary"},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"25","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"20","left":"20"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-q9SenD"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"gap":"no","elementId":"guten-HrmcEJ","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}},"zIndex":{"Desktop":""},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="HrmcEJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-HrmcEJ layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-q3lgRr","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":""}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Desktop":""}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-q3lgRr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="q3lgRr"><div class="guten-column-wrapper"><!-- wp:gutenverse/google-maps {"elementId":"guten-oGEFfX","location":"Jl. Sunset Road, Bali","zoom":"17","height":{"Desktop":"460","Mobile":"360"},"mapFilter":{"saturation":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Desktop":"1"}} -->
<div class="guten-element gutenverse-maps guten-oGEFfX"><iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=Jl.%20Sunset%20Road%2C%20Bali&amp;z=17&amp;t=m&amp;output=embed&amp;iwloc=near" title="Jl. Sunset Road, Bali"></iframe></div>
<!-- /wp:gutenverse/google-maps --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
