<?php
/**
 * Gutenverse Best Solution content.
 */
return array(
	'title'      => __( 'Gutenverse Best Solution', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"height":{},"elementId":"guten-H8d2EO","verticalAlign":"center","background":{"type":"default","color":{"type":"variable","id":"black"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="H8d2EO"><section class="wp-block-gutenverse-section guten-element guten-section guten-H8d2EO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-AoWPJO","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-AoWPJO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AoWPJO"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-PVvNz3","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="PVvNz3"><section class="wp-block-gutenverse-section guten-element guten-section guten-PVvNz3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-6v8Nk9","background":{"type":"default","image":{"Desktop":{"id":99,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/employee-meeting-work-job-working-argentina-1599057-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"20","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-6v8Nk9 animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6v8Nk9"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-PPRAWw","space":{"Desktop":{"point":"540","unit":"px"},"Mobile":{"point":"320","unit":"px"}}} -->
            <div class="guten-element guten-spacer guten-PPRAWw"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column -->

            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-C2FamW","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-C2FamW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="C2FamW"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-rOTdRc","color":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"h2-font"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-rOTdRc animated guten-element-hide desktop-fadeInRight">Best Solutions For Your Business</h2>
            <!-- /wp:gutenverse/heading -->

            <!-- wp:gutenverse/text-editor {"elementId":"guten-H5rWBY","columns":{"Desktop":"1"},"textColor":{"type":"variable","id":"zeever-bodytext"},"typography":{"type":"variable","id":"body-text-font"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"100","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
            <div class="guten-element gutenverse-text-editor guten-H5rWBY animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->

            <!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"Watch Video","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"23","right":"30","bottom":"23","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"20","left":"20"}}},"buttonBackground":{"type":"default","color":{"r":145,"g":108,"b":61,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"zeever-secondary"}}},"buttonBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"zeever-button-border"}}},"showIcon":true,"icon":"gtn gtn-play-button","iconSpacing":{"Desktop":"14"},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"color":{"type":"variable","id":"zeever-primary"},"iconColor":{"type":"variable","id":"zeever-primary"},"typography":{"type":"variable","id":"button-font"},"hoverIconColor":{"type":"variable","id":"zeever-primary"},"hoverTextColor":{"type":"variable","id":"zeever-primary"}} -->
            <div class="guten-element guten-button-wrapper guten-BTgZlT"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><i class="fa-lg gtn gtn-play-button"></i><span>Watch Video</span></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
