<?php
/**
 * Gutenverse Team content.
 */
return array(
	'title'      => __( 'Gutenverse Team', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"height":{},"elementId":"guten-nYO4iW","background":{"type":"default","color":{"type":"variable","id":"zeever-third"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"80"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"20"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="nYO4iW"><section class="wp-block-gutenverse-section guten-element guten-section guten-nYO4iW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-O3OX6v","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-O3OX6v"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="O3OX6v"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-JR6zSO","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="JR6zSO"><section class="wp-block-gutenverse-section guten-element guten-section guten-JR6zSO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":65},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-0oWjc1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-0oWjc1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0oWjc1"><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-uCwz7h","alignText":{"Desktop":"flex-start"},"text":"Meet our team.","focusText":"","subText":"The Best People To Support Your Project","lineWidth":{"Desktop":"12","Tablet":"","Mobile":""},"lineHeight":{"Desktop":"3"},"lineStyle":"solid","lineMargin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"mainColor":{"type":"variable","id":"zeever-primary"},"mainTypography":{"type":"variable","id":"h2-font"},"mainBackground":{"type":"default","gradientColor":[{"color":"rgb(49, 207, 180)","id":1,"offset":"0.132","active":true},{"color":"rgb(126, 32, 207)","id":2,"offset":"1.000","active":false}],"color":""},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","top":""}},"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"focusBackground":{"type":"default","color":""},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"focusPadding":{"Desktop":{"unit":"px","dimension":{"top":"3","right":"3","bottom":"3","left":"3"}}},"subColor":{"type":"variable","id":"zeever-secondary"},"subTypography":{"type":"variable","id":"h5-font"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"subPadding":{"Desktop":{},"Mobile":[]},"lineColor":{"type":"variable","id":"zeever-secondary"},"border":{"radius":{"Desktop":{}}},"boxShadow":{"position":"outline"},"boxShadowHover":{"position":"outline"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
            <div class="guten-element guten-advanced-heading guten-uCwz7h animated guten-element-hide desktop-fadeInLeft"><div class="heading-section "><div class="heading-line before"></div><h2 class="heading-title">Meet our team.<span class="heading-focus"></span></h2></div><span class="heading-subtitle">The Best People To Support Your Project</span></div>
            <!-- /wp:gutenverse/advanced-heading --></div></div></div>
            <!-- /wp:gutenverse/column -->

            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":35,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-7sTE7n","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"animation":{},"hideMobile":true} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-7sTE7n hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7sTE7n"><div class="guten-column-wrapper"></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->

            <!-- wp:gutenverse/section {"layout":"fullwidth","sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-Kkoj10","background":{"type":"default","color":{"type":"variable","id":"zeever-third"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"120"}},"Tablet":{"unit":"px","dimension":{"bottom":"80","left":"10","right":"10"}},"Mobile":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="Kkoj10"><section class="wp-block-gutenverse-section guten-element guten-section guten-Kkoj10 layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3e5E6Z","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"10","right":"10"}}},"padding":{"Desktop":{}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-3e5E6Z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3e5E6Z"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-DQMxmt","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":297,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/face-eyewear-glasses-green-blue-head-1493723-pxhere.com.webp"},"name":"Jonathan Doe","job":"Digital Marketing","nameColor":{"type":"variable","id":"zeever-primary"},"nameTypography":{"type":"variable","id":"h3-font"},"jobColor":{"type":"variable","id":"zeever-primary"},"jobTypography":{"type":"variable","id":"body-text-font"},"descColor":{"type":"variable","id":"zeever-primary"},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"profileBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"hoverPadding":{"Tablet":{},"Desktop":{}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"hoverContentBorder":{"radius":{"Tablet":{},"Desktop":{}}}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-DQMxmt animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/face-eyewear-glasses-green-blue-head-1493723-pxhere.com.webp" alt="Jonathan Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jonathan Doe</h3><p class="profile-sub">Digital Marketing</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-9hrXzV","iconSize":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"zeever-primary"},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-secondary"}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-primary"}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{}},"hoverIconColor":{"type":"variable","id":"zeever-third"},"hoverBgColor":{"type":"variable","id":"zeever-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="guten-element guten-social-icons guten-9hrXzV circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-WeoRYA"} -->
            <div class="guten-element guten-social-icon guten-WeoRYA facebook"><a id="guten-WeoRYA"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-kBOxHe"} -->
            <div class="guten-element guten-social-icon guten-kBOxHe twitter"><a id="guten-kBOxHe"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-92PIgK"} -->
            <div class="guten-element guten-social-icon guten-92PIgK instagram"><a id="guten-92PIgK"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->

            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-XCdrQf","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Desktop":{}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-XCdrQf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XCdrQf"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-OX0kUn","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":299,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/plaid-clothing-pattern-dress-shirt-cool-street-fashion-1513593-pxhere.com.webp"},"name":"Christopher Doe","job":"Web Developer","nameColor":{"type":"variable","id":"zeever-primary"},"nameTypography":{"type":"variable","id":"h3-font"},"jobColor":{"type":"variable","id":"zeever-primary"},"jobTypography":{"type":"variable","id":"body-text-font"},"descColor":{"type":"variable","id":"zeever-primary"},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"Mobile":{}},"profileBorder":{"radius":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{}}},"imageBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"hoverPadding":{"Desktop":{}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-OX0kUn animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/plaid-clothing-pattern-dress-shirt-cool-street-fashion-1513593-pxhere.com.webp" alt="Christopher Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Christopher Doe</h3><p class="profile-sub">Web Developer</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-4Vxlya","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"zeever-primary"},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-secondary"}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-primary"}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{"Desktop":{}},"hoverIconColor":{"type":"variable","id":"zeever-third"},"hoverBgColor":{"type":"variable","id":"zeever-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-4Vxlya circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-wQRVvm"} -->
            <div class="guten-element guten-social-icon guten-wQRVvm facebook"><a id="guten-wQRVvm"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-7VZADO"} -->
            <div class="guten-element guten-social-icon guten-7VZADO twitter"><a id="guten-7VZADO"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-vUQkO0"} -->
            <div class="guten-element guten-social-icon guten-vUQkO0 instagram"><a id="guten-vUQkO0"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->

            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ae55nh","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-ae55nh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ae55nh"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-mlBErr","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":288,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/person-girl-woman-model-spring-fashion-110400-pxhere.com.webp"},"name":"Chintya Doe","job":"Talent Management","nameColor":{"type":"variable","id":"zeever-primary"},"nameTypography":{"type":"variable","id":"h3-font"},"jobColor":{"type":"variable","id":"zeever-primary"},"jobTypography":{"type":"variable","id":"body-text-font"},"descColor":{"type":"variable","id":"zeever-primary"},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-mlBErr animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/person-girl-woman-model-spring-fashion-110400-pxhere.com.webp" alt="Chintya Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Chintya Doe</h3><p class="profile-sub">Talent Management</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-oAKPgJ","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-secondary"}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-primary"}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{"Desktop":{}},"hoverIconColor":{"r":8,"g":34,"b":34,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-oAKPgJ circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-LOXbwz"} -->
            <div class="guten-element guten-social-icon guten-LOXbwz facebook"><a id="guten-LOXbwz"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-q9PAUt"} -->
            <div class="guten-element guten-social-icon guten-q9PAUt twitter"><a id="guten-q9PAUt"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-nVh333"} -->
            <div class="guten-element guten-social-icon guten-nVh333 instagram"><a id="guten-nVh333"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->

            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-QLT6qO","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-QLT6qO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QLT6qO"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-7lBszl","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":295,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/work-person-people-girl-woman-isolated-1258806-pxhere.com.webp"},"name":"Jennifer Doe","job":"Marketing","nameColor":{"type":"variable","id":"zeever-primary"},"nameTypography":{"type":"variable","id":"h3-font"},"jobColor":{"type":"variable","id":"zeever-primary"},"jobTypography":{"type":"variable","id":"body-text-font"},"descColor":{"type":"variable","id":"zeever-primary"},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-7lBszl animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/work-person-people-girl-woman-isolated-1258806-pxhere.com.webp" alt="Jennifer Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jennifer Doe</h3><p class="profile-sub">Marketing</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-jjfR5i","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"zeever-primary"},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-secondary"}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-primary"}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{"Desktop":{}},"hoverIconColor":{"type":"variable","id":"zeever-third"},"hoverBgColor":{"type":"variable","id":"zeever-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-jjfR5i circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-JM0rBf"} -->
            <div class="guten-element guten-social-icon guten-JM0rBf facebook"><a id="guten-JM0rBf"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-Y6xBNF"} -->
            <div class="guten-element guten-social-icon guten-Y6xBNF twitter"><a id="guten-Y6xBNF"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-Zy9zxI"} -->
            <div class="guten-element guten-social-icon guten-Zy9zxI instagram"><a id="guten-Zy9zxI"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->

            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-RiuPND","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{},"hideTablet":true} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-RiuPND hide-tablet"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RiuPND"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-38EhTA","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":300,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/street-fashion-photograph-blue-clothing-jeans-turquoise-1532253-pxhere.com.webp"},"name":"Marcho Doe","nameColor":{"type":"variable","id":"zeever-primary"},"nameTypography":{"type":"variable","id":"h3-font"},"jobColor":{"type":"variable","id":"zeever-primary"},"jobTypography":{"type":"variable","id":"body-text-font"},"descColor":{"type":"variable","id":"zeever-primary"},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-38EhTA animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/street-fashion-photograph-blue-clothing-jeans-turquoise-1532253-pxhere.com.webp" alt="Marcho Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Marcho Doe</h3><p class="profile-sub">Designer</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-8aLkY2","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-secondary"}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"zeever-primary"}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{},"hoverIconColor":{"r":8,"g":34,"b":34,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-8aLkY2 circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-C3IEEr"} -->
            <div class="guten-element guten-social-icon guten-C3IEEr facebook"><a id="guten-C3IEEr"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-4JkMRD"} -->
            <div class="guten-element guten-social-icon guten-4JkMRD twitter"><a id="guten-4JkMRD"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->

            <!-- wp:gutenverse/social-icon {"elementId":"guten-0ad1PA"} -->
            <div class="guten-element guten-social-icon guten-0ad1PA instagram"><a id="guten-0ad1PA"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
