<?php
/**
 * Gutenverse Hero content.
 */
return array(
	'title'      => __( 'Gutenverse About Featured', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"elementId":"guten-unjoJz","background":{"type":"default","color":{"type":"variable","id":"black"}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"0","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="unjoJz"><section class="wp-block-gutenverse-section guten-element guten-section guten-unjoJz layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-NvNYhF","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NvNYhF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="NvNYhF"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-oSOE7E","wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="oSOE7E"><section class="wp-block-gutenverse-section guten-element guten-section guten-oSOE7E layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-mwKsMk","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mwKsMk"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="mwKsMk"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-ScoKgT","title":"Excellent Design","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","icon":"gtn gtn-layers1-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"r":102,"g":252,"b":241,"a":1}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"zeever-secondary"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{},"Tablet":[]},"titleMargin":{"Desktop":{},"Tablet":[]},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h3-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"descColor":{"type":"variable","id":"zeever-bodytext"},"descTypography":{"type":"variable","id":"body-text-font"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="guten-element guten-ScoKgT animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-layers1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Excellent Design</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-dk8hoJ","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-dk8hoJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dk8hoJ"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-VANQCt","title":"Fast Response","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","icon":"gtn gtn-flash-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"r":102,"g":252,"b":241,"a":1}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"zeever-secondary"},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[]},"titleMargin":{"Desktop":{},"Tablet":[]},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h3-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"descColor":{"type":"variable","id":"zeever-bodytext"},"descTypography":{"type":"variable","id":"body-text-font"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-VANQCt animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-flash-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Fast Response</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-fj9Q0Z","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fj9Q0Z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="fj9Q0Z"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-KMdITT","title":"Time Saving","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","icon":"gtn gtn-clock1-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"r":102,"g":252,"b":241,"a":1}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"zeever-secondary"},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[]},"titleMargin":{"Desktop":{},"Tablet":[]},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h3-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"descColor":{"type":"variable","id":"zeever-bodytext"},"descTypography":{"type":"variable","id":"body-text-font"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-KMdITT animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-clock1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Time Saving</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-h7yr0I","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="h7yr0I"><section class="wp-block-gutenverse-section guten-element guten-section guten-h7yr0I layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-g368rz","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-g368rz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="g368rz"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Dmv9ZV","title":"Perfect Solutions","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","icon":"gtn gtn-badge-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"r":102,"g":252,"b":241,"a":1}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"zeever-secondary"},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[]},"titleMargin":{"Desktop":{},"Tablet":[]},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h3-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"descColor":{"type":"variable","id":"zeever-bodytext"},"descTypography":{"type":"variable","id":"body-text-font"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-Dmv9ZV animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-badge-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Perfect Solutions</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-U2Amtn","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-U2Amtn"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="U2Amtn"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-7SkowK","title":"Professional Team","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","icon":"gtn gtn-team-2-line","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"r":102,"g":252,"b":241,"a":1}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"zeever-secondary"},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h3-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":[]},"descColor":{"type":"variable","id":"zeever-bodytext"},"descTypography":{"type":"variable","id":"body-text-font"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<div class="guten-element guten-7SkowK animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-team-2-line"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Professional Team</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-mNdpwv","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"20","right":"0","bottom":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mNdpwv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="mNdpwv"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-xR18qg","title":"24/7 Support","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","icon":"gtn gtn-support-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"r":102,"g":252,"b":241,"a":1}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"zeever-secondary"},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[]},"titleMargin":{"Desktop":{},"Tablet":[]},"titleColor":{"type":"variable","id":"zeever-primary"},"titleTypography":{"type":"variable","id":"h3-font"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"descColor":{"type":"variable","id":"zeever-bodytext"},"descTypography":{"type":"variable","id":"body-text-font"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
<div class="guten-element guten-xR18qg animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-support-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">24/7 Support</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1170},"isChild":true,"gap":"no","elementId":"guten-tecoV4","background":{"type":"default","color":{"type":"variable","id":"black"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"120"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"none"},"duration":"slow","delay":"1400"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="tecoV4"><section class="wp-block-gutenverse-section guten-element guten-section guten-tecoV4 slow layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-TfCqLS","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"right":{"type":"solid","width":"3","color":{"type":"variable","id":"zeever-secondary"}},"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":""}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TfCqLS animated guten-element-hide desktop-fadeInDown"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TfCqLS"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-ZcLJy5","space":{"Desktop":{"point":"60","unit":"px"},"Mobile":{"point":"20","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-ZcLJy5"></div>
<!-- /wp:gutenverse/spacer --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-SwnVsl","verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-SwnVsl"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SwnVsl"><div class="guten-column-wrapper"></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
