<?php
/**
 * Gutenverse Index Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Index Hero', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":1270,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_HWLNQD65VR.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"fifth"}},"opacity":"0.8","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="9rsSZi"><section class="wp-block-gutenverse-section guten-element guten-section guten-9rsSZi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-hPOdgn","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-hPOdgn animated guten-element-hide desktop-fadeInDown"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hPOdgn"><div class="guten-column-wrapper"><!-- wp:post-title {"style":{"typography":{"fontSize":"50px"}},"textColor":"white"} /--></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
