<?php
/**
 * Gutenverse Home Section 6 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 6', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-cP4Fhu","background":{"type":"default","color":{"type":"variable","id":"fourth"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="cP4Fhu"><section class="wp-block-gutenverse-section guten-element guten-section guten-cP4Fhu layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Ru6Jwn","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Ru6Jwn"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Ru6Jwn"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-9BDo7o","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-9BDo7o animated guten-element-hide desktop-fadeInUp">TRUSTED BY BIG COMPANIES</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-UkhKnn","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"50","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"20","left":"20"}},"Tablet":{"unit":"%","dimension":{"right":"7","left":"7","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-UkhKnn animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-kZgqeZ","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="kZgqeZ"><section class="wp-block-gutenverse-section guten-element guten-section guten-kZgqeZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-zGjrdA","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Desktop":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zGjrdA animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zGjrdA"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-zLcBop","imgSrc":{"media":{"imageId":1273,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-zeever@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":62,"width":300,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-zeever@2x-8-300x62.webp","orientation":"landscape"},"full":{"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-zeever@2x-8.webp","height":171,"width":824,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"106","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"align":{"Mobile":"center"},"opacity":"0.9","border":{"radius":{"Desktop":{}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-zLcBop"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-zeever@2x-8.webp" height="171" width="824"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-IwBM82","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Mobile":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"fifth"}},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"fifth"}}},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Desktop":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-IwBM82 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="IwBM82"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-izjPOv","imgSrc":{"media":{"imageId":1272,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-financio@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":68,"width":300,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-financio@2x-8-300x68.webp","orientation":"landscape"},"large":{"height":231,"width":1024,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-financio@2x-8-1024x231.webp","orientation":"landscape"},"full":{"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-financio@2x-8.webp","height":266,"width":1180,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"180","unit":"px"},"Tablet":{"point":"120","unit":"px"},"Mobile":{"point":"100","unit":"px"}},"height":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}},"all":{"type":"none"}},"align":{"Mobile":"center"},"opacity":"0.9","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-izjPOv"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-financio@2x-8.webp" height="266" width="1180"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-OEMhUm","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"fifth"}}},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OEMhUm animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OEMhUm"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-GYAU5P","imgSrc":{"media":{"imageId":1271,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-xtreme_1@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":49,"width":300,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-xtreme_1@2x-8-300x49.webp","orientation":"landscape"},"large":{"height":168,"width":1024,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-xtreme_1@2x-8-1024x168.webp","orientation":"landscape"},"full":{"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-xtreme_1@2x-8.webp","height":178,"width":1085,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"140","unit":"px"},"Tablet":{"point":"106","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"align":{"Mobile":"center"},"opacity":"0.9"} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-GYAU5P"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-xtreme_1@2x-8.webp" height="178" width="1085"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-oGMvji","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Mobile":{},"Desktop":{}}},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-oGMvji animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="oGMvji"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Ch2KhT","imgSrc":{"media":{"imageId":1270,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-knees_1@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":79,"width":300,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-knees_1@2x-8-300x79.webp","orientation":"landscape"},"full":{"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-knees_1@2x-8.webp","height":180,"width":685,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"106","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"align":{"Mobile":"center"},"opacity":"0.9"} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Ch2KhT"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo-knees_1@2x-8.webp" height="180" width="685"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
