<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-xbSNFk","background":{},"backgroundHover":{},"border":{"radius":{"Desktop":{}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"140"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="xbSNFk"><section class="wp-block-gutenverse-section guten-element guten-section guten-xbSNFk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-5VxRFd","background":{"type":"default","image":{"Desktop":{"id":1144,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_LK46EHFEEF.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-5VxRFd animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5VxRFd"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-j2w1pg","space":{"Desktop":{"unit":"vh","point":"50"},"Tablet":{"point":"364","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-j2w1pg"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-SguYJS","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"70"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-SguYJS"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SguYJS"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-IBGWfC","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-IBGWfC animated guten-element-hide desktop-fadeInRight">We Provide The Best Solutions To Grow Your Business</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-8ITkKC","textColor":{"type":"variable","id":"seven"},"typography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element gutenverse-text-editor guten-8ITkKC animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"isChild":true,"height":{},"gap":"no","elementId":"guten-fj02cB","background":{"type":"default","color":{"type":"variable","id":"seventeen"}},"backgroundHover":{},"border":{"radius":{"Desktop":{}},"left":{"type":"solid","color":{"type":"variable","id":"third"},"width":"7"}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="fj02cB"><section class="wp-block-gutenverse-section guten-element guten-section guten-fj02cB animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-a2wMqJ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-a2wMqJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="a2wMqJ"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-4JGitp","textColor":{"type":"variable","id":"seven"},"typography":{"type":"variable","id":"text-editor-italic","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"},"Tablet":{"unit":"px","point":"30"},"Mobile":{"unit":"px","point":"22"}},"weight":"400","style":"italic"}} -->
			<div class="guten-element gutenverse-text-editor guten-4JGitp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore incididunt ut labore magna aliqua. </p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
