<?php
/**
 * Gutenverse Home Section 5 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 5', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-6v2y9Y","background":{"type":"default","color":{"type":"variable","id":"eight"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="6v2y9Y"><section class="wp-block-gutenverse-section guten-element guten-section guten-6v2y9Y layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-y5W8b4","order":{"Mobile":2},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"80","top":"82","right":"70","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20","top":"60","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"40","right":"20","left":"20"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-y5W8b4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="y5W8b4"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-Ca8LBk","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="Ca8LBk"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ca8LBk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-OnqBc0","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"flex-end"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OnqBc0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OnqBc0"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-OH2B7B","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-OH2B7B animated guten-element-hide desktop-fadeInLeft">Best Solutions To HELPS YOUR BUSINESS</h2>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-SYapx9","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="SYapx9"><section class="wp-block-gutenverse-section guten-element guten-section guten-SYapx9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-7vDfTP","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"flex-end"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7vDfTP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7vDfTP"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-E5DiTJ","textColor":{"type":"variable","id":"seven"},"typography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<div class="guten-element gutenverse-text-editor guten-E5DiTJ animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-yNS9Ex","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="yNS9Ex"><section class="wp-block-gutenverse-section guten-element guten-section guten-yNS9Ex layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-I4FqHk","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"flex-end"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-I4FqHk"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="I4FqHk"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-hStkEJ","spaceBetween":{"Desktop":"5"},"iconColor":{"type":"variable","id":"secondary"},"iconColorHover":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"15"},"textColor":{"type":"variable","id":"seven"},"textColorHover":{"type":"variable","id":"seven"},"textIndent":{"Desktop":"13","Tablet":"13","Mobile":"13"},"textTypography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<div class="guten-element guten-icon-list guten-hStkEJ animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-tvfFZE"} -->
			<div class="guten-element guten-icon-list-item guten-tvfFZE"><a id="guten-tvfFZE"><i class="fas fa-check"></i><span class="list-text ">We Are Leading in Consulting Services</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-pXjwjQ"} -->
			<div class="guten-element guten-icon-list-item guten-pXjwjQ"><a id="guten-pXjwjQ"><i class="fas fa-check"></i><span class="list-text ">Solutions For Small &amp; Large Business</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ylzVvk"} -->
			<div class="guten-element guten-icon-list-item guten-ylzVvk"><a id="guten-ylzVvk"><i class="fas fa-check"></i><span class="list-text ">Guidence From Our Expert Team</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-NxdNlf","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="NxdNlf"><section class="wp-block-gutenverse-section guten-element guten-section guten-NxdNlf layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3O5jtx","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"flex-end"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3O5jtx"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3O5jtx"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-VneMQi","content":"GET IT TOUCH","buttonWidth":{"Desktop":"40","Tablet":"55","Mobile":"70"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"showIcon":true,"icon":"far fa-envelope","iconSpacing":{"Desktop":"14"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"border":{"radius":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"hoverIconColor":{"type":"variable","id":"white"},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<div class="guten-element guten-button-wrapper guten-VneMQi"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><i class="fa-lg far fa-envelope"></i><span>GET IT TOUCH</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ZmcB8z","order":{"Mobile":1},"background":{"type":"default","image":{"Desktop":{"id":1178,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_7BQNRHB6EX.webp"}},"position":{"Desktop":"center center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default","Tablet":"center"},"horizontalAlign":{"Desktop":"default","Tablet":"center"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ZmcB8z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ZmcB8z"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-37ipjz","space":{"Mobile":{"point":"250","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-37ipjz"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
