<?php
/**
 * Gutenverse Footer content.
 */
return array(
	'title'      => __( 'Gutenverse Footer', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"1170"},"height":{},"gap":"no","elementId":"guten-sR0jCU","background":{"type":"default","image":{"Desktop":{"id":1183,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/technology-westerner-white-white-background-wireless-woman-1431119-pxhere.com.webp"}},"position":{"Desktop":"top center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"fifth"}},"opacity":"0.9","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="sR0jCU"><section class="wp-block-gutenverse-section guten-element guten-section guten-sR0jCU layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-RIOfbI","order":{"Mobile":4},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":{}},"padding":{"Tablet":{},"Mobile":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-RIOfbI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RIOfbI"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-nRgPoO","imgSrc":{"media":{"imageId":1127,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo@2x-150x150.webp","orientation":"landscape"},"medium":{"height":98,"width":300,"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo@2x-300x98.webp","orientation":"landscape"},"full":{"url":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo@2x.webp","height":332,"width":1014,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"56"},"Tablet":{"point":"172","unit":"px"},"Mobile":{"point":"149","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"align":{"Desktop":"left"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-nRgPoO"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( HYPEBIZ_URI ) . 'assets/img/logo@2x.webp" height="332" width="1014"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-M9QnkD","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{}},"padding":{"Tablet":{},"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-M9QnkD"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Copyright © 2022. By Jegstudio<br>All rights reserved.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-KHgxhL","order":{"Mobile":3},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KHgxhL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KHgxhL"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-oz6Yh3","type":6,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{},"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Tablet":{},"Mobile":{},"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-oz6Yh3">RECENT NEWS</h6>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-efpwQx","spaceBetween":{"Desktop":"10"},"alignList":{"Desktop":"flex-start"},"iconColor":{"type":"variable","id":"secondary"},"iconColorHover":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textColorHover":{"type":"variable","id":"white"},"textIndent":{"Desktop":"8"},"textTypography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
			<div class="guten-element guten-icon-list guten-efpwQx"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-EgKdFF"} -->
			<div class="guten-element guten-icon-list-item guten-EgKdFF"><a id="guten-EgKdFF"><i class="fas fa-chevron-right"></i><span class="list-text ">Far far away, behind the word mountains</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-R0fYR4"} -->
			<div class="guten-element guten-icon-list-item guten-R0fYR4"><a id="guten-R0fYR4"><i class="fas fa-chevron-right"></i><span class="list-text ">A small river named Duden flows by their place</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-gwZzzS"} -->
			<div class="guten-element guten-icon-list-item guten-gwZzzS"><a id="guten-gwZzzS"><i class="fas fa-chevron-right"></i><span class="list-text ">When she reached the first hills of the Italic Mountains</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-RNM5fA","order":{"Mobile":2},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"50"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-RNM5fA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RNM5fA"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-gXsa4y","type":6,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{},"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Tablet":{},"Mobile":{},"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-gXsa4y">QUICK LINKS</h6>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-mieRKy","spaceBetween":{"Desktop":"10"},"textColor":{"type":"variable","id":"white"},"textColorHover":{"type":"variable","id":"white"},"textTypography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
			<div class="guten-element guten-icon-list guten-mieRKy"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-76ZuNZ","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-76ZuNZ"><a id="guten-76ZuNZ"><span class="list-text no-icon">Home</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-7Mi80l","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-7Mi80l"><a id="guten-7Mi80l"><span class="list-text no-icon">Our Services</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vFaTyw","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-vFaTyw"><a id="guten-vFaTyw"><span class="list-text no-icon">Our Team</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-p8PVji","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-p8PVji"><a id="guten-p8PVji"><span class="list-text no-icon">Our Clients</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-oJJcCT","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-oJJcCT"><a id="guten-oJJcCT"><span class="list-text no-icon">Contact Us</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-4tt52P","order":{"Mobile":1},"background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Mobile":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-4tt52P"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="4tt52P"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-9d1OyY","type":6,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{},"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Tablet":{},"Mobile":{},"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-9d1OyY">NEWSLETTER</h6>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-sy4Qs8","dropcapMargin":{},"dropcapPadding":{},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-sy4Qs8"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Join our mailing list to get news updates and exclusive offers.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/form-builder {"elementId":"guten-AdGovK","formId":{"label":"Form Email","value":116}} -->
			<form style="display:none" class="guten-element guten-form-builder guten-AdGovK" data-form-id="116"><!-- wp:gutenverse/form-input-email {"elementId":"guten-kr7Njz","showLabel":false,"showHelper":false,"labelColor":{"Desktop":{}},"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"16","bottom":"10","left":"16"}},"Tablet":{}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"placeholderColor":{"Desktop":{}},"inputTypography":{"type":"variable","id":"text-editor-style-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"inputBgColorHover":{"Desktop":{"type":"variable","id":"white"}},"inputBgColorFocus":{"Desktop":{"type":"variable","id":"white"}}} -->
			<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-kr7Njz hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-email -->
			
			<!-- wp:gutenverse/form-input-submit {"elementId":"guten-YnrGHZ","content":"Send","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-1","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"white"},"paddingButton":{"Desktop":{},"Mobile":{},"Tablet":{}}} -->
			<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-YnrGHZ"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
			<!-- /wp:gutenverse/form-input-submit --></form>
			<!-- /wp:gutenverse/form-builder --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
