<?php
/**
 * Gutenverse About Feature content.
 */
return array(
	'title'      => __( 'Gutenverse About Feature', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-Jl8TBo","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="Jl8TBo"><section class="wp-block-gutenverse-section guten-element guten-section guten-Jl8TBo layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":49.912},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-EGSuUO","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-EGSuUO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="EGSuUO"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-9h88ad","imgSrc":{"media":{"imageId":1145,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/floor-interior-home-ceiling-loft-office-1390062-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/floor-interior-home-ceiling-loft-office-1390062-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/floor-interior-home-ceiling-loft-office-1390062-pxhere.com-1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( INTRACE_URI ) . 'assets/img/floor-interior-home-ceiling-loft-office-1390062-pxhere.com.webp","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"700","unit":"px"},"Tablet":{"point":"451","unit":"px"},"Mobile":{"point":"382","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"20","left":"10"}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-9h88ad animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( INTRACE_URI ) . 'assets/img/floor-interior-home-ceiling-loft-office-1390062-pxhere.com.webp" height="1280" width="1920"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50.08,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-DjspGP","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DjspGP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DjspGP"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-dasmft","background":{"type":"default","color":{"type":"variable","id":"white"}},"backgroundHover":{},"border":{"radius":{"Desktop":[]}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"30","spread":"0","color":{"r":1,"g":1,"b":1,"a":0.1}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","left":"-60","right":"60","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","left":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="dasmft"><section class="wp-block-gutenverse-section guten-element guten-section guten-dasmft animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-hJ48Cg","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hJ48Cg"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hJ48Cg"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-bLQgca","type":5,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.1"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-bLQgca">Welcome to Intrace</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-OQmLN1","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"42"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-OQmLN1">Innovative ideas stylish designs</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-TEpLc5","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"6"}}},"padding":{"Desktop":{},"Mobile":[]}} -->
<div class="guten-element gutenverse-text-editor guten-TEpLc5"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-D4Na6k","content":"Read more","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"}} -->
<div class="guten-element guten-button-wrapper guten-D4Na6k"><a class="guten-button guten-button-sm" href="#"><span>Read more</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-qkRuSm","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"0"}},"Tablet":{"unit":"%","dimension":{"top":"10","bottom":"0","right":"0","left":"-110"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"16","bottom":"0","left":"16"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="qkRuSm"><section class="wp-block-gutenverse-section guten-element guten-section guten-qkRuSm layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-0ZvMLr","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":[],"Desktop":{}},"padding":{"Tablet":[],"Mobile":[],"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0ZvMLr animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0ZvMLr"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-W8dDts","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":{},"Tablet":[]}},"iconSize":{"Tablet":""},"iconPadding":{"Desktop":{},"Tablet":[]},"iconMargin":{"Desktop":{},"Tablet":[]},"prefix":"","number":"25","suffix":"+","title":"Years of Experience","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Tablet":"-5"},"titleBottomSpace":{"Tablet":""},"contentPadding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":""}},"Mobile":[]}} -->
<div class="guten-element guten-W8dDts guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="25" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Years of Experience</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-bxg50J","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":[],"Desktop":{}},"padding":{"Tablet":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"900"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bxg50J animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bxg50J"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-ldzwPG","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"prefix":"","number":"1,250","suffix":"+","title":"Projects Completed","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Tablet":"-5"},"contentPadding":{"Desktop":{},"Tablet":[],"Mobile":[]}} -->
<div class="guten-element guten-ldzwPG guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="1,250" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Projects Completed</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
