<?php
/**
 * Gutenverse Home CTA content.
 */
return array(
	'title'      => __( 'Gutenverse Home CTA', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-dbhktv","verticalAlign":"center","background":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"60","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"10","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="dbhktv"><section class="wp-block-gutenverse-section guten-element guten-section guten-dbhktv layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Tablet":60},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-PmosRe","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PmosRe"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PmosRe"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-RmkPwP","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h2-cta-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-RmkPwP animated guten-element-hide desktop-fadeInLeft">Ready To Start New Project With Intrace?</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-3nbJmj","columns":{"Desktop":"1"},"gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text-2"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"60","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-3nbJmj animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40,"Tablet":40},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-EemkVQ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-EemkVQ animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="EemkVQ"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-a6LBcz","content":"Contact Us","alignButton":{"Desktop":"right","Mobile":"center","Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":24,"g":24,"b":24,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","color":{"type":"variable","id":"white"},"width":"1"}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"white"}}},"border":{"radius":{"Desktop":{}}},"borderHover":{"radius":{"Desktop":{}}},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"}} -->
<div class="guten-element guten-button-wrapper guten-a6LBcz"><a class="guten-button guten-button-sm" href="#"><span>Contact Us</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
