<?php
/**
 * Gutenverse Home Fun Fact content.
 */
return array(
	'title'      => __( 'Gutenverse Home Fun Fact', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-vtuMLQ","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"380","bottom":"0"}},"Tablet":{"unit":"%","dimension":{"top":"55","bottom":"0","right":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"top":"120","right":"","bottom":"0","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","left":"10","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"zIndex":{"Mobile":""},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="vtuMLQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-vtuMLQ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-TVlAqf","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TVlAqf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TVlAqf"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"elementId":"guten-RPuez5","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="RPuez5"><section class="wp-block-gutenverse-section guten-element guten-section guten-RPuez5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-BEmmqp","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-BEmmqp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BEmmqp"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-4SGq63","iconType":"none","iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"prefix":"","number":"25","suffix":"+","title":"Years of Experience","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{},"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-4SGq63 animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="25" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Years of Experience</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-VVUBqb","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VVUBqb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VVUBqb"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-MHS0qu","iconType":"none","iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"prefix":"","number":"1,250","suffix":"+","title":"Projects Completed","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-MHS0qu animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="1,250" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Projects Completed</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-sXdd21","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sXdd21"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sXdd21"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-swuTCt","iconType":"none","iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"prefix":"","number":"45","suffix":"+","title":"Awwards Winning","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{},"Mobile":[],"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-swuTCt animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="45" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Awwards Winning</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-n4dsqr","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"zIndex":{"Mobile":""},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-n4dsqr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="n4dsqr"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-OvX2Hw","iconType":"none","iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"prefix":"","number":"35","suffix":"+","title":"Professional Team","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<div class="guten-element guten-OvX2Hw animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="35" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Professional Team</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-v4QA1y","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-100","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","left":"","bottom":""}}},"animation":{},"hideMobile":true,"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="v4QA1y"><section class="wp-block-gutenverse-section guten-element guten-section guten-v4QA1y hide-mobile layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-tUTHh9","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"0"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tUTHh9"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="tUTHh9"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-WBqD4v","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"accent-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"98"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"textShadow":{"horizontal":"0","vertical":"0","blur":"1","color":{"r":1,"g":1,"b":1,"a":0.3}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Desktop":[],"Tablet":[]},"zIndex":{"Mobile":"0","Desktop":""},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"400"},"hideTablet":false,"hideMobile":true,"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-start"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"-5","unit":"px"}},"positioningRight":{"Desktop":{"point":"5","unit":"px"}},"positioningTop":{"Desktop":{"point":"-49","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-WBqD4v animated guten-element-hide desktop-fadeIn hide-mobile">achievement</h2>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
