<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Us', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-ClCmkW","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="ClCmkW"><section class="wp-block-gutenverse-section guten-element guten-section guten-ClCmkW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-S5Bv0G","background":{"type":"default","color":{"type":"variable","id":"white"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":[]}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"20","spread":"0","color":{"r":1,"g":1,"b":1,"a":0.1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-S5Bv0G animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="S5Bv0G"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-eYTuM9","hideAfterSubmit":false,"margin":{"Tablet":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-eYTuM9" data-hide-after="false"><!-- wp:gutenverse/form-input-text {"elementId":"guten-oL8Hgj","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"12","bottom":"10","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1"}},"inputColorHover":{"Desktop":[]},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBgColorHover":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-oL8Hgj hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-rthzO7","showLabel":false,"inputPlaceholder":"Your Email","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"12","bottom":"10","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1"}},"inputColorHover":{"Desktop":[]},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBgColorHover":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-rthzO7 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-jaCw7N","showLabel":false,"inputPlaceholder":"Your Subject","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"12","bottom":"10","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":""}},"inputColorHover":{"Desktop":[]},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBgColorHover":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-jaCw7N hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-QQDDhH","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputHeight":{"Desktop":"176"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"6","right":"12","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"color":"","type":"solid","width":"1"}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"color":{"type":"variable","id":"intrace-primary"},"type":"solid","width":"1"}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"color":{"type":"variable","id":"intrace-primary"},"type":"solid","width":"1"}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-QQDDhH hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/button {"elementId":"guten-N94Rza","content":"Send Message","buttonWidth":{"Desktop":""},"alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"32","bottom":"20","left":"32"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-hero-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"}} -->
<div class="guten-element guten-button-wrapper guten-N94Rza"><a class="guten-button guten-button-sm" href="#"><span>Send Message</span></a></div>
<!-- /wp:gutenverse/button --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-nLuSof","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"","left":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nLuSof"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nLuSof"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-7gNhi7","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-alt-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-7gNhi7 animated guten-element-hide desktop-fadeInRight">Get in touch</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-2t2CRP","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"6"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"animation":{"type":{"Desktop":"fadeInRight"},"delay":"300","duration":"normal"}} -->
<div class="guten-element gutenverse-text-editor guten-2t2CRP animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/google-maps {"elementId":"guten-9NxnX6","location":"renon","zoom":"17","height":{"Desktop":"300"},"mapFilter":{"blur":"0","brightness":"100","contrast":"100","saturation":"0","hue":"360"},"border":{"radius":{"Desktop":{}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-maps guten-9NxnX6 animated guten-element-hide desktop-fadeInRight"><iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=renon&amp;z=17&amp;t=m&amp;output=embed&amp;iwloc=near" title="renon"></iframe></div>
<!-- /wp:gutenverse/google-maps -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-THWG1X","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="THWG1X"><section class="wp-block-gutenverse-section guten-element guten-section guten-THWG1X layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Cl47t1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Cl47t1 animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Cl47t1"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-3CN8uB","textColor":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"6"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-3CN8uB"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Ubud, Bali</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-42QMFs","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"intrace-accent"},"iconSize":{"Tablet":"14","Mobile":"14"},"textColor":{"type":"variable","id":"intrace-body-text"},"textIndent":{"Mobile":"10","Desktop":"10"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-icon-list guten-42QMFs"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-n9cKcb"} -->
<div class="guten-element guten-icon-list-item guten-n9cKcb"><a id="guten-n9cKcb"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 81 2345 1234</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-cKB64d"} -->
<div class="guten-element guten-icon-list-item guten-cKB64d"><a id="guten-cKB64d"><i class="fas fa-envelope"></i><span class="list-text ">Contact@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-yQq9tC"} -->
<div class="guten-element guten-icon-list-item guten-yQq9tC"><a id="guten-yQq9tC"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Raya Ubud No.88, Bali 80571</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-EEO4TN","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"900"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-EEO4TN animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="EEO4TN"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-t7io2W","textColor":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"6","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-t7io2W"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Denpasar, Bali</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-Hfgk3i","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"intrace-accent"},"iconSize":{"Tablet":"14"},"textColor":{"type":"variable","id":"intrace-primary"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"}} -->
<div class="guten-element guten-icon-list guten-Hfgk3i"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-kjJn5P"} -->
<div class="guten-element guten-icon-list-item guten-kjJn5P"><a id="guten-kjJn5P"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 81 2175 1298</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-y1fVLm"} -->
<div class="guten-element guten-icon-list-item guten-y1fVLm"><a id="guten-y1fVLm"><i class="fas fa-envelope"></i><span class="list-text ">Contact@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-yDo138"} -->
<div class="guten-element guten-icon-list-item guten-yDo138"><a id="guten-yDo138"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Niti Mandala, Renon, Bali 80225</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
