<?php
/**
 * Gutenverse Home About 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Home About 2', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-tCOlqI","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","left":"10","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","left":"10","bottom":"40"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="tCOlqI"><section class="wp-block-gutenverse-section guten-element guten-section guten-tCOlqI layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-bGOpBl","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"60","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"10","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bGOpBl animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bGOpBl"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-GqpPRO","type":5,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.1"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-GqpPRO animated guten-element-hide desktop-fadeInLeft">Awward Winning</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-WbIqHf","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"42"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-WbIqHf">Interior Design</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-W5WFOg","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"6","top":"6","right":"6","left":"6"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<div class="guten-element gutenverse-text-editor guten-W5WFOg"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/image {"elementId":"guten-uZoDhW","imgSrc":{"media":{"imageId":98,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/Sign-150x150.webp","orientation":"landscape"},"medium":{"height":55,"width":300,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/Sign-300x55.webp","orientation":"landscape"},"large":{"height":187,"width":1024,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/Sign-1024x187.webp","orientation":"landscape"},"full":{"url":"' . esc_url( INTRACE_URI ) . 'assets/img/Sign.webp","height":264,"width":1448,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"45"},"Mobile":{"unit":"%","point":"65"},"Tablet":{"unit":"%","point":"65"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"align":{"Desktop":"left","Mobile":"center"},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-uZoDhW"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( INTRACE_URI ) . 'assets/img/Sign.webp" height="264" width="1448"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-bPA5Bo","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<div class="guten-element gutenverse-text-editor guten-bPA5Bo"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Jonathan Doe, CEO</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-CUPXE2","content":"Read more","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Mobile":[],"Tablet":{}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":"1","type":"solid","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"}} -->
<div class="guten-element guten-button-wrapper guten-CUPXE2"><a class="guten-button guten-button-sm" href="#"><span>Read more</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-DrUcl9","background":{"type":"default"},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":""},"animation":{},"hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DrUcl9"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DrUcl9"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-vcyyIJ","imgSrc":{"media":{"imageId":1137,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com002d002d150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com002d002d300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com002d002d1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com.webp","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"412","unit":"px"},"Tablet":{"point":"265","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"},"hideMobile":true,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-vcyyIJ animated guten-element-hide desktop-fadeInRight hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com.webp" height="1280" width="1920"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{"Desktop":{"point":"160","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}},"gap":"no","elementId":"guten-seeatL","heightControl":"min","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-29","left":"-50","bottom":"0","right":"29"}},"Tablet":{"unit":"px","dimension":{"top":"12","right":"-152","left":"-108","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":"3"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="seeatL"><section class="wp-block-gutenverse-section guten-element guten-section guten-seeatL animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-bjtIhv","background":{"type":"default","color":{"type":"variable","id":"white"}},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":[]}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"10","spread":"0","color":{"r":1,"g":1,"b":1,"a":0.1}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"","right":"41","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"25","bottom":"25","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"25","bottom":"25","left":"25"}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bjtIhv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bjtIhv"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-qV5cs4","background":{},"backgroundHover":{},"border":{"radius":{"Desktop":{}}},"borderHover":{"radius":{"Desktop":{}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="qV5cs4"><section class="wp-block-gutenverse-section guten-element guten-section guten-qV5cs4 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-aYO2f8","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-aYO2f8"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="aYO2f8"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-fsYpaw","gap":{"Desktop":{"point":"","unit":"px"}},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Desktop":{}},"left":{"type":"solid","width":"2","color":{"type":"variable","id":"intrace-accent"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","left":"30","top":"15"}}}} -->
<div class="guten-element gutenverse-text-editor guten-fsYpaw"><div class="text-content-inner"><!-- wp:paragraph -->
<p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore”&nbsp;</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-kgqg8n","type":6,"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-kgqg8n">Jonathan Doe</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
