<?php
/**
 * Gutenverse Services CTA content.
 */
return array(
	'title'      => __( 'Gutenverse Services CTA', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-kN1ju0","background":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"10","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="kN1ju0"><section class="wp-block-gutenverse-section guten-element guten-section guten-kN1ju0 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-D7TxFh","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Mobile":[]}},"margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"70","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"80","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-D7TxFh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="D7TxFh"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-uRoRMR","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h2-alt-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-uRoRMR animated guten-element-hide desktop-fadeInLeft">Get in touch</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-ZYJmE3","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"6"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="guten-element gutenverse-text-editor guten-ZYJmE3 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Z0fG5n","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"6"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="guten-element gutenverse-text-editor guten-Z0fG5n animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Ubud, Bali</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-OjSZVI","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"intrace-accent"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="guten-element guten-icon-list guten-OjSZVI animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-YfO1jy"} -->
<div class="guten-element guten-icon-list-item guten-YfO1jy"><a id="guten-YfO1jy"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 81 2345 1234</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-0Eew3L"} -->
<div class="guten-element guten-icon-list-item guten-0Eew3L"><a id="guten-0Eew3L"><i class="fas fa-envelope"></i><span class="list-text ">Contact@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-kV7Vr1"} -->
<div class="guten-element guten-icon-list-item guten-kV7Vr1"><a id="guten-kV7Vr1"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Raya Ubud No.88, Bali 80571</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-VTG9zW","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"6"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"}} -->
<div class="guten-element gutenverse-text-editor guten-VTG9zW animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Denpasar, Bali</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-CjmqYd","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"intrace-accent"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-icon-list guten-CjmqYd animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-GVmZHM"} -->
<div class="guten-element guten-icon-list-item guten-GVmZHM"><a id="guten-GVmZHM"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 81 2345 1234</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-w1T91K"} -->
<div class="guten-element guten-icon-list-item guten-w1T91K"><a id="guten-w1T91K"><i class="fas fa-envelope"></i><span class="list-text ">Contact@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-sayjdr"} -->
<div class="guten-element guten-icon-list-item guten-sayjdr"><a id="guten-sayjdr"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Niti Mandala, Renon, Bali 80225</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-VhFGq6","background":{"type":"default","color":{"type":"variable","id":"white"}},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VhFGq6 animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VhFGq6"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-eYTuM9","hideAfterSubmit":false,"successPadding":{"Desktop":{}},"successBorder":{"radius":{"Desktop":{}}},"errorPadding":{"Desktop":{}},"errorBorder":{"radius":{"Desktop":{}}},"border":{"radius":{"Desktop":{}}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-eYTuM9" data-hide-after="false"><!-- wp:gutenverse/form-input-text {"elementId":"guten-oL8Hgj","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"12","bottom":"10","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1"}},"inputColorHover":{"Desktop":[]},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBgColorHover":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-oL8Hgj hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-rthzO7","showLabel":false,"inputPlaceholder":"Your Email","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"12","bottom":"10","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1"}},"inputColorHover":{"Desktop":[]},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBgColorHover":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-rthzO7 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-jaCw7N","showLabel":false,"inputPlaceholder":"Your Subject","showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"12","bottom":"10","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":""}},"inputColorHover":{"Desktop":[]},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"inputBgColorHover":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-jaCw7N hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-QQDDhH","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"helperPadding":{"Desktop":{}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputHeight":{"Desktop":"176"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"6","right":"12","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"intrace-primary"}},"inputBorderNormal":{"radius":{"Desktop":{}},"all":{"color":"","type":"solid","width":"1"}},"inputBorderHover":{"radius":{"Desktop":{}},"all":{"color":{"type":"variable","id":"intrace-primary"},"type":"solid","width":"1"}},"inputBorderFocus":{"radius":{"Desktop":{}},"all":{"color":{"type":"variable","id":"intrace-primary"},"type":"solid","width":"1"}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-QQDDhH hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea --></form>
<!-- /wp:gutenverse/form-builder -->

<!-- wp:gutenverse/button {"elementId":"guten-N94Rza","content":"Send Message","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"32","bottom":"20","left":"32"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-hero-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"}} -->
<div class="guten-element guten-button-wrapper guten-N94Rza"><a class="guten-button guten-button-sm" href="#"><span>Send Message</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
