<?php
/**
 * Gutenverse Home Client Logo content.
 */
return array(
	'title'      => __( 'Gutenverse Home Client Logo', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{"Desktop":{"point":"","unit":"px"}},"gap":"no","elementId":"guten-QqvXAT","heightControl":"min","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="QqvXAT"><section class="wp-block-gutenverse-section guten-element guten-section guten-QqvXAT layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-889Ltw","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"45","bottom":"45"}}},"padding":{"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-889Ltw"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="889Ltw"><div class="guten-column-wrapper"><!-- wp:gutenverse/logo-slider {"elementId":"guten-r0fre3","logos":[{"title":"One","_key":"BmkMJW","src":{"id":1107,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-5.webp"},"hoverSrc":[]},{"title":"Two","_key":"3GBWkE","src":{"id":1108,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-4.webp"},"hoverSrc":[]},{"title":"Three","_key":"YqsvFO","src":{"id":1109,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum.webp"},"hoverSrc":[]},{"title":"four","src":{"id":1110,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-2.webp"},"hoverSrc":[],"_key":"1rrw1e"},{"title":"Five","src":{"id":1111,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-3.webp"},"hoverSrc":[],"_key":"OYugX6"}],"imageHeight":{"Desktop":""},"imageFit":{"Desktop":"cover"},"imagePadding":{"Desktop":{"unit":"px","dimension":{"top":"52","right":"52","bottom":"52","left":"52"}},"Tablet":{"unit":"%","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageHoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"52","right":"52","bottom":"52","left":"52"}},"Tablet":{"unit":"%","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageHoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"imageBorderHover":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"spacing":{"Desktop":"1","Tablet":"0","Mobile":""},"itemShowed":{"Desktop":"4","Tablet":"3","Mobile":"2"},"loop":true,"dotsRadius":{"Desktop":[]},"arrowFontSize":{"Desktop":""},"arrowPadding":{"Desktop":[],"Mobile":[]},"arrowMargin":{"Desktop":[],"Mobile":[]},"arrowHoverPadding":{"Desktop":[]},"arrowHoverMargin":{"Desktop":[]},"arrowBorder":{"radius":{"Desktop":[],"Mobile":[]}},"arrowBorderHover":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"opacity":"0.3","hoverOpacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-r0fre3 animated guten-element-hide desktop-fadeInUp arrow-bottom-edge"><div class="client-list"><div id="guten-r0fre3" class="swiper-container" data-loop="true" data-autoplay="false" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:10,&quot;slidesPerView&quot;:2},&quot;768&quot;:{&quot;spaceBetween&quot;:0,&quot;slidesPerView&quot;:3},&quot;1024&quot;:{&quot;spaceBetween&quot;:1,&quot;slidesPerView&quot;:4}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-5.webp" alt="One"/><img class="hover-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-5.webp" alt="One"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-4.webp" alt="Two"/><img class="hover-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-4.webp" alt="Two"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum.webp" alt="Three"/><img class="hover-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum.webp" alt="Three"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-2.webp" alt="four"/><img class="hover-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-2.webp" alt="four"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-3.webp" alt="Five"/><img class="hover-image" src="' . esc_url( INTRACE_URI ) . 'assets/img/Logoipsum-3.webp" alt="Five"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
