<?php
/**
 * Gutenverse Project Detail Feature 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Project Detail Feature 2', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-zFAwC3","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"60","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"40","right":"10","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="zFAwC3"><section class="wp-block-gutenverse-section guten-element guten-section guten-zFAwC3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":40,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-2GEjWW","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-2GEjWW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="2GEjWW"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-VLrO17","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-alt-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-VLrO17 animated guten-element-hide desktop-fadeInLeft">Project Info</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-SpUtno","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"6"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="guten-element gutenverse-text-editor guten-SpUtno animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-3SwZBQ","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="3SwZBQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-3SwZBQ animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-0lSzaQ","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0lSzaQ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0lSzaQ"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Nytg2n","title":"Client","titleTag":"h3","description":"Pablo Chaesar","icon":"gtn gtn-users2-light","iconSize":{"Desktop":"30","Tablet":"30","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{}},"containerBorder":{"radius":{"Desktop":{},"Mobile":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{},"Mobile":[]},"iconMargin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"-5"}}},"iconColor":{"type":"variable","id":"intrace-accent"},"iconBorder":{"radius":{"Desktop":{},"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":""}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"badgePadding":{"Desktop":{}},"badgeRadius":{"Desktop":{}}} -->
<div class="guten-element guten-Nytg2n guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-users2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Client</h3><p class="icon-box-description">Pablo Chaesar</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-fKGFra","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fKGFra"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="fKGFra"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-GIlKJ4","title":"Location","titleTag":"h3","description":"Seminyak, Kuta","icon":"gtn gtn-map-marker1-light","iconSize":{"Desktop":"30","Tablet":"30","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{},"Mobile":[]},"iconMargin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"-5"}}},"iconColor":{"type":"variable","id":"intrace-accent"},"iconBorder":{"radius":{"Desktop":{},"Mobile":[]}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"}} -->
<div class="guten-element guten-GIlKJ4 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-map-marker1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Location</h3><p class="icon-box-description">Seminyak, Kuta</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-Ca0odV","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="Ca0odV"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ca0odV animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-S8IbZP","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-S8IbZP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="S8IbZP"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-OjsS6C","title":"Project Year","titleTag":"h3","description":"2019","icon":"gtn gtn-calendar-light","iconSize":{"Desktop":"30","Tablet":"30","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{},"Mobile":[]},"iconMargin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"-5"}}},"iconColor":{"type":"variable","id":"intrace-accent"},"iconBorder":{"radius":{"Desktop":{},"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"}} -->
<div class="guten-element guten-OjsS6C guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-calendar-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Project Year</h3><p class="icon-box-description">2019</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-8QAE9P","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8QAE9P"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8QAE9P"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-8toBjT","title":"Price Value","titleTag":"h3","description":"$250.000","icon":"gtn gtn-money-bag1-light","iconSize":{"Desktop":"30","Tablet":"30","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[],"Mobile":[]},"iconMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"-5"}}},"iconColor":{"r":173,"g":146,"b":113,"a":1},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"","left":""}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"}} -->
<div class="guten-element guten-8toBjT guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-money-bag1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Price Value</h3><p class="icon-box-description">$250.000</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-WIMiWg","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="WIMiWg"><section class="wp-block-gutenverse-section guten-element guten-section guten-WIMiWg animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-deDqum","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-deDqum"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="deDqum"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Q98fDT","title":"Surface Area","titleTag":"h3","description":"400,000 m2","icon":"gtn gtn-apartment-light","iconSize":{"Desktop":"30","Tablet":"30","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{},"Mobile":[]},"iconMargin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"-5"}}},"iconColor":{"type":"variable","id":"intrace-accent"},"iconBorder":{"radius":{"Desktop":{},"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"}} -->
<div class="guten-element guten-Q98fDT guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-apartment-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Surface Area</h3><p class="icon-box-description">400,000 m2</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-QvYV4G","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QvYV4G"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QvYV4G"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-zNq36c","title":"Project Head","titleTag":"h3","description":"Maximus Holden","icon":"gtn gtn-user-1-light","iconSize":{"Desktop":"30","Tablet":"30","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":{},"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{},"Mobile":[]},"iconMargin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"-5"}}},"iconColor":{"type":"variable","id":"intrace-accent"},"iconBorder":{"radius":{"Desktop":{},"Mobile":[]}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"}} -->
<div class="guten-element guten-zNq36c guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-user-1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Project Head</h3><p class="icon-box-description">Maximus Holden</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":60,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-2knbig","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"30","top":""}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-2knbig"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="2knbig"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-0sfW6I","color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-alt-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-0sfW6I animated guten-element-hide desktop-fadeInRight">Project Description</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-psMnSs","textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"6","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":{"unit":"%","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"}} -->
<div class="guten-element gutenverse-text-editor guten-psMnSs animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation mco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in nderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur caecat cupidatat non proident, sunt in culpa qui officia deserunt mollit &nbsp;qui officia deserunt mollit </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-VBEi5s","spaceBetween":{"Desktop":"10","Mobile":"10"},"iconColor":{"type":"variable","id":"intrace-accent"},"iconSize":{"Desktop":"14","Mobile":"14"},"textColor":{"type":"variable","id":"intrace-body-text"},"textIndent":{"Desktop":"10","Mobile":"5"},"textTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-icon-list guten-VBEi5s animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-LwrdIR","margin":{"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":""}}}} -->
<div class="guten-element guten-icon-list-item guten-LwrdIR"><a id="guten-LwrdIR"><i class="fas fa-check"></i><span class="list-text ">Lorem ipsum dolor sit amet, consectetur adipi</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-DxzGxj"} -->
<div class="guten-element guten-icon-list-item guten-DxzGxj"><a id="guten-DxzGxj"><i class="fas fa-check"></i><span class="list-text ">Lorem ipsum dolor sit amet, consectetur </span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-LqztHE"} -->
<div class="guten-element guten-icon-list-item guten-LqztHE"><a id="guten-LqztHE"><i class="fas fa-check"></i><span class="list-text ">Lorem ipsum dolor sit amet, consec</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
