<?php
/**
 * Gutenverse Services Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Services Section 3', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-dPYd3w","background":{"type":"default","color":{"type":"variable","id":"intrace-background"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"10","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="dPYd3w"><section class="wp-block-gutenverse-section guten-element guten-section guten-dPYd3w layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-xa6R4C","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50"}},"Tablet":{"unit":"px","dimension":{"right":"60","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xa6R4C"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="xa6R4C"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-HnCdOO","type":5,"textAlign":{"Desktop":"left","Tablet":"left","Mobile":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.1"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"15","right":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-HnCdOO animated guten-element-hide desktop-fadeInLeft">Approach</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-tVF7VO","textAlign":{"Tablet":"left","Mobile":"center"},"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-alt-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-tVF7VO animated guten-element-hide desktop-fadeInLeft">How We work</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-gsc4Ku","alignment":{"Tablet":"left","Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="guten-element gutenverse-text-editor guten-gsc4Ku animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-V5vqPM","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="V5vqPM"><section class="wp-block-gutenverse-section guten-element guten-section guten-V5vqPM animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":27.273,"Tablet":27.273},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-WB0Wuw","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-WB0Wuw"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WB0Wuw"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-GSQGaO","textAlign":{"Tablet":"center","Mobile":"center"},"color":{"r":248,"g":248,"b":248,"a":1},"typography":{"type":"variable","id":"accent-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"98"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"textShadow":{"horizontal":"0","vertical":"0","blur":"2","color":{"r":1,"g":1,"b":1,"a":0.3}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-GSQGaO">01</h2>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":72.72},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-5tERCI","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5tERCI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5tERCI"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-R0wNFj","title":"Concept","titleTag":"h3","iconType":"none","align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"badgePadding":{"Tablet":[]},"badgeRadius":{"Tablet":[]}} -->
<div class="guten-element guten-R0wNFj guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Concept</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-0ca48e","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="0ca48e"><section class="wp-block-gutenverse-section guten-element guten-section guten-0ca48e animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":27.28},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-gkfD77","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-gkfD77"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="gkfD77"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-8xkwAW","textAlign":{"Tablet":"center"},"color":{"r":248,"g":248,"b":248,"a":1},"typography":{"type":"variable","id":"accent-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"98"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"textShadow":{"horizontal":"0","vertical":"0","blur":"2","color":{"r":1,"g":1,"b":1,"a":0.3}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-8xkwAW">02</h2>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":72.72},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-S2teiA","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-S2teiA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="S2teiA"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-4ozJ3C","title":"Design","titleTag":"h3","iconType":"none","align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"}} -->
<div class="guten-element guten-4ozJ3C guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Design</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-ropjfM","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="ropjfM"><section class="wp-block-gutenverse-section guten-element guten-section guten-ropjfM animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":27.28},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-CvSrrI","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CvSrrI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="CvSrrI"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-QDTekS","textAlign":{"Tablet":"center"},"color":{"r":248,"g":248,"b":248,"a":1},"typography":{"type":"variable","id":"accent-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"98"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"textShadow":{"horizontal":"0","vertical":"0","blur":"2","color":{"r":1,"g":1,"b":1,"a":0.3}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-QDTekS">03</h2>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":72.72},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-d92Asy","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-d92Asy"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="d92Asy"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-J3ICFz","title":"Development","titleTag":"h3","iconType":"none","align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"titlePadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"intrace-body-text"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<div class="guten-element guten-J3ICFz guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Development</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-T9shTU","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Tablet":[],"Mobile":[]},"padding":{"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"},"hideTablet":true,"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-T9shTU animated guten-element-hide desktop-fadeInRight hide-tablet hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="T9shTU"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-eGMVVE","imgSrc":{"media":{"imageId":1154,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com-1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com.webp","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","height":{"Desktop":{"point":"630","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[]}},"align":{"Desktop":null},"imageFit":{"Desktop":"cover"},"hideTablet":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-eGMVVE hide-tablet"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( INTRACE_URI ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com.webp" height="1280" width="1920"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
