<?php
/**
 * Gutenverse About Funfact content.
 */
return array(
	'title'      => __( 'Gutenverse About Funfact', 'photology' ),
	'categories' => array( 'photology-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-NZ6UpQ","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}},"color":{"type":"variable","id":"photology-bg-grey"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"r":247,"g":247,"b":247,"a":1}},"opacity":"0.8","topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="NZ6UpQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-NZ6UpQ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-VPWcpM","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VPWcpM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VPWcpM"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-KWcV1a","icon":"gtn gtn-users1-light","iconColor":{"Desktop":{"type":"variable","id":"photology-brown"}},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"prefix":"","number":"1620","suffix":"","title":"Happy Customer","showSupper":true,"superColor":{"type":"variable","id":"photology-brown"},"superTypography":{"type":"variable","id":"h3-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"superTop":{"Desktop":"8"},"numberColor":{"Desktop":{"type":"variable","id":"photology-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"photology-text"}},"numberTypography":{"type":"variable","id":"number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"titleTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"numberBottomSpace":{"Desktop":"8"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":{}},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="guten-element guten-KWcV1a animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-users1-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="1620" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Happy Customer</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-kb9cqs","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kb9cqs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="kb9cqs"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-KSfGij","icon":"gtn gtn-photo-camera1-light","iconColor":{"Desktop":{"type":"variable","id":"photology-brown"}},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"prefix":"","number":"3640","suffix":"","title":"Photos Taken","showSupper":true,"superColor":{"type":"variable","id":"photology-brown"},"superTypography":{"type":"variable","id":"h3-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"superTop":{"Desktop":"8"},"numberColor":{"Desktop":{"type":"variable","id":"photology-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"photology-text"}},"numberTypography":{"type":"variable","id":"number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"titleTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"numberBottomSpace":{"Desktop":"8"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-KSfGij animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-photo-camera1-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="3640" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Photos Taken</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-GzvcJu","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GzvcJu"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GzvcJu"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-PKCEj2","icon":"gtn gtn-trophy-light","iconColor":{"Desktop":{"type":"variable","id":"photology-brown"}},"iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"prefix":"","number":"86","suffix":"","title":"Awward Winning","showSupper":true,"superColor":{"type":"variable","id":"photology-brown"},"superTypography":{"type":"variable","id":"h3-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"superTop":{"Desktop":"8"},"numberColor":{"Desktop":{"type":"variable","id":"photology-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"photology-text"}},"numberTypography":{"type":"variable","id":"number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"titleTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"numberBottomSpace":{"Desktop":"8"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element guten-PKCEj2 animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-trophy-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="86" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Awward Winning</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-Wqs4UO","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Wqs4UO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Wqs4UO"><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-AtwGdH","icon":"gtn gtn-team-2-line","iconColor":{"Desktop":{"type":"variable","id":"photology-brown"}},"iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"prefix":"","number":"60","suffix":"","title":"Professional Team","showSupper":true,"superColor":{"type":"variable","id":"photology-brown"},"superTypography":{"type":"variable","id":"h3-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"superTop":{"Desktop":"8"},"numberColor":{"Desktop":{"type":"variable","id":"photology-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"photology-text"}},"numberTypography":{"type":"variable","id":"number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"titleTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"numberBottomSpace":{"Desktop":"8"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="guten-element guten-AtwGdH animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-2-line"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="60" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Professional Team</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
