<?php
/**
 * Gutenverse Team content.
 */
return array(
	'title'      => __( 'Gutenverse Team', 'photology' ),
	'categories' => array( 'photology-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"elementId":"guten-qPoZUy","background":{"type":"default","color":{"type":"variable","id":"photology-soft-grey"}},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"04"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="qPoZUy"><section class="wp-block-gutenverse-section guten-element guten-section guten-qPoZUy layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-5diNgc","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5diNgc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5diNgc"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-YFXmO3","verticalAlign":"center","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="YFXmO3"><section class="wp-block-gutenverse-section guten-element guten-section guten-YFXmO3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":55},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-Z0iiDd","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Z0iiDd"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Z0iiDd"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-DUjWqY","color":{"type":"variable","id":"photology-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"38"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-DUjWqY animated guten-element-hide desktop-fadeInLeft">Meet With Our Team</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-FKGMMb","color":{"type":"variable","id":"photology-quote"},"typography":{"type":"variable","id":"accent-big-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"140"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"40"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"600"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"-21"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-FKGMMb animated guten-element-hide desktop-fadeInRight">Awesome</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-3YqoPh","textColor":{"type":"variable","id":"photology-text"},"typography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-3YqoPh animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":45},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-YGZaTN","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YGZaTN"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="YGZaTN"><div class="guten-column-wrapper"></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-vlxMbc","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"50"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<div class="section-wrapper" data-id="vlxMbc"><section class="wp-block-gutenverse-section guten-element guten-section guten-vlxMbc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.3},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-1FG9jh","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1FG9jh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1FG9jh"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-a7FOuc","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":70,"image":"' . esc_url( PHOTOLOGY_URI ) . 'assets/img/hand-man-person-camera-photography-photographer-150687-pxhere.com.jpg"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"profileBorderHover":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverBgColor":{"type":"variable","id":"photology-overlay"}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-a7FOuc animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( PHOTOLOGY_URI ) . 'assets/img/hand-man-person-camera-photography-photographer-150687-pxhere.com.jpg" alt=""/><div class="profile-body center"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-V0m3zR","iconSize":{"Desktop":{"point":"16","unit":"px"}},"gap":{"Desktop":"16","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"photology-secondary"},"bgColor":{"type":"variable","id":"photology-brown"},"hoverIconColor":{"type":"variable","id":"photology-brown"},"hoverBgColor":{"type":"variable","id":"photology-secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-60","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-V0m3zR circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-yodz1F"} -->
<div class="guten-element guten-social-icon guten-yodz1F facebook"><a id="guten-yodz1F"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-Vw0xFf"} -->
<div class="guten-element guten-social-icon guten-Vw0xFf twitter"><a id="guten-Vw0xFf"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-xXTBxw"} -->
<div class="guten-element guten-social-icon guten-xXTBxw instagram"><a id="guten-xXTBxw"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/heading {"elementId":"guten-NkVrOm","type":3,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"photology-primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-NkVrOm">Javier Hooper</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-xM08fL","type":6,"textAlign":{"Desktop":"center","Tablet":null,"Mobile":"center"},"color":{"type":"variable","id":"photology-text"},"typography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-5"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-xM08fL">Photographer</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-NPOCo1","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NPOCo1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="NPOCo1"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-DY9LyI","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":71,"image":"' . esc_url( PHOTOLOGY_URI ) . 'assets/img/photograph-snapshot-jacket-photographer-photography-cool-1557473-pxhere.com.jpg"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"profileBorderHover":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverBgColor":{"type":"variable","id":"photology-overlay"}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-DY9LyI animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( PHOTOLOGY_URI ) . 'assets/img/photograph-snapshot-jacket-photographer-photography-cool-1557473-pxhere.com.jpg" alt=""/><div class="profile-body center"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-LtzN7M","iconSize":{"Desktop":{"point":"16","unit":"px"}},"gap":{"Desktop":"16","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"photology-secondary"},"bgColor":{"type":"variable","id":"photology-brown"},"itemPadding":{"Desktop":{}},"hoverIconColor":{"type":"variable","id":"photology-brown"},"hoverBgColor":{"type":"variable","id":"photology-secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-60","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-LtzN7M circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-e75jTq"} -->
<div class="guten-element guten-social-icon guten-e75jTq facebook"><a id="guten-e75jTq"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-O9Qp45"} -->
<div class="guten-element guten-social-icon guten-O9Qp45 twitter"><a id="guten-O9Qp45"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-sNXckr"} -->
<div class="guten-element guten-social-icon guten-sNXckr instagram"><a id="guten-sNXckr"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/heading {"elementId":"guten-ehuulL","type":3,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"photology-primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-ehuulL">Joanne Torres</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-KNiOih","type":6,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"photology-text"},"typography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-5"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-KNiOih">Photographer</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-lBu2Nz","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lBu2Nz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lBu2Nz"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-oVGK60","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":69,"image":"' . esc_url( PHOTOLOGY_URI ) . 'assets/img/hand-girl-hair-camera-photographer-pine-14200-pxhere.com.jpg"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"profileBorderHover":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverBgColor":{"type":"variable","id":"photology-overlay"}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-oVGK60 animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( PHOTOLOGY_URI ) . 'assets/img/hand-girl-hair-camera-photographer-pine-14200-pxhere.com.jpg" alt=""/><div class="profile-body center"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-abhqej","iconSize":{"Desktop":{"point":"16","unit":"px"}},"gap":{"Desktop":"16","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"photology-secondary"},"bgColor":{"type":"variable","id":"photology-brown"},"hoverIconColor":{"type":"variable","id":"photology-brown"},"hoverBgColor":{"type":"variable","id":"photology-secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-60","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-abhqej circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-r9krxF"} -->
<div class="guten-element guten-social-icon guten-r9krxF facebook"><a id="guten-r9krxF"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-ZB5ARa"} -->
<div class="guten-element guten-social-icon guten-ZB5ARa twitter"><a id="guten-ZB5ARa"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-jVFt93"} -->
<div class="guten-element guten-social-icon guten-jVFt93 instagram"><a id="guten-jVFt93"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/heading {"elementId":"guten-7K2JiE","type":3,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"photology-primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-7K2JiE">Lianne Hail</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-fl6dPZ","type":6,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"photology-text"},"typography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-5"}}},"padding":{"Desktop":{}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-fl6dPZ">Photographer</h6>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
