<?php
/**
 * Gutenverse Home Studies content.
 */
return array(
	'title'      => __( 'Gutenverse Home Studies', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-DCIHGY","background":{"type":"default","image":{"Desktop":{"id":447,"image":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/management-watch-personal-computer-laptop-computer-product-1637281-pxhere.com.webp"}},"color":"","position":{"Desktop":"top center"},"size":{"Desktop":"cover"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"r":30,"g":30,"b":30,"a":1}},"opacity":"0.8","topDivider":{},"bottomDivider":{},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80"}},"Mobile":{"unit":"px","dimension":{"top":"50"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="DCIHGY"><section class="wp-block-gutenverse-section guten-element guten-section guten-DCIHGY layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-D46z7W","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-D46z7W"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="D46z7W"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-rAXcd3","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"default"},"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"5","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-rAXcd3 animated guten-element-hide desktop-fadeInUp">Case Studies</h5>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-jZ3IRh","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"slideInUp"},"duration":"normal","delay":"80"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-jZ3IRh animated guten-element-hide desktop-slideInUp">Let’s See Our Latest Project</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-oA92ji","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"26","bottom":"0","left":"26"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"35","bottom":"0","left":"35"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"160"}} -->
			<div class="guten-element gutenverse-text-editor guten-oA92ji animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-u4KUuP","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"backgroundHover":{},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"horizontal":"0","vertical":"0","spread":"0","blur":"22","color":{"r":35,"g":25,"b":1,"a":0.09}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"-180","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"5","right":"10","bottom":"","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"25","bottom":"5","left":"25"}},"Mobile":{"unit":"px","dimension":{"right":""}}},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInUp","Mobile":"none"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="u4KUuP"><section class="wp-block-gutenverse-section guten-element guten-section guten-u4KUuP animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-uMa1vL","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-uMa1vL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="uMa1vL"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-2ybBZ3","imgSrc":{"media":{"imageId":433,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-brainstorming-business-businessman-businesswoman-collaboration-1455461-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-brainstorming-business-businessman-businesswoman-collaboration-1455461-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-brainstorming-business-businessman-businesswoman-collaboration-1455461-pxhere.com-1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-brainstorming-business-businessman-businesswoman-collaboration-1455461-pxhere.com.webp","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"px","point":""}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Tablet":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-2ybBZ3"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-brainstorming-business-businessman-businesswoman-collaboration-1455461-pxhere.com.webp" height="1280" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-box {"elementId":"guten-6nszhc","title":"Cashflow Forecasting","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","iconType":"none","icon":"gtn gtn-save-money-light","iconPosition":"left","align":{"Desktop":"flex-start","Tablet":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"20","left":"5"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"","left":""}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"18","left":""}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"left":"","bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"descColor":{"type":"variable","id":"forth"},"descTypography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="guten-element guten-6nszhc guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h2 class="title">Cashflow Forecasting</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p><!-- wp:gutenverse/button {"elementId":"guten-TL8Fij","content":"Read More","buttonWidth":{"Desktop":""},"alignButton":{"Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"Desktop":{"point":"11","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":[]},"color":{"type":"variable","id":"secondary"},"iconColor":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"button2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.1"},"weight":"500","transform":"uppercase"},"hoverIconColor":{"type":"variable","id":"primary"},"hoverTextColor":{"type":"variable","id":"primary"}} -->
			<div class="guten-element guten-button-wrapper guten-TL8Fij"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-0rWBqY","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-0rWBqY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0rWBqY"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-lbxMiJ","imgSrc":{"media":{"imageId":431,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/african-african-american-agenda-agreement-american-black-1431451-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":195,"width":300,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/african-african-american-agenda-agreement-american-black-1431451-pxhere.com-300x195.webp","orientation":"landscape"},"large":{"height":666,"width":1024,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/african-african-american-agenda-agreement-american-black-1431451-pxhere.com-1024x666.webp","orientation":"landscape"},"full":{"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/african-african-american-agenda-agreement-american-black-1431451-pxhere.com.webp","height":1248,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"px","point":""},"Tablet":{"unit":"%","point":""}},"height":{"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Tablet":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-lbxMiJ"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( ACCOUNTRA_URI ) . 'assets/img/african-african-american-agenda-agreement-american-black-1431451-pxhere.com.webp" height="1248" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-box {"elementId":"guten-U8Ejav","title":"Acquisitions \u0026amp; Mergers","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","iconType":"none","icon":"gtn gtn-save-money-light","iconPosition":"left","align":{"Desktop":"flex-start","Tablet":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"20","left":"5"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"","left":""}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"18","left":""}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"left":"","bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"descColor":{"type":"variable","id":"forth"},"descTypography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="guten-element guten-U8Ejav guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h2 class="title">Acquisitions &amp; Mergers</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p><!-- wp:gutenverse/button {"elementId":"guten-K6L3oH","content":"Read More","buttonWidth":{"Desktop":""},"alignButton":{"Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"Desktop":{"point":"11","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"color":{"type":"variable","id":"secondary"},"iconColor":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"button2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.1"},"weight":"500","transform":"uppercase"},"hoverIconColor":{"type":"variable","id":"primary"},"hoverTextColor":{"type":"variable","id":"primary"}} -->
			<div class="guten-element guten-button-wrapper guten-K6L3oH"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-n7Bqww","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-n7Bqww"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="n7Bqww"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-yNBZQX","imgSrc":{"media":{"imageId":429,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-business-chart-computer-connection-copy-space-1568883-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":195,"width":300,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-business-chart-computer-connection-copy-space-1568883-pxhere.com-300x195.webp","orientation":"landscape"},"large":{"height":667,"width":1024,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-business-chart-computer-connection-copy-space-1568883-pxhere.com-1024x667.webp","orientation":"landscape"},"full":{"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-business-chart-computer-connection-copy-space-1568883-pxhere.com.webp","height":1250,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"px","point":""}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-yNBZQX"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( ACCOUNTRA_URI ) . 'assets/img/analysis-business-chart-computer-connection-copy-space-1568883-pxhere.com.webp" height="1250" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-box {"elementId":"guten-tDITsT","title":"Company Budgeting","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","iconType":"none","icon":"gtn gtn-save-money-light","iconPosition":"left","align":{"Desktop":"flex-start","Tablet":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"20","left":"5"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"","left":""}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"18","left":""}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"left":"","bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"descColor":{"type":"variable","id":"forth"},"descTypography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="guten-element guten-tDITsT guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h2 class="title">Company Budgeting</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p><!-- wp:gutenverse/button {"elementId":"guten-PE9ecQ","content":"Read More","buttonWidth":{"Desktop":""},"alignButton":{"Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"Desktop":{"point":"11","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":[]},"color":{"type":"variable","id":"secondary"},"iconColor":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"button2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.1"},"weight":"500","transform":"uppercase"},"hoverIconColor":{"type":"variable","id":"primary"},"hoverTextColor":{"type":"variable","id":"primary"}} -->
			<div class="guten-element guten-button-wrapper guten-PE9ecQ"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
