<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":"890"},"height":{},"gap":"no","elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":75,"image":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com.webp"}},"color":"","size":{"Desktop":"cover","Tablet":"cover","Mobile":"cover"},"position":{"Desktop":"custom","Tablet":"center center","Mobile":"bottom left"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"45","unit":"px"}},"repeat":{"Tablet":"no-repeat"}},"backgroundHover":{},"backgroundOverlay":{"type":"default","color":{"r":26,"g":20,"b":20,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270,"image":{"Desktop":[]}},"opacity":"0.8","topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-180","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"400","bottom":"270"}},"Tablet":{"unit":"px","dimension":{"top":"380","bottom":"120","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"80","top":"320"}}},"zIndex":{"Desktop":"1"},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="P6sVWZ"><section class="wp-block-gutenverse-section guten-element guten-section guten-P6sVWZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-91Fk0O","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-91Fk0O"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="91Fk0O"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-cad3Cf","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="cad3Cf"><section class="wp-block-gutenverse-section guten-element guten-section guten-cad3Cf animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-CPw075","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-CPw075"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="CPw075"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-XvGz0E","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"h1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"background":{"type":"default"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-XvGz0E">Focus On Growing Your Business</h1>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/advanced-heading {"elementId":"guten-sAdGZx","alignText":{"Desktop":"center"},"text":"Trust The ","focusText":"Accounting","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"third"},"mainTypography":{"type":"variable","id":"h1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"mainMargin":{"Desktop":{},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"secondary"},"focusTypography":{"type":"variable","id":"h1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":""}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":{},"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-30","right":"","bottom":"","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline","Mobile":"default"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-sAdGZx"><div class="heading-section "><h2 class="heading-title">Trust The <span class="heading-focus">Accounting</span></h2></div></div>
			<!-- /wp:gutenverse/advanced-heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-uRMP2C","type":1,"textAlign":{"Desktop":"center","Mobile":"center"},"color":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"h1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"background":{"type":"default"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-18","right":"","bottom":"","left":"-45"}},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"60","left":"60"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"inline","Mobile":"default"},"positioningAlign":{"Desktop":"center"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-uRMP2C">To Us</h1>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-0iCbAc","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"20","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"18","left":"18","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"11","bottom":"0","left":"11"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-0iCbAc animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-y7Tk4t","verticalAlign":"center","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"5"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":{}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="y7Tk4t"><section class="wp-block-gutenverse-section guten-element guten-section guten-y7Tk4t layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-KNvoZB","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default","Mobile":"default"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KNvoZB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KNvoZB"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"Get A Quote","url":"#","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"25","bottom":"20","left":"25"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"40"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":"uppercase","weight":"500","transform":"uppercase"},"hoverTextColor":{"type":"variable","id":"primary"}} -->
			<div class="guten-element guten-button-wrapper guten-BTgZlT"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Get A Quote</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-MidhJF","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-MidhJF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MidhJF"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-Aplvqa","icon":"gtn gtn-play1-light","iconAlign":{"Mobile":"center"},"iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"19","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"0"},"iconColorTwo":{"type":"variable","id":"primary"},"iconColorHoverOne":{"r":0,"g":0,"b":0,"a":0},"iconShape":"circle","url":"#","animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"},"background":{"type":"default","color":{"type":"variable","id":"third"}},"backgroundHover":{"type":"default","color":{"type":"variable","id":"secondary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15","top":"","right":"","bottom":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"17","right":"16","bottom":"13"}},"Mobile":{"unit":"px","dimension":{"right":"17","left":"19","top":"12","bottom":"12"}}},"positioningType":{"Desktop":"inline","Mobile":"inline"},"positioningAlign":{"Desktop":"center","Mobile":"center"}} -->
			<div class="wp-block-gutenverse-icon guten-element guten-Aplvqa guten-icon animated guten-element-hide desktop-fadeInRight"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-play1-light"></i></a></div>
			<!-- /wp:gutenverse/icon -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-6Cdrmm","content":"Watch Video","url":"#","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":""},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"40"},"color":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"button1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":"uppercase","weight":"500","transform":"uppercase"},"positioningType":{"Desktop":"inline","Tablet":"inline","Mobile":"inline"},"positioningAlign":{"Tablet":"center","Desktop":"center","Mobile":"center"}} -->
			<div class="guten-element guten-button-wrapper guten-6Cdrmm"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Watch Video</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
