<?php
/**
 * Gutenverse Pricing FAQ content.
 */
return array(
	'title'      => __( 'Gutenverse Pricing FAQ', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-Crpm3R","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":""}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"120","bottom":"40"}}},"zIndex":{"Desktop":""},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="Crpm3R"><section class="wp-block-gutenverse-section guten-element guten-section guten-Crpm3R layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":45,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-wLgsux","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","right":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"10","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-wLgsux"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wLgsux"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-dTZt6W","type":5,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"default"},"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-dTZt6W animated guten-element-hide desktop-fadeInLeft">FAQ</h5>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-7Lox3m","textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"50"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-7Lox3m animated guten-element-hide desktop-fadeInLeft">Our Clients Reviews</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-szlnTH","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"forth"},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-szlnTH animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/accordions {"elementId":"guten-HYRz3U","iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right","iconColor":{"type":"variable","id":"secondary"},"iconActiveColor":{"type":"variable","id":"primary"},"iconSize":{"Desktop":"18"},"titleTextColor":{"type":"variable","id":"primary"},"titleActiveColor":{"type":"variable","id":"primary"},"titleTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Mobile":{"unit":"em","point":"1.5"}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"contentTextColor":{"type":"variable","id":"forth"},"contentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"35","bottom":"25","left":"35"}}},"accordionBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Mobile":[]},"all":{"type":"none","color":""}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"","left":""}},"Mobile":[]},"all":{"type":"none"}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"all":{"type":"none"}},"border":{"radius":{"Desktop":{}}},"boxShadow":{"horizontal":"","vertical":"","blur":"","spread":"","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"150"},"accordionBorderActive":{"radius":{"Desktop":{}}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"25","top":"","right":"","left":""}},"Mobile":[]},"contentBorderActive":{"radius":{"Desktop":[]}},"titleBackgroundActiveColor":{"type":"variable","id":"secondary"},"titleBorderActive":{"radius":{"Desktop":{}}},"accordionBoxShadow":{"color":{"r":46,"g":46,"b":46,"a":0.1},"horizontal":"0","vertical":"0","blur":"10","spread":"1"}} -->
			<div class="guten-element guten-accordions guten-HYRz3U animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/accordion {"elementId":"guten-WTgUPZ","iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
			<div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">Where Can I Find More Information?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-chevron-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion -->
			
			<!-- wp:gutenverse/accordion {"elementId":"guten-8PCeLk","iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
			<div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">What Kinds of Payment Do You Accept?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-chevron-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion -->
			
			<!-- wp:gutenverse/accordion {"elementId":"guten-GbQRZJ","first":true,"iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
			<div class="accordion-item active"><div class="accordion-heading"><span class="accordion-text">What Are Your Terms and Conditions?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-chevron-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion --></div>
			<!-- /wp:gutenverse/accordions --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":55,"Tablet":100},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-3PZU9O","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"flex-end","Tablet":"default"},"horizontalAlign":{"Desktop":"flex-end","Tablet":"center"},"border":{"radius":{"Desktop":[]},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3PZU9O animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3PZU9O"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Nw51dC","imgSrc":{"media":{"imageId":636,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":160,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com-160x300.webp","orientation":"portrait"},"large":{"height":1024,"width":545,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com-545x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com.webp","height":1128,"width":600,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"70"},"Tablet":{"point":"280","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Desktop":"right","Tablet":"center"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"},"hideMobile":true,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"80","bottom":"-10","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","left":"0","bottom":"0","right":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Tablet":"default"},"positioningAlign":{"Tablet":"flex-end"}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Nw51dC animated guten-element-hide slow desktop-fadeInRight hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( ACCOUNTRA_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com.webp" height="1128" width="600"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
