<?php
/**
 * Gutenverse Footer content.
 */
return array(
	'title'      => __( 'Gutenverse Footer', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"height":{},"gap":"no","elementId":"guten-akM3I6","background":{"type":"default","color":{"r":7,"g":7,"b":7,"a":1}},"backgroundHover":{},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"0","bottom":"20"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="akM3I6"><section class="wp-block-gutenverse-section guten-element guten-section guten-akM3I6 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-KgNDbe","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KgNDbe"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KgNDbe"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-88hTL3","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="88hTL3"><section class="wp-block-gutenverse-section guten-element guten-section guten-88hTL3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":32,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-txaqKl","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{},"Mobile":{}},"bottom":{"type":"solid","width":"1","color":{"r":234,"g":234,"b":234,"a":0.1}},"right":{"type":"solid","width":"1","color":{"r":234,"g":234,"b":234,"a":0.1}}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}},"Mobile":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"15","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-txaqKl"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="txaqKl"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-9B4B4o","title":"Give Us A Call","titleTag":"h4","description":"(+021) 645 863 232","icon":"fas fa-phone-alt","iconSize":{"Desktop":"30","Tablet":"25"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"5","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"iconColor":{"type":"variable","id":"secondary"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"3","top":"","right":"","left":""}},"Tablet":{}},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"type":"variable","id":"third"},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"25"}},"Mobile":{"unit":"px","dimension":{"left":"60","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}}}} -->
			<div class="guten-element guten-9B4B4o guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-phone-alt"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Give Us A Call</h4><p class="icon-box-description">(+021) 645 863 232</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":40,"Tablet":35},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ImxbkE","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"r":234,"g":234,"b":234,"a":0.1}},"right":{"color":{"r":234,"g":234,"b":234,"a":0.1},"type":"solid","width":"1"}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}},"Mobile":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ImxbkE"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ImxbkE"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-HWJ56j","title":"Send Us A Message","titleTag":"h4","description":"support@domain.com","icon":"fas fa-envelope","iconSize":{"Desktop":"30","Tablet":"25"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start","Tablet":null},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"5","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"iconColor":{"type":"variable","id":"secondary"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"3","top":"","right":"","left":""}},"Tablet":{}},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"type":"variable","id":"third"},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":"15"}},"Mobile":{"unit":"px","dimension":{"left":"50","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"left":"30","top":"","right":"","bottom":""}}}} -->
			<div class="guten-element guten-HWJ56j guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-envelope"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Send Us A Message</h4><p class="icon-box-description">support@domain.com</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":33},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-TJ21T9","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"r":234,"g":234,"b":234,"a":0.1}}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}},"Mobile":{},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-TJ21T9"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TJ21T9"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-1mxlk4","title":"Office Location","titleTag":"h4","description":"Jl. Sunset Road No.815","icon":"fas fa-map-marker-alt","iconSize":{"Desktop":"30","Tablet":"25"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"5","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"iconColor":{"type":"variable","id":"secondary"},"iconBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"3","top":"","right":"","left":""}},"Tablet":{}},"titleColor":{"type":"variable","id":"secondary"},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"type":"variable","id":"third"},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"","left":"35"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-1mxlk4 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-map-marker-alt"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Office Location</h4><p class="icon-box-description">Jl. Sunset Road No.815</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-3nzFEi","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"60"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"15","top":"","right":"","bottom":""}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="3nzFEi"><section class="wp-block-gutenverse-section guten-element guten-section guten-3nzFEi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":38},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-hyuPIE","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-hyuPIE"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hyuPIE"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-JRaLsm","imgSrc":{"media":{"imageId":206,"sizes":{"thumbnail":{"height":76,"width":150,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/logo-accountra-150x76.webp","orientation":"landscape"},"medium":{"height":57,"width":300,"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/logo-accountra-300x57.webp","orientation":"landscape"},"full":{"url":"' . esc_url( ACCOUNTRA_URI ) . 'assets/img/logo-accountra.webp","height":76,"width":400,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"65"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{}}},"align":{"Desktop":"left"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15","top":"","right":"","left":""}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-JRaLsm"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( ACCOUNTRA_URI ) . 'assets/img/logo-accountra.webp" height="76" width="400"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-cZC6uJ","textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"20"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-cZC6uJ"><div class="text-content-inner"><!-- wp:paragraph {"textColor":"white"} -->
			<p class="has-white-color has-text-color">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/social-icons {"elementId":"guten-sksmFE","iconSize":{"Desktop":{"point":"15","unit":"px"}},"gap":{"Desktop":"20"},"alignment":{"Desktop":"flex-start"},"shape":"circle","itemPadding":{"Desktop":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="guten-element guten-social-icons guten-sksmFE circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-GpagA5","iconColor":{"type":"variable","id":"primary"},"bgColor":{"type":"variable","id":"third"},"hoverIconColor":{"type":"variable","id":"primary"},"hoverBgColor":{"type":"variable","id":"secondary"}} -->
			<div class="guten-element guten-social-icon guten-GpagA5 facebook"><a id="guten-GpagA5"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-GP7TQC","iconColor":{"type":"variable","id":"primary"},"bgColor":{"type":"variable","id":"third"},"hoverIconColor":{"type":"variable","id":"primary"},"hoverBgColor":{"type":"variable","id":"secondary"}} -->
			<div class="guten-element guten-social-icon guten-GP7TQC twitter"><a id="guten-GP7TQC"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-gu7KR9","iconColor":{"type":"variable","id":"primary"},"bgColor":{"type":"variable","id":"third"},"hoverIconColor":{"type":"variable","id":"primary"},"hoverBgColor":{"type":"variable","id":"secondary"}} -->
			<div class="guten-element guten-social-icon guten-gu7KR9 instagram"><a id="guten-gu7KR9"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-pOVNb9","iconColor":{"type":"variable","id":"primary"},"bgColor":{"type":"variable","id":"third"},"hoverIconColor":{"type":"variable","id":"primary"},"hoverBgColor":{"type":"variable","id":"secondary"}} -->
			<div class="guten-element guten-social-icon guten-pOVNb9 pinterest"><a id="guten-pOVNb9"><i class="gtn gtn-pinterest-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":33,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-LTU3vs","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LTU3vs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LTU3vs"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-wCbRMc","type":6,"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-wCbRMc">Quick Links</h6>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-UUFQIc","spaceBetween":{"Desktop":"6"},"iconColor":{"r":252,"g":194,"b":54,"a":1},"textColor":{"type":"variable","id":"third"},"textColorHover":{"type":"variable","id":"secondary"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"}} -->
			<div class="guten-element guten-icon-list guten-UUFQIc"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-DffgXs","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-DffgXs"><a id="guten-DffgXs"><span class="list-text no-icon">About Us</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-CS8V5a","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-CS8V5a"><a id="guten-CS8V5a"><span class="list-text no-icon">Services</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-R9whki","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-R9whki"><a id="guten-R9whki"><span class="list-text no-icon">Cases</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-9zWuSz","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-9zWuSz"><a id="guten-9zWuSz"><span class="list-text no-icon">Pricing</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-KnPPVb","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-KnPPVb"><a id="guten-KnPPVb"><span class="list-text no-icon">Contact</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":29,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-9c0yN5","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9c0yN5"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9c0yN5"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-DbMxeu","type":6,"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-DbMxeu">Useful Links</h6>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-M79GF1","spaceBetween":{"Desktop":"6"},"iconColor":{"r":252,"g":194,"b":54,"a":1},"textColor":{"type":"variable","id":"third"},"textColorHover":{"type":"variable","id":"secondary"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"}} -->
			<div class="guten-element guten-icon-list guten-M79GF1"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-2mfSz8","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-2mfSz8"><a id="guten-2mfSz8"><span class="list-text no-icon">Privacy Policy</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-f2ROj8","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-f2ROj8"><a id="guten-f2ROj8"><span class="list-text no-icon">Terms and Conditions</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-v064Z4","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-v064Z4"><a id="guten-v064Z4"><span class="list-text no-icon">Disclaimer</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Z46RYn","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-Z46RYn"><a id="guten-Z46RYn"><span class="list-text no-icon">Support</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-4oZ1pV","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-4oZ1pV"><a id="guten-4oZ1pV"><span class="list-text no-icon">FAQ</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-d8qmBb","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-d8qmBb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="d8qmBb"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-pZ5DKm","type":6,"textAlign":{"Tablet":"center","Mobile":"left"},"color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-pZ5DKm">News Letter</h6>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-WB0FG6","alignment":{"Tablet":"center","Mobile":"left"},"textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"5"}},"Tablet":{"unit":"%","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"60","bottom":"","left":"0"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-WB0FG6"><div class="text-content-inner"><!-- wp:paragraph {"textColor":"white"} -->
			<p class="has-white-color has-text-color">Lorem ipsum dolor sit amet, consectetur adipisci elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-RQ9J9v","background":{},"backgroundHover":{},"topDivider":{},"bottomDivider":{},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="RQ9J9v"><section class="wp-block-gutenverse-section guten-element guten-section guten-RQ9J9v layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"elementId":"guten-ntVzub","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ntVzub"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ntVzub"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-4elOvi","formId":{"label":"Form Subscribe","value":542},"hideAfterSubmit":false,"redirectTo":"","background":{"type":"default","color":""},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":""}}}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{}}} -->
			<form style="display:none" class="guten-element guten-form-builder guten-4elOvi" data-form-id="542" data-hide-after="false" data-redirect=""><!-- wp:gutenverse/form-input-email {"elementId":"guten-UQlmMG","showLabel":false,"showHelper":false,"position":"left","labelColor":{"Desktop":{}},"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"helperColor":{"Desktop":{}},"helperPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"warningColor":{"Desktop":{}},"positioningType":{"Desktop":"custom","Mobile":"inline"},"positioningWidth":{"Desktop":{"unit":"%","point":"75"}},"positioningAlign":{"Mobile":"center"},"background":{"type":"default","color":""},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Your Email Address","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"60","bottom":"","left":""}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"60"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","top":"0","bottom":"0"}}},"placeholderColor":{"Desktop":{}},"inputTypography":{"size":{"Desktop":{"point":"12","unit":"px"}},"font":{"label":"Heebo","value":"Heebo","type":"google"}},"inputColorNormal":{"Desktop":{}},"inputBorderNormal":{"all":{"type":"none"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"5"}},"Tablet":{},"Mobile":{}}},"inputColorHover":{"Desktop":{}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"third"}}} -->
			<div class="guten-element guten-form-input-email guten-form-input guten-input-position-left guten-UQlmMG hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email Address" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-email -->
			
			<!-- wp:gutenverse/form-input-submit {"elementId":"guten-Ld5toI","content":"Send","buttonWidth":{"Desktop":"","Mobile":""},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":""},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"5","left":"0"}}}},"positioningType":{"Desktop":"inline","Mobile":"inline"},"positioningAlign":{"Mobile":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"-5"}},"Tablet":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"-5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"primary"},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500","transform":"uppercase"},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"20","bottom":"18","left":"20"}},"Tablet":{},"Mobile":{}}} -->
			<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-Ld5toI"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
			<!-- /wp:gutenverse/form-input-submit --></form>
			<!-- /wp:gutenverse/form-builder --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"width":{"Desktop":1140},"isChild":true,"height":{},"gap":"no","elementId":"guten-dhaT9S","verticalAlign":"center","background":{},"backgroundHover":{},"border":{"radius":{"Desktop":{"unit":"px"}},"top":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":0.1}}},"topDivider":{},"bottomDivider":{},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","left":"","right":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"8","right":"0","bottom":"12"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"animation":{},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="dhaT9S"><section class="wp-block-gutenverse-section guten-element guten-section guten-dhaT9S layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-K25aoc","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default","Tablet":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-K25aoc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="K25aoc"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-jVGahx","alignment":{"Desktop":"left","Tablet":"left","Mobile":"center"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningAlign":{"Mobile":"center"}} -->
			<div class="guten-element gutenverse-text-editor guten-jVGahx"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Accounting Firm Themes by Jegstudio</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sticky":{"Desktop":false},"topSticky":{"Desktop":{"point":"0","unit":"px"}},"bottomSticky":{"Desktop":{"point":"0","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-OMaljg","background":{},"backgroundHover":{},"verticalAlign":{"Desktop":"default","Tablet":"default","Mobile":"default"},"horizontalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}},"animation":{}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OMaljg"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OMaljg"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-Sx4N9N","alignment":{"Desktop":"right","Tablet":"right","Mobile":"center"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-Sx4N9N"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Copyright © 2022. All rights reserved.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
